// Auto-generated by scripts/updateData.js — last update: 2026-05-31
// CZ: product pair co-occurrence from order export

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;   // number of orders containing both products
  pct: number;     // % of total orders
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataCZ: CrossSellData = {
  "totalOrders": 5921,
  "multiItemOrders": 5294,
  "pairs": [
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 756,
      "pct": 12.77
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 536,
      "pct": 9.05
    },
    {
      "productA": "Ovocné trubičky - jahoda 2ks (25g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 375,
      "pct": 6.33
    },
    {
      "productA": "Ovocné trubičky - malina 2ks (25g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 372,
      "pct": 6.28
    },
    {
      "productA": "Ovocné trubičky - malina 2ks (25g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 357,
      "pct": 6.03
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "count": 355,
      "pct": 6
    },
    {
      "productA": "Ovocné trubičky - jahoda 2ks (25g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 350,
      "pct": 5.91
    },
    {
      "productA": "Ovocné trubičky - mango 2ks (25g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 339,
      "pct": 5.73
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 325,
      "pct": 5.49
    },
    {
      "productA": "Ovocné trubičky - malina 2ks (25g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 320,
      "pct": 5.4
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 311,
      "pct": 5.25
    },
    {
      "productA": "Ovocné trubičky - jahoda 2ks (25g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 305,
      "pct": 5.15
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 293,
      "pct": 4.95
    },
    {
      "productA": "Ovocné trubičky - mango 2ks (25g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 280,
      "pct": 4.73
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s karamelovou polevou 43ks (540g)",
      "count": 275,
      "pct": 4.64
    },
    {
      "productA": "Ovocné trubičky - meruňka 2ks (25g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 274,
      "pct": 4.63
    },
    {
      "productA": "Ovocné trubičky - jahoda 2ks (25g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 257,
      "pct": 4.34
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 238,
      "pct": 4.02
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 232,
      "pct": 3.92
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 223,
      "pct": 3.77
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 222,
      "pct": 3.75
    },
    {
      "productA": "Ovocné trubičky - jablko 2ks (25g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 215,
      "pct": 3.63
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 212,
      "pct": 3.58
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - jahoda 2ks (25g)",
      "count": 209,
      "pct": 3.53
    },
    {
      "productA": "Ovocné trubičky - jablko 2ks (25g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 208,
      "pct": 3.51
    },
    {
      "productA": "Ovocné trubičky - jablko 2ks (25g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 207,
      "pct": 3.5
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 206,
      "pct": 3.48
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. OVOCNASLEVA20 - Sleva 20%",
      "count": 205,
      "pct": 3.46
    },
    {
      "productA": "Ovocné trubičky - jablko 2ks (25g)",
      "productB": "Ovocné trubičky - jahoda 2ks (25g)",
      "count": 203,
      "pct": 3.43
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 200,
      "pct": 3.38
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "count": 199,
      "pct": 3.36
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou bez přidaného cukru 43ks (540g)",
      "count": 191,
      "pct": 3.23
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "count": 191,
      "pct": 3.23
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "count": 190,
      "pct": 3.21
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "count": 190,
      "pct": 3.21
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou a skořicí (100g)",
      "count": 189,
      "pct": 3.19
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou a skořicí (100g)",
      "count": 187,
      "pct": 3.16
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 184,
      "pct": 3.11
    },
    {
      "productA": "Jablečné trubičky s karamelovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 181,
      "pct": 3.06
    },
    {
      "productA": "Ovocné trubičky - jablko 2ks (25g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 178,
      "pct": 3.01
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 43ks (540g)",
      "count": 177,
      "pct": 2.99
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - jahoda 2ks (25g)",
      "count": 176,
      "pct": 2.97
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. MLSEJ100 - Sleva 100 Kč",
      "count": 174,
      "pct": 2.94
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou a skořicí (100g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 173,
      "pct": 2.92
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s karamelovou polevou 43ks (540g)",
      "count": 172,
      "pct": 2.9
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "count": 171,
      "pct": 2.89
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou a skořicí (100g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 171,
      "pct": 2.89
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 170,
      "pct": 2.87
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 168,
      "pct": 2.84
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 160,
      "pct": 2.7
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 155,
      "pct": 2.62
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 2ks (24g)",
      "count": 155,
      "pct": 2.62
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 154,
      "pct": 2.6
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 151,
      "pct": 2.55
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "count": 148,
      "pct": 2.5
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 146,
      "pct": 2.47
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. ZDRAVYLEDEN20 - Sleva 20%",
      "count": 145,
      "pct": 2.45
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 2ks (24g)",
      "count": 143,
      "pct": 2.42
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou a skořicí (100g)",
      "count": 143,
      "pct": 2.42
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "count": 143,
      "pct": 2.42
    },
    {
      "productA": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "productB": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 142,
      "pct": 2.4
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s jogurtovou polevou a višní 43ks (540g)",
      "count": 140,
      "pct": 2.36
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 139,
      "pct": 2.35
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 138,
      "pct": 2.33
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 137,
      "pct": 2.31
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. OVOCNASLEVA20 - Sleva 20%",
      "count": 136,
      "pct": 2.3
    },
    {
      "productA": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "productB": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 134,
      "pct": 2.26
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 2ks (24g)",
      "count": 134,
      "pct": 2.26
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a višní 43ks (540g)",
      "count": 133,
      "pct": 2.25
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 133,
      "pct": 2.25
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 131,
      "pct": 2.21
    },
    {
      "productA": "Jahodové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "productB": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "count": 129,
      "pct": 2.18
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou bez přidaného cukru 43ks (540g)",
      "count": 129,
      "pct": 2.18
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "count": 125,
      "pct": 2.11
    },
    {
      "productA": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "productB": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 124,
      "pct": 2.09
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 123,
      "pct": 2.08
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 43ks (540g)",
      "count": 122,
      "pct": 2.06
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 122,
      "pct": 2.06
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 121,
      "pct": 2.04
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jahodové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "count": 119,
      "pct": 2.01
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 117,
      "pct": 1.98
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - jahoda 2ks (25g)",
      "count": 116,
      "pct": 1.96
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 116,
      "pct": 1.96
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 115,
      "pct": 1.94
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 115,
      "pct": 1.94
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - MIX",
      "count": 115,
      "pct": 1.94
    },
    {
      "productA": "Jahodové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "productB": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 114,
      "pct": 1.93
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 114,
      "pct": 1.93
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. OVOCNASLEVA20 - Sleva 20%",
      "count": 114,
      "pct": 1.93
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 113,
      "pct": 1.91
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. ZDRAVYLEDEN20 - Sleva 20%",
      "count": 113,
      "pct": 1.91
    },
    {
      "productA": "Jahodové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "productB": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 111,
      "pct": 1.87
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 111,
      "pct": 1.87
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s jogurtovou polevou a višní 43ks (540g)",
      "count": 109,
      "pct": 1.84
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 106,
      "pct": 1.79
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Ovocné trubičky - jahoda 2ks (25g)",
      "count": 106,
      "pct": 1.79
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - jahoda 2ks (25g)",
      "count": 106,
      "pct": 1.79
    },
    {
      "productA": "Jablečné trubičky s karobovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 104,
      "pct": 1.76
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 103,
      "pct": 1.74
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 103,
      "pct": 1.74
    }
  ]
};
