// Auto-generated by scripts/updateData.js — last update: 2026-05-25
// CZ: product pair co-occurrence from order export

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;   // number of orders containing both products
  pct: number;     // % of total orders
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataCZ: CrossSellData = {
  "totalOrders": 6967,
  "multiItemOrders": 6256,
  "pairs": [
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 848,
      "pct": 12.17
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 620,
      "pct": 8.9
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "count": 396,
      "pct": 5.68
    },
    {
      "productA": "Ovocné trubičky - jahoda 2ks (25g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 390,
      "pct": 5.6
    },
    {
      "productA": "Ovocné trubičky - malina 2ks (25g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 385,
      "pct": 5.53
    },
    {
      "productA": "Ovocné trubičky - malina 2ks (25g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 369,
      "pct": 5.3
    },
    {
      "productA": "Ovocné trubičky - jahoda 2ks (25g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 359,
      "pct": 5.15
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 356,
      "pct": 5.11
    },
    {
      "productA": "Ovocné trubičky - mango 2ks (25g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 345,
      "pct": 4.95
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 341,
      "pct": 4.89
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 333,
      "pct": 4.78
    },
    {
      "productA": "Ovocné trubičky - malina 2ks (25g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 331,
      "pct": 4.75
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s karamelovou polevou 43ks (540g)",
      "count": 322,
      "pct": 4.62
    },
    {
      "productA": "Ovocné trubičky - jahoda 2ks (25g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 314,
      "pct": 4.51
    },
    {
      "productA": "Ovocné trubičky - mango 2ks (25g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 286,
      "pct": 4.11
    },
    {
      "productA": "Ovocné trubičky - meruňka 2ks (25g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 281,
      "pct": 4.03
    },
    {
      "productA": "Ovocné trubičky - jahoda 2ks (25g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 266,
      "pct": 3.82
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 264,
      "pct": 3.79
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 248,
      "pct": 3.56
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 248,
      "pct": 3.56
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 240,
      "pct": 3.44
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 228,
      "pct": 3.27
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "count": 221,
      "pct": 3.17
    },
    {
      "productA": "Ovocné trubičky - jablko 2ks (25g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 221,
      "pct": 3.17
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "count": 218,
      "pct": 3.13
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou bez přidaného cukru 43ks (540g)",
      "count": 218,
      "pct": 3.13
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - jahoda 2ks (25g)",
      "count": 215,
      "pct": 3.09
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "count": 214,
      "pct": 3.07
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "count": 214,
      "pct": 3.07
    },
    {
      "productA": "Ovocné trubičky - jablko 2ks (25g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 213,
      "pct": 3.06
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 211,
      "pct": 3.03
    },
    {
      "productA": "Ovocné trubičky - jablko 2ks (25g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 211,
      "pct": 3.03
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s karamelovou polevou 43ks (540g)",
      "count": 210,
      "pct": 3.01
    },
    {
      "productA": "Ovocné trubičky - jablko 2ks (25g)",
      "productB": "Ovocné trubičky - jahoda 2ks (25g)",
      "count": 210,
      "pct": 3.01
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 208,
      "pct": 2.99
    },
    {
      "productA": "Jablečné trubičky s karamelovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 205,
      "pct": 2.94
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. OVOCNASLEVA20 - Sleva 20%",
      "count": 205,
      "pct": 2.94
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "count": 198,
      "pct": 2.84
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 43ks (540g)",
      "count": 192,
      "pct": 2.76
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 191,
      "pct": 2.74
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 189,
      "pct": 2.71
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou a skořicí (100g)",
      "count": 189,
      "pct": 2.71
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou a skořicí (100g)",
      "count": 187,
      "pct": 2.68
    },
    {
      "productA": "Ovocné trubičky - jablko 2ks (25g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 184,
      "pct": 2.64
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - jahoda 2ks (25g)",
      "count": 182,
      "pct": 2.61
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 2ks (24g)",
      "count": 179,
      "pct": 2.57
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 177,
      "pct": 2.54
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. MLSEJ100 - Sleva 100 Kč",
      "count": 174,
      "pct": 2.5
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 174,
      "pct": 2.5
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 173,
      "pct": 2.48
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou a skořicí (100g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 173,
      "pct": 2.48
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou a skořicí (100g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 171,
      "pct": 2.45
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 170,
      "pct": 2.44
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "count": 169,
      "pct": 2.43
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "count": 163,
      "pct": 2.34
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 159,
      "pct": 2.28
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s jogurtovou polevou a višní 43ks (540g)",
      "count": 159,
      "pct": 2.28
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 2ks (24g)",
      "count": 157,
      "pct": 2.25
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 156,
      "pct": 2.24
    },
    {
      "productA": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "productB": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 155,
      "pct": 2.22
    },
    {
      "productA": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "productB": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 151,
      "pct": 2.17
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 2ks (24g)",
      "count": 147,
      "pct": 2.11
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 147,
      "pct": 2.11
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a višní 43ks (540g)",
      "count": 146,
      "pct": 2.1
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. ZDRAVYLEDEN20 - Sleva 20%",
      "count": 145,
      "pct": 2.08
    },
    {
      "productA": "Jahodové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "productB": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "count": 144,
      "pct": 2.07
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou bez přidaného cukru 43ks (540g)",
      "count": 144,
      "pct": 2.07
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou a skořicí (100g)",
      "count": 143,
      "pct": 2.05
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - MIX",
      "count": 143,
      "pct": 2.05
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 141,
      "pct": 2.02
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 141,
      "pct": 2.02
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 139,
      "pct": 2
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 138,
      "pct": 1.98
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 138,
      "pct": 1.98
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "count": 137,
      "pct": 1.97
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. OVOCNASLEVA20 - Sleva 20%",
      "count": 136,
      "pct": 1.95
    },
    {
      "productA": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "productB": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 135,
      "pct": 1.94
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 43ks (540g)",
      "count": 132,
      "pct": 1.89
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jahodové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "count": 128,
      "pct": 1.84
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 126,
      "pct": 1.81
    },
    {
      "productA": "Jahodové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "productB": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 125,
      "pct": 1.79
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 125,
      "pct": 1.79
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 124,
      "pct": 1.78
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 122,
      "pct": 1.75
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - MIX",
      "count": 122,
      "pct": 1.75
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 121,
      "pct": 1.74
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s jogurtovou polevou a višní 43ks (540g)",
      "count": 121,
      "pct": 1.74
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 121,
      "pct": 1.74
    },
    {
      "productA": "Jahodové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "productB": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 120,
      "pct": 1.72
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - jahoda 2ks (25g)",
      "count": 119,
      "pct": 1.71
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 119,
      "pct": 1.71
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 119,
      "pct": 1.71
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Sušené mango premium 100g",
      "count": 117,
      "pct": 1.68
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 116,
      "pct": 1.66
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "count": 116,
      "pct": 1.66
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 116,
      "pct": 1.66
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s karobovou polevou 43ks (540g)",
      "count": 115,
      "pct": 1.65
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. OVOCNASLEVA20 - Sleva 20%",
      "count": 114,
      "pct": 1.64
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. ZDRAVYLEDEN20 - Sleva 20%",
      "count": 113,
      "pct": 1.62
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 111,
      "pct": 1.59
    }
  ]
};
