// Auto-generated by scripts/updateData.js — last update: 2026-06-18
// CZ: product pair co-occurrence from order export

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;   // number of orders containing both products
  pct: number;     // % of total orders
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataCZ: CrossSellData = {
  "totalOrders": 7172,
  "multiItemOrders": 6421,
  "pairs": [
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 859,
      "pct": 11.98
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 633,
      "pct": 8.83
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "count": 396,
      "pct": 5.52
    },
    {
      "productA": "Ovocné trubičky - jahoda 2ks (25g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 393,
      "pct": 5.48
    },
    {
      "productA": "Ovocné trubičky - malina 2ks (25g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 386,
      "pct": 5.38
    },
    {
      "productA": "Ovocné trubičky - malina 2ks (25g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 372,
      "pct": 5.19
    },
    {
      "productA": "Ovocné trubičky - jahoda 2ks (25g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 360,
      "pct": 5.02
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 356,
      "pct": 4.96
    },
    {
      "productA": "Ovocné trubičky - mango 2ks (25g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 346,
      "pct": 4.82
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 341,
      "pct": 4.75
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 337,
      "pct": 4.7
    },
    {
      "productA": "Ovocné trubičky - malina 2ks (25g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 333,
      "pct": 4.64
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s karamelovou polevou 43ks (540g)",
      "count": 332,
      "pct": 4.63
    },
    {
      "productA": "Ovocné trubičky - jahoda 2ks (25g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 316,
      "pct": 4.41
    },
    {
      "productA": "Ovocné trubičky - mango 2ks (25g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 286,
      "pct": 3.99
    },
    {
      "productA": "Ovocné trubičky - meruňka 2ks (25g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 284,
      "pct": 3.96
    },
    {
      "productA": "Ovocné trubičky - jahoda 2ks (25g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 269,
      "pct": 3.75
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 265,
      "pct": 3.69
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 248,
      "pct": 3.46
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 248,
      "pct": 3.46
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 241,
      "pct": 3.36
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 228,
      "pct": 3.18
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou bez přidaného cukru 43ks (540g)",
      "count": 225,
      "pct": 3.14
    },
    {
      "productA": "Ovocné trubičky - jablko 2ks (25g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 222,
      "pct": 3.1
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "count": 221,
      "pct": 3.08
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "count": 218,
      "pct": 3.04
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s karamelovou polevou 43ks (540g)",
      "count": 217,
      "pct": 3.03
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "count": 216,
      "pct": 3.01
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "count": 215,
      "pct": 3
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - jahoda 2ks (25g)",
      "count": 215,
      "pct": 3
    },
    {
      "productA": "Ovocné trubičky - jablko 2ks (25g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 214,
      "pct": 2.98
    },
    {
      "productA": "Ovocné trubičky - jablko 2ks (25g)",
      "productB": "Ovocné trubičky - jahoda 2ks (25g)",
      "count": 213,
      "pct": 2.97
    },
    {
      "productA": "Ovocné trubičky - jablko 2ks (25g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 212,
      "pct": 2.96
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 211,
      "pct": 2.94
    },
    {
      "productA": "Jablečné trubičky s karamelovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 209,
      "pct": 2.91
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 208,
      "pct": 2.9
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. OVOCNASLEVA20 - Sleva 20%",
      "count": 205,
      "pct": 2.86
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "count": 198,
      "pct": 2.76
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 43ks (540g)",
      "count": 194,
      "pct": 2.7
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 192,
      "pct": 2.68
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 189,
      "pct": 2.64
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou a skořicí (100g)",
      "count": 189,
      "pct": 2.64
    },
    {
      "productA": "Ovocné trubičky - jablko 2ks (25g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 188,
      "pct": 2.62
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou a skořicí (100g)",
      "count": 187,
      "pct": 2.61
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 2ks (24g)",
      "count": 186,
      "pct": 2.59
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - jahoda 2ks (25g)",
      "count": 182,
      "pct": 2.54
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 177,
      "pct": 2.47
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 176,
      "pct": 2.45
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. MLSEJ100 - Sleva 100 Kč",
      "count": 174,
      "pct": 2.43
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 174,
      "pct": 2.43
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou a skořicí (100g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 173,
      "pct": 2.41
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou a skořicí (100g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 171,
      "pct": 2.38
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 171,
      "pct": 2.38
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "count": 169,
      "pct": 2.36
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 2ks (24g)",
      "count": 164,
      "pct": 2.29
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "count": 163,
      "pct": 2.27
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 161,
      "pct": 2.24
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s jogurtovou polevou a višní 43ks (540g)",
      "count": 160,
      "pct": 2.23
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 159,
      "pct": 2.22
    },
    {
      "productA": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "productB": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 155,
      "pct": 2.16
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 2ks (24g)",
      "count": 153,
      "pct": 2.13
    },
    {
      "productA": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "productB": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 152,
      "pct": 2.12
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 151,
      "pct": 2.11
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a višní 43ks (540g)",
      "count": 149,
      "pct": 2.08
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 148,
      "pct": 2.06
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - MIX",
      "count": 147,
      "pct": 2.05
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou bez přidaného cukru 43ks (540g)",
      "count": 145,
      "pct": 2.02
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. ZDRAVYLEDEN20 - Sleva 20%",
      "count": 145,
      "pct": 2.02
    },
    {
      "productA": "Jahodové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "productB": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "count": 144,
      "pct": 2.01
    },
    {
      "productA": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou a skořicí (100g)",
      "count": 143,
      "pct": 1.99
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 141,
      "pct": 1.97
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 140,
      "pct": 1.95
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 138,
      "pct": 1.92
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 138,
      "pct": 1.92
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "count": 137,
      "pct": 1.91
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Slevový kupon č. OVOCNASLEVA20 - Sleva 20%",
      "count": 136,
      "pct": 1.9
    },
    {
      "productA": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "productB": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 135,
      "pct": 1.88
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 43ks (540g)",
      "count": 134,
      "pct": 1.87
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jahodové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "count": 130,
      "pct": 1.81
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - černý rybíz 2ks (25g)",
      "count": 126,
      "pct": 1.76
    },
    {
      "productA": "Jahodové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "productB": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 126,
      "pct": 1.76
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 126,
      "pct": 1.76
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 125,
      "pct": 1.74
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 124,
      "pct": 1.73
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - MIX",
      "count": 124,
      "pct": 1.73
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 122,
      "pct": 1.7
    },
    {
      "productA": "Jahodové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "productB": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
      "count": 121,
      "pct": 1.69
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 121,
      "pct": 1.69
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s jogurtovou polevou a višní 43ks (540g)",
      "count": 121,
      "pct": 1.69
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - jahoda 2ks (25g)",
      "count": 119,
      "pct": 1.66
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Ovocné trubičky - malina 2ks (25g)",
      "count": 119,
      "pct": 1.66
    },
    {
      "productA": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 119,
      "pct": 1.66
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s karobovou polevou 43ks (540g)",
      "count": 117,
      "pct": 1.63
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Sušené mango premium 100g",
      "count": 117,
      "pct": 1.63
    },
    {
      "productA": "Jablečné kuličky s jogurtovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - meruňka 2ks (25g)",
      "count": 116,
      "pct": 1.62
    },
    {
      "productA": "Jablečné kuličky natural RAW (100g)",
      "productB": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "count": 116,
      "pct": 1.62
    },
    {
      "productA": "Jablečné kuličky s jahodovou polevou a kokosem (100g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 116,
      "pct": 1.62
    },
    {
      "productA": "Jablečné trubičky s karobovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
      "count": 114,
      "pct": 1.59
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou bez přidaného cukru 43ks (540g)",
      "count": 114,
      "pct": 1.59
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 2ks (24g)",
      "productB": "Jablečné trubičky s karobovou polevou 2ks (24g)",
      "count": 114,
      "pct": 1.59
    }
  ]
};
