// Auto-generated by scripts/updateData.js — last update: 2026-04-07
// SK: product pair co-occurrence from order export

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;   // number of orders containing both products
  pct: number;     // % of total orders
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataSK: CrossSellData = {
  "totalOrders": 287,
  "multiItemOrders": 270,
  "pairs": [
    {
      "productA": "Jablkové trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "count": 27,
      "pct": 9.41
    },
    {
      "productA": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 25,
      "pct": 8.71
    },
    {
      "productA": "Jablkové trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 20,
      "pct": 6.97
    },
    {
      "productA": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablkové trubičky s karamelovou polevou 43ks (540g)",
      "count": 18,
      "pct": 6.27
    },
    {
      "productA": "Jablkové trubičky s karamelovou polevou 43ks (540g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 16,
      "pct": 5.57
    },
    {
      "productA": "Jablkové guľôčky s jahodovou polevou a kokosom (100g)",
      "productB": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "count": 14,
      "pct": 4.88
    },
    {
      "productA": "Ovocné chrumky - jahoda (100g)",
      "productB": "Ovocné chrumky - mango (100g)",
      "count": 12,
      "pct": 4.18
    },
    {
      "productA": "Jablkové trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablkové trubičky s karamelovou polevou 43ks (540g)",
      "count": 12,
      "pct": 4.18
    },
    {
      "productA": "Jablkové trubičky s čokoládovou polevou bez pridaného cukru 43ks (540g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 12,
      "pct": 4.18
    },
    {
      "productA": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablkové trubičky s čokoládovou polevou bez pridaného cukru 43ks (540g)",
      "count": 12,
      "pct": 4.18
    },
    {
      "productA": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Zľavový kupón číslo VELIKONOCE10 - Zľava 10%",
      "count": 12,
      "pct": 4.18
    },
    {
      "productA": "Jablkové trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 11,
      "pct": 3.83
    },
    {
      "productA": "Jablkové trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablkové trubičky s jogurtovou polevou a čerešňou 43ks (540g)",
      "count": 11,
      "pct": 3.83
    },
    {
      "productA": "Jablkové trubičky s jogurtovou polevou a čerešňou 43ks (540g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 11,
      "pct": 3.83
    },
    {
      "productA": "Ovocné chrumky - mango (100g)",
      "productB": "Ovocné chrumky - marhuľa (100g)",
      "count": 11,
      "pct": 3.83
    },
    {
      "productA": "Ovocné chrumky - jahoda (100g)",
      "productB": "Ovocné chrumky - malina (100g)",
      "count": 10,
      "pct": 3.48
    },
    {
      "productA": "Ovocné chrumky - mango (100g)",
      "productB": "Ovocné pusinky - čierne ríbezle (100g)",
      "count": 10,
      "pct": 3.48
    },
    {
      "productA": "Jablkové guľôčky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Jablkové trubičky s čokoládovou polevou 43ks (540g)",
      "count": 10,
      "pct": 3.48
    },
    {
      "productA": "Jablkové guľôčky s jogurtovou polevou a kokosom (100g)",
      "productB": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "count": 10,
      "pct": 3.48
    },
    {
      "productA": "Jablkové guľôčky s jogurtovou polevou a kokosom (100g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 10,
      "pct": 3.48
    },
    {
      "productA": "Jablkové trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Zľavový kupón číslo VELIKONOCE10 - Zľava 10%",
      "count": 10,
      "pct": 3.48
    },
    {
      "productA": "Jablkové trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Zľavový kupón číslo VELIKONOCE10 - Zľava 10%",
      "count": 10,
      "pct": 3.48
    },
    {
      "productA": "Jablkové guľôčky prírodné RAW (100g)",
      "productB": "Jablkové guľôčky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "count": 9,
      "pct": 3.14
    },
    {
      "productA": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablkové trubičky s čokoládovou polevou 43ks (540g)",
      "count": 9,
      "pct": 3.14
    },
    {
      "productA": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - malina 33ks (380g)",
      "count": 9,
      "pct": 3.14
    },
    {
      "productA": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablkové trubičky s jogurtovou polevou a čerešňou 43ks (540g)",
      "count": 9,
      "pct": 3.14
    },
    {
      "productA": "Jablkové guľôčky s jahodovou polevou a kokosom (100g)",
      "productB": "Jablkové guľôčky s jogurtovou polevou a kokosom (100g)",
      "count": 9,
      "pct": 3.14
    },
    {
      "productA": "Jablkové guľôčky prírodné RAW (100g)",
      "productB": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "count": 9,
      "pct": 3.14
    },
    {
      "productA": "Ovocné chrumky - marhuľa (100g)",
      "productB": "Ovocné pusinky - čierne ríbezle (100g)",
      "count": 9,
      "pct": 3.14
    },
    {
      "productA": "Jablkové guľôčky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 9,
      "pct": 3.14
    },
    {
      "productA": "Ovocné chrumky - jahoda (100g)",
      "productB": "Ovocné chrumky - marhuľa (100g)",
      "count": 9,
      "pct": 3.14
    },
    {
      "productA": "Jablkové guľôčky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "count": 9,
      "pct": 3.14
    },
    {
      "productA": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 9,
      "pct": 3.14
    },
    {
      "productA": "Jablkové guľôčky s jahodovou polevou a kokosom (100g)",
      "productB": "Jablkové trubičky s jahodovou polevou 43ks (540g)",
      "count": 9,
      "pct": 3.14
    },
    {
      "productA": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Mango trubičky s jogurtovou polevou 18ks (220g)",
      "count": 9,
      "pct": 3.14
    },
    {
      "productA": "Ovocné chrumky - malina (100g)",
      "productB": "Ovocné chrumky - mango (100g)",
      "count": 8,
      "pct": 2.79
    },
    {
      "productA": "Jablkové trubičky s karamelovou polevou 43ks (540g)",
      "productB": "Jablkové trubičky s čokoládovou polevou 43ks (540g)",
      "count": 8,
      "pct": 2.79
    },
    {
      "productA": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Lyofilizované jahody 100g",
      "count": 8,
      "pct": 2.79
    },
    {
      "productA": "Jablkové trubičky s jogurtovou polevou a čerešňou 43ks (540g)",
      "productB": "Jablkové trubičky s karamelovou polevou 43ks (540g)",
      "count": 8,
      "pct": 2.79
    },
    {
      "productA": "Jablkové trubičky s karamelovou polevou 43ks (540g)",
      "productB": "Jablkové trubičky s čokoládovou polevou bez pridaného cukru 43ks (540g)",
      "count": 8,
      "pct": 2.79
    },
    {
      "productA": "Ovocné trubičky - jahoda 33ks (380g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 8,
      "pct": 2.79
    },
    {
      "productA": "Jablkové guľôčky s jogurtovou polevou a kokosom (100g)",
      "productB": "Jablkové guľôčky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "count": 8,
      "pct": 2.79
    },
    {
      "productA": "Lyofilizované jahody 100g",
      "productB": "Lyofilizované mango 100g",
      "count": 8,
      "pct": 2.79
    },
    {
      "productA": "Jablkové guľôčky prírodné RAW (100g)",
      "productB": "Jablkové trubičky s čokoládovou polevou 43ks (540g)",
      "count": 8,
      "pct": 2.79
    },
    {
      "productA": "Ovocné chrumky - jahoda (100g)",
      "productB": "Ovocné pusinky - čierne ríbezle (100g)",
      "count": 7,
      "pct": 2.44
    },
    {
      "productA": "Jablkové trubičky s čokoládovou polevou a čerešňou 43ks (540g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 7,
      "pct": 2.44
    },
    {
      "productA": "Ovocné chrumky - malina (100g)",
      "productB": "Ovocné chrumky - marhuľa (100g)",
      "count": 7,
      "pct": 2.44
    },
    {
      "productA": "Jablkové guľôčky prírodné RAW (100g)",
      "productB": "Jablkové guľôčky s jogurtovou polevou a kokosom (100g)",
      "count": 7,
      "pct": 2.44
    },
    {
      "productA": "Jablkové trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Ovocné chrumky - jahoda (100g)",
      "count": 7,
      "pct": 2.44
    },
    {
      "productA": "Lyofilizované jahody 100g",
      "productB": "Ovocné trubičky - jahoda 33ks (380g)",
      "count": 7,
      "pct": 2.44
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
      "count": 7,
      "pct": 2.44
    },
    {
      "productA": "Jablkové guľôčky s jahodovou polevou a kokosom (100g)",
      "productB": "Jablkové trubičky s čokoládovou polevou 43ks (540g)",
      "count": 7,
      "pct": 2.44
    },
    {
      "productA": "Jablkové trubičky s karamelovou polevou 43ks (540g)",
      "productB": "Zľavový kupón číslo VELIKONOCE10 - Zľava 10%",
      "count": 7,
      "pct": 2.44
    },
    {
      "productA": "Jablkové trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jablkové trubičky s čokoládovou polevou a čiernymi ríbezľami 43ks (540g)",
      "count": 6,
      "pct": 2.09
    },
    {
      "productA": "Jablkové rúrky 2ks - MIX",
      "productB": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "count": 6,
      "pct": 2.09
    },
    {
      "productA": "Jablkové rúrky 2ks - MIX",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 6,
      "pct": 2.09
    },
    {
      "productA": "Ovocné chrumky - mango (100g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 6,
      "pct": 2.09
    },
    {
      "productA": "Jablkové guľôčky s jahodovou polevou a kokosom (100g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 6,
      "pct": 2.09
    },
    {
      "productA": "Ovocné chrumky - jahoda (100g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 6,
      "pct": 2.09
    },
    {
      "productA": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - jahoda 33ks (380g)",
      "count": 6,
      "pct": 2.09
    },
    {
      "productA": "Jablkové guľôčky s jahodovou polevou a kokosom (100g)",
      "productB": "Jablkové trubičky s čokoládovou polevou bez pridaného cukru 43ks (540g)",
      "count": 6,
      "pct": 2.09
    },
    {
      "productA": "Jablkové trubičky s karamelovou polevou 43ks (540g)",
      "productB": "Lyofilizované jahody 100g",
      "count": 6,
      "pct": 2.09
    },
    {
      "productA": "Jablkové trubičky s čokoládovou polevou bez pridaného cukru 43ks (540g)",
      "productB": "Lyofilizované jahody 100g",
      "count": 6,
      "pct": 2.09
    },
    {
      "productA": "Jablkové trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - jahoda 33ks (380g)",
      "count": 6,
      "pct": 2.09
    },
    {
      "productA": "Ovocné trubičky - jahoda 33ks (380g)",
      "productB": "Ovocné trubičky - mango 33ks (380g)",
      "count": 6,
      "pct": 2.09
    },
    {
      "productA": "Jablkové guľôčky prírodné RAW (100g)",
      "productB": "Zľavový kupón číslo VELIKONOCE10 - Zľava 10%",
      "count": 6,
      "pct": 2.09
    },
    {
      "productA": "Jablkové guľôčky prírodné RAW (100g)",
      "productB": "Ovocné chrumky - jahoda (100g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové guľôčky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "productB": "Ovocné chrumky - jahoda (100g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Ovocné trubičky - mango 33ks (380g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Jablkové trubičky s čokoládovou polevou bez pridaného cukru 43ks (540g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové trubičky s čokoládovou polevou BEZ PALMOVÉHO TUKU 43ks (540g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Ovocné chrumky - marhuľa (100g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové guľôčky s jogurtovou polevou a kokosom (100g)",
      "productB": "Jablkové trubičky s jogurtovou polevou a čerešňou 43ks (540g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové guľôčky s čokoládovou polevou a škoricou (100g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablkové trubičky s čokoládovou polevou bez pridaného cukru 43ks (540g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové guľôčky prírodné RAW (100g)",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Ovocné chrumky - mango (100g)",
      "productB": "Ovocné trubičky - jahoda 33ks (380g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové guľôčky s jogurtovou polevou a kokosom (100g)",
      "productB": "Jablkové trubičky s jahodovou polevou 43ks (540g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Ovocné chrumky - mango (100g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Lyofilizované jahody 100g",
      "productB": "Zľavový kupón číslo ZDRAVYLEDEN20 - Zľava 20%",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Ovocné trubičky - jahoda 33ks (380g)",
      "productB": "Ovocné trubičky - malina 33ks (380g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Ovocné trubičky - malina 2ks (25g)",
      "productB": "Ovocné trubičky - mango 2ks (25g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové guľôčky prírodné RAW (100g)",
      "productB": "Jablkové guľôčky s jahodovou polevou a kokosom (100g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové guľôčky s jahodovou polevou a kokosom (100g)",
      "productB": "Jablkové trubičky s karamelovou polevou 43ks (540g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové guľôčky s jahodovou polevou a kokosom (100g)",
      "productB": "Ovocné chrumky - jahoda (100g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné chrumky - jahoda (100g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Lyofilizované jahody 100g",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Ovocné chrumky - malina (100g)",
      "productB": "Ovocné trubičky - jahoda 33ks (380g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové trubičky s jahodovou polevou 43ks (540g)",
      "productB": "Jablkové trubičky s čokoládovou polevou 43ks (540g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové guľôčky s jahodovou polevou a kokosom (100g)",
      "productB": "Lyofilizované jahody 100g",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové trubičky s čokoládovou polevou 43ks (540g)",
      "productB": "Polomáčané malinové trubičky s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové guľôčky s jahodovou polevou a kokosom (100g)",
      "productB": "Jablkové guľôčky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Ovocné chrumky - jahoda (100g)",
      "productB": "Ovocné rúrky - MIX",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Ovocné chrumky - mango (100g)",
      "productB": "Ovocné rúrky - MIX",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Ovocné pusinky - čierne ríbezle (100g)",
      "productB": "Ovocné rúrky - MIX",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Polomáčané malinové trubičky s čokoládovou polevou bez palmového tuku 18ks (220g)",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové trubičky s jogurtovou polevou 43ks (540g)",
      "productB": "Ovocné rúrky - MIX",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Ovocné chrumky - marhuľa (100g)",
      "productB": "Ovocné rúrky - MIX",
      "count": 5,
      "pct": 1.74
    },
    {
      "productA": "Jablkové trubičky s čokoládovou polevou bez pridaného cukru 43ks (540g)",
      "productB": "Zľavový kupón číslo VELIKONOCE10 - Zľava 10%",
      "count": 5,
      "pct": 1.74
    }
  ]
};
