// Auto-generated by scripts/updateData.js — last update: 2026-07-27
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = neděle … 6 = sobota
  hour:         number;  // 0–23
  dayCount:     number;  // počet dnů s daným dnem v týdnu v datasetu
  totalRevenue: number;  // celkové tržby bez DPH za (dow, hour)
  totalOrders:  number;  // celkový počet objednávek za (dow, hour)
  avgRevenue:   number;  // průměrné tržby bez DPH / den
  avgOrders:    number;  // průměrný počet objednávek / den
}

export const hourlyDataCZ: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 85,
    "totalRevenue": 12969.33,
    "totalOrders": 15,
    "avgRevenue": 152.58,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 85,
    "totalRevenue": 3425.89,
    "totalOrders": 4,
    "avgRevenue": 40.3,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 85,
    "totalRevenue": 1234.82,
    "totalOrders": 1,
    "avgRevenue": 14.53,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 85,
    "totalRevenue": 4636.61,
    "totalOrders": 4,
    "avgRevenue": 54.55,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 85,
    "totalRevenue": 8698.21,
    "totalOrders": 4,
    "avgRevenue": 102.33,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 85,
    "totalRevenue": 4084.79,
    "totalOrders": 6,
    "avgRevenue": 48.06,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 85,
    "totalRevenue": 9377.43,
    "totalOrders": 13,
    "avgRevenue": 110.32,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 85,
    "totalRevenue": 21455.3,
    "totalOrders": 25,
    "avgRevenue": 252.42,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 85,
    "totalRevenue": 35351.23,
    "totalOrders": 43,
    "avgRevenue": 415.9,
    "avgOrders": 0.51
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 85,
    "totalRevenue": 51572.38,
    "totalOrders": 57,
    "avgRevenue": 606.73,
    "avgOrders": 0.67
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 85,
    "totalRevenue": 49336.79,
    "totalOrders": 60,
    "avgRevenue": 580.43,
    "avgOrders": 0.71
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 85,
    "totalRevenue": 57065.9,
    "totalOrders": 63,
    "avgRevenue": 671.36,
    "avgOrders": 0.74
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 85,
    "totalRevenue": 45716.24,
    "totalOrders": 57,
    "avgRevenue": 537.84,
    "avgOrders": 0.67
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 85,
    "totalRevenue": 53809.84,
    "totalOrders": 65,
    "avgRevenue": 633.06,
    "avgOrders": 0.76
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 85,
    "totalRevenue": 56240.84,
    "totalOrders": 62,
    "avgRevenue": 661.66,
    "avgOrders": 0.73
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 85,
    "totalRevenue": 51239.44,
    "totalOrders": 56,
    "avgRevenue": 602.82,
    "avgOrders": 0.66
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 85,
    "totalRevenue": 61602,
    "totalOrders": 64,
    "avgRevenue": 724.73,
    "avgOrders": 0.75
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 85,
    "totalRevenue": 57326.47,
    "totalOrders": 65,
    "avgRevenue": 674.43,
    "avgOrders": 0.76
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 85,
    "totalRevenue": 60875.52,
    "totalOrders": 69,
    "avgRevenue": 716.18,
    "avgOrders": 0.81
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 85,
    "totalRevenue": 86442.33,
    "totalOrders": 100,
    "avgRevenue": 1016.97,
    "avgOrders": 1.18
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 85,
    "totalRevenue": 86876.41,
    "totalOrders": 95,
    "avgRevenue": 1022.08,
    "avgOrders": 1.12
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 85,
    "totalRevenue": 77849.48,
    "totalOrders": 85,
    "avgRevenue": 915.88,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 85,
    "totalRevenue": 51738.46,
    "totalOrders": 56,
    "avgRevenue": 608.69,
    "avgOrders": 0.66
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 85,
    "totalRevenue": 31252.55,
    "totalOrders": 36,
    "avgRevenue": 367.68,
    "avgOrders": 0.42
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 84,
    "totalRevenue": 13492.29,
    "totalOrders": 13,
    "avgRevenue": 160.62,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 84,
    "totalRevenue": 4261.59,
    "totalOrders": 3,
    "avgRevenue": 50.73,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 84,
    "totalRevenue": 1774.01,
    "totalOrders": 3,
    "avgRevenue": 21.12,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 84,
    "totalRevenue": 913.67,
    "totalOrders": 1,
    "avgRevenue": 10.88,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 84,
    "totalRevenue": 2884.83,
    "totalOrders": 4,
    "avgRevenue": 34.34,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 84,
    "totalRevenue": 7043.92,
    "totalOrders": 10,
    "avgRevenue": 83.86,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 84,
    "totalRevenue": 9614.55,
    "totalOrders": 13,
    "avgRevenue": 114.46,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 84,
    "totalRevenue": 31097.82,
    "totalOrders": 40,
    "avgRevenue": 370.21,
    "avgOrders": 0.48
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 84,
    "totalRevenue": 48821.72,
    "totalOrders": 54,
    "avgRevenue": 581.21,
    "avgOrders": 0.64
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 84,
    "totalRevenue": 76090.03,
    "totalOrders": 73,
    "avgRevenue": 905.83,
    "avgOrders": 0.87
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 84,
    "totalRevenue": 76083.92,
    "totalOrders": 87,
    "avgRevenue": 905.76,
    "avgOrders": 1.04
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 84,
    "totalRevenue": 75918.82,
    "totalOrders": 76,
    "avgRevenue": 903.8,
    "avgOrders": 0.9
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 84,
    "totalRevenue": 64168.62,
    "totalOrders": 71,
    "avgRevenue": 763.91,
    "avgOrders": 0.85
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 84,
    "totalRevenue": 58059.64,
    "totalOrders": 63,
    "avgRevenue": 691.19,
    "avgOrders": 0.75
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 84,
    "totalRevenue": 67760.13,
    "totalOrders": 72,
    "avgRevenue": 806.67,
    "avgOrders": 0.86
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 84,
    "totalRevenue": 58890.92,
    "totalOrders": 67,
    "avgRevenue": 701.08,
    "avgOrders": 0.8
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 84,
    "totalRevenue": 72063.98,
    "totalOrders": 80,
    "avgRevenue": 857.9,
    "avgOrders": 0.95
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 84,
    "totalRevenue": 59875.65,
    "totalOrders": 59,
    "avgRevenue": 712.81,
    "avgOrders": 0.7
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 84,
    "totalRevenue": 53361.21,
    "totalOrders": 62,
    "avgRevenue": 635.25,
    "avgOrders": 0.74
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 84,
    "totalRevenue": 62249.09,
    "totalOrders": 69,
    "avgRevenue": 741.06,
    "avgOrders": 0.82
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 84,
    "totalRevenue": 80434.04,
    "totalOrders": 87,
    "avgRevenue": 957.55,
    "avgOrders": 1.04
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 84,
    "totalRevenue": 102885.43,
    "totalOrders": 123,
    "avgRevenue": 1224.83,
    "avgOrders": 1.46
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 84,
    "totalRevenue": 58376.24,
    "totalOrders": 64,
    "avgRevenue": 694.96,
    "avgOrders": 0.76
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 84,
    "totalRevenue": 24567.38,
    "totalOrders": 30,
    "avgRevenue": 292.47,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 83,
    "totalRevenue": 7865.26,
    "totalOrders": 9,
    "avgRevenue": 94.76,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 83,
    "totalRevenue": 2570.73,
    "totalOrders": 4,
    "avgRevenue": 30.97,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 83,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 83,
    "totalRevenue": 4975.99,
    "totalOrders": 5,
    "avgRevenue": 59.95,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 83,
    "totalRevenue": 5529.44,
    "totalOrders": 6,
    "avgRevenue": 66.62,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 83,
    "totalRevenue": 8426.35,
    "totalOrders": 11,
    "avgRevenue": 101.52,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 83,
    "totalRevenue": 8273.93,
    "totalOrders": 11,
    "avgRevenue": 99.69,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 83,
    "totalRevenue": 41641.9,
    "totalOrders": 41,
    "avgRevenue": 501.71,
    "avgOrders": 0.49
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 83,
    "totalRevenue": 51288.14,
    "totalOrders": 61,
    "avgRevenue": 617.93,
    "avgOrders": 0.73
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 83,
    "totalRevenue": 59301.26,
    "totalOrders": 75,
    "avgRevenue": 714.47,
    "avgOrders": 0.9
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 83,
    "totalRevenue": 92976.9,
    "totalOrders": 95,
    "avgRevenue": 1120.2,
    "avgOrders": 1.14
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 83,
    "totalRevenue": 49015.51,
    "totalOrders": 60,
    "avgRevenue": 590.55,
    "avgOrders": 0.72
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 83,
    "totalRevenue": 61285.78,
    "totalOrders": 71,
    "avgRevenue": 738.38,
    "avgOrders": 0.86
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 83,
    "totalRevenue": 81108.26,
    "totalOrders": 68,
    "avgRevenue": 977.21,
    "avgOrders": 0.82
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 83,
    "totalRevenue": 53684.28,
    "totalOrders": 66,
    "avgRevenue": 646.8,
    "avgOrders": 0.8
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 83,
    "totalRevenue": 40300.14,
    "totalOrders": 49,
    "avgRevenue": 485.54,
    "avgOrders": 0.59
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 83,
    "totalRevenue": 43488.79,
    "totalOrders": 52,
    "avgRevenue": 523.96,
    "avgOrders": 0.63
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 83,
    "totalRevenue": 53700.78,
    "totalOrders": 53,
    "avgRevenue": 647,
    "avgOrders": 0.64
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 83,
    "totalRevenue": 70546.82,
    "totalOrders": 78,
    "avgRevenue": 849.96,
    "avgOrders": 0.94
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 83,
    "totalRevenue": 48923.2,
    "totalOrders": 65,
    "avgRevenue": 589.44,
    "avgOrders": 0.78
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 83,
    "totalRevenue": 90246.31,
    "totalOrders": 103,
    "avgRevenue": 1087.3,
    "avgOrders": 1.24
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 83,
    "totalRevenue": 79282.12,
    "totalOrders": 94,
    "avgRevenue": 955.21,
    "avgOrders": 1.13
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 83,
    "totalRevenue": 47560.99,
    "totalOrders": 49,
    "avgRevenue": 573.02,
    "avgOrders": 0.59
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 83,
    "totalRevenue": 17746.57,
    "totalOrders": 19,
    "avgRevenue": 213.81,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 85,
    "totalRevenue": 9320.54,
    "totalOrders": 8,
    "avgRevenue": 109.65,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 85,
    "totalRevenue": 3778.75,
    "totalOrders": 5,
    "avgRevenue": 44.46,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 85,
    "totalRevenue": 3527.93,
    "totalOrders": 4,
    "avgRevenue": 41.51,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 85,
    "totalRevenue": 1140.08,
    "totalOrders": 3,
    "avgRevenue": 13.41,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 85,
    "totalRevenue": 1832.15,
    "totalOrders": 3,
    "avgRevenue": 21.55,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 85,
    "totalRevenue": 7750.51,
    "totalOrders": 11,
    "avgRevenue": 91.18,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 85,
    "totalRevenue": 15021.56,
    "totalOrders": 18,
    "avgRevenue": 176.72,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 85,
    "totalRevenue": 51424.16,
    "totalOrders": 37,
    "avgRevenue": 604.99,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 85,
    "totalRevenue": 62474.94,
    "totalOrders": 74,
    "avgRevenue": 735,
    "avgOrders": 0.87
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 85,
    "totalRevenue": 54982.07,
    "totalOrders": 63,
    "avgRevenue": 646.85,
    "avgOrders": 0.74
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 85,
    "totalRevenue": 71027.64,
    "totalOrders": 81,
    "avgRevenue": 835.62,
    "avgOrders": 0.95
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 85,
    "totalRevenue": 66007.61,
    "totalOrders": 69,
    "avgRevenue": 776.56,
    "avgOrders": 0.81
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 85,
    "totalRevenue": 72393.03,
    "totalOrders": 76,
    "avgRevenue": 851.68,
    "avgOrders": 0.89
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 85,
    "totalRevenue": 74296.97,
    "totalOrders": 85,
    "avgRevenue": 874.08,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 85,
    "totalRevenue": 67322.87,
    "totalOrders": 72,
    "avgRevenue": 792.03,
    "avgOrders": 0.85
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 85,
    "totalRevenue": 47418.78,
    "totalOrders": 49,
    "avgRevenue": 557.87,
    "avgOrders": 0.58
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 85,
    "totalRevenue": 39207.78,
    "totalOrders": 49,
    "avgRevenue": 461.27,
    "avgOrders": 0.58
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 85,
    "totalRevenue": 55797.4,
    "totalOrders": 66,
    "avgRevenue": 656.44,
    "avgOrders": 0.78
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 85,
    "totalRevenue": 52693.09,
    "totalOrders": 64,
    "avgRevenue": 619.92,
    "avgOrders": 0.75
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 85,
    "totalRevenue": 58587.5,
    "totalOrders": 70,
    "avgRevenue": 689.26,
    "avgOrders": 0.82
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 85,
    "totalRevenue": 82926.17,
    "totalOrders": 88,
    "avgRevenue": 975.6,
    "avgOrders": 1.04
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 85,
    "totalRevenue": 72832.18,
    "totalOrders": 85,
    "avgRevenue": 856.85,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 85,
    "totalRevenue": 29813.46,
    "totalOrders": 39,
    "avgRevenue": 350.75,
    "avgOrders": 0.46
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 85,
    "totalRevenue": 28128.7,
    "totalOrders": 32,
    "avgRevenue": 330.93,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 86,
    "totalRevenue": 3168.17,
    "totalOrders": 7,
    "avgRevenue": 36.84,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 86,
    "totalRevenue": 4764.65,
    "totalOrders": 5,
    "avgRevenue": 55.4,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 86,
    "totalRevenue": 4511.6,
    "totalOrders": 6,
    "avgRevenue": 52.46,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 86,
    "totalRevenue": 1026.8,
    "totalOrders": 2,
    "avgRevenue": 11.94,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 86,
    "totalRevenue": 2505.64,
    "totalOrders": 3,
    "avgRevenue": 29.14,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 86,
    "totalRevenue": 16148.94,
    "totalOrders": 15,
    "avgRevenue": 187.78,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 86,
    "totalRevenue": 23749.06,
    "totalOrders": 21,
    "avgRevenue": 276.15,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 86,
    "totalRevenue": 27805.74,
    "totalOrders": 32,
    "avgRevenue": 323.32,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 86,
    "totalRevenue": 46647.64,
    "totalOrders": 48,
    "avgRevenue": 542.41,
    "avgOrders": 0.56
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 86,
    "totalRevenue": 74060.51,
    "totalOrders": 81,
    "avgRevenue": 861.17,
    "avgOrders": 0.94
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 86,
    "totalRevenue": 55963.25,
    "totalOrders": 59,
    "avgRevenue": 650.74,
    "avgOrders": 0.69
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 86,
    "totalRevenue": 61819.43,
    "totalOrders": 55,
    "avgRevenue": 718.83,
    "avgOrders": 0.64
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 86,
    "totalRevenue": 55516,
    "totalOrders": 63,
    "avgRevenue": 645.53,
    "avgOrders": 0.73
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 86,
    "totalRevenue": 65165.41,
    "totalOrders": 64,
    "avgRevenue": 757.74,
    "avgOrders": 0.74
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 86,
    "totalRevenue": 50451.21,
    "totalOrders": 56,
    "avgRevenue": 586.64,
    "avgOrders": 0.65
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 86,
    "totalRevenue": 36719.03,
    "totalOrders": 40,
    "avgRevenue": 426.97,
    "avgOrders": 0.47
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 86,
    "totalRevenue": 45009.94,
    "totalOrders": 50,
    "avgRevenue": 523.37,
    "avgOrders": 0.58
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 86,
    "totalRevenue": 48705.75,
    "totalOrders": 59,
    "avgRevenue": 566.35,
    "avgOrders": 0.69
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 86,
    "totalRevenue": 46180.21,
    "totalOrders": 59,
    "avgRevenue": 536.98,
    "avgOrders": 0.69
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 86,
    "totalRevenue": 42423.42,
    "totalOrders": 58,
    "avgRevenue": 493.3,
    "avgOrders": 0.67
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 86,
    "totalRevenue": 54847.11,
    "totalOrders": 61,
    "avgRevenue": 637.76,
    "avgOrders": 0.71
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 86,
    "totalRevenue": 55085.6,
    "totalOrders": 71,
    "avgRevenue": 640.53,
    "avgOrders": 0.83
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 86,
    "totalRevenue": 43323.8,
    "totalOrders": 46,
    "avgRevenue": 503.77,
    "avgOrders": 0.53
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 86,
    "totalRevenue": 29959.45,
    "totalOrders": 22,
    "avgRevenue": 348.37,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 85,
    "totalRevenue": 7683.09,
    "totalOrders": 10,
    "avgRevenue": 90.39,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 85,
    "totalRevenue": 4249.28,
    "totalOrders": 4,
    "avgRevenue": 49.99,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 85,
    "totalRevenue": 6035.88,
    "totalOrders": 6,
    "avgRevenue": 71.01,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 85,
    "totalRevenue": 8604.63,
    "totalOrders": 4,
    "avgRevenue": 101.23,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 85,
    "totalRevenue": 5558.3,
    "totalOrders": 6,
    "avgRevenue": 65.39,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 85,
    "totalRevenue": 4954.13,
    "totalOrders": 8,
    "avgRevenue": 58.28,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 85,
    "totalRevenue": 16547.51,
    "totalOrders": 23,
    "avgRevenue": 194.68,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 85,
    "totalRevenue": 36578.87,
    "totalOrders": 37,
    "avgRevenue": 430.34,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 85,
    "totalRevenue": 51070.32,
    "totalOrders": 66,
    "avgRevenue": 600.83,
    "avgOrders": 0.78
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 85,
    "totalRevenue": 40613.93,
    "totalOrders": 53,
    "avgRevenue": 477.81,
    "avgOrders": 0.62
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 85,
    "totalRevenue": 52159.69,
    "totalOrders": 59,
    "avgRevenue": 613.64,
    "avgOrders": 0.69
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 85,
    "totalRevenue": 52081.8,
    "totalOrders": 55,
    "avgRevenue": 612.73,
    "avgOrders": 0.65
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 85,
    "totalRevenue": 52828.62,
    "totalOrders": 59,
    "avgRevenue": 621.51,
    "avgOrders": 0.69
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 85,
    "totalRevenue": 55317.73,
    "totalOrders": 56,
    "avgRevenue": 650.8,
    "avgOrders": 0.66
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 85,
    "totalRevenue": 43704.52,
    "totalOrders": 54,
    "avgRevenue": 514.17,
    "avgOrders": 0.64
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 85,
    "totalRevenue": 46258.98,
    "totalOrders": 50,
    "avgRevenue": 544.22,
    "avgOrders": 0.59
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 85,
    "totalRevenue": 34870.74,
    "totalOrders": 46,
    "avgRevenue": 410.24,
    "avgOrders": 0.54
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 85,
    "totalRevenue": 38652.23,
    "totalOrders": 43,
    "avgRevenue": 454.73,
    "avgOrders": 0.51
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 85,
    "totalRevenue": 33233.33,
    "totalOrders": 37,
    "avgRevenue": 390.98,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 85,
    "totalRevenue": 52992.56,
    "totalOrders": 68,
    "avgRevenue": 623.44,
    "avgOrders": 0.8
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 85,
    "totalRevenue": 53277.41,
    "totalOrders": 64,
    "avgRevenue": 626.79,
    "avgOrders": 0.75
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 85,
    "totalRevenue": 59853.46,
    "totalOrders": 67,
    "avgRevenue": 704.16,
    "avgOrders": 0.79
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 85,
    "totalRevenue": 27932.11,
    "totalOrders": 37,
    "avgRevenue": 328.61,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 85,
    "totalRevenue": 22851.5,
    "totalOrders": 25,
    "avgRevenue": 268.84,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 85,
    "totalRevenue": 6269.5,
    "totalOrders": 7,
    "avgRevenue": 73.76,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 85,
    "totalRevenue": 3787.87,
    "totalOrders": 5,
    "avgRevenue": 44.56,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 85,
    "totalRevenue": 562.68,
    "totalOrders": 2,
    "avgRevenue": 6.62,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 85,
    "totalRevenue": 1875.89,
    "totalOrders": 3,
    "avgRevenue": 22.07,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 85,
    "totalRevenue": 1597.32,
    "totalOrders": 3,
    "avgRevenue": 18.79,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 85,
    "totalRevenue": 4497.7,
    "totalOrders": 5,
    "avgRevenue": 52.91,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 85,
    "totalRevenue": 16603.54,
    "totalOrders": 17,
    "avgRevenue": 195.34,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 85,
    "totalRevenue": 27869.74,
    "totalOrders": 36,
    "avgRevenue": 327.88,
    "avgOrders": 0.42
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 85,
    "totalRevenue": 35177.07,
    "totalOrders": 40,
    "avgRevenue": 413.85,
    "avgOrders": 0.47
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 85,
    "totalRevenue": 42370.05,
    "totalOrders": 52,
    "avgRevenue": 498.47,
    "avgOrders": 0.61
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 85,
    "totalRevenue": 57939.67,
    "totalOrders": 59,
    "avgRevenue": 681.64,
    "avgOrders": 0.69
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 85,
    "totalRevenue": 51676.33,
    "totalOrders": 51,
    "avgRevenue": 607.96,
    "avgOrders": 0.6
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 85,
    "totalRevenue": 42872.5,
    "totalOrders": 45,
    "avgRevenue": 504.38,
    "avgOrders": 0.53
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 85,
    "totalRevenue": 66564.55,
    "totalOrders": 71,
    "avgRevenue": 783.11,
    "avgOrders": 0.84
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 85,
    "totalRevenue": 41508.71,
    "totalOrders": 44,
    "avgRevenue": 488.34,
    "avgOrders": 0.52
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 85,
    "totalRevenue": 41075.4,
    "totalOrders": 48,
    "avgRevenue": 483.24,
    "avgOrders": 0.56
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 85,
    "totalRevenue": 39657.28,
    "totalOrders": 47,
    "avgRevenue": 466.56,
    "avgOrders": 0.55
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 85,
    "totalRevenue": 51610.59,
    "totalOrders": 53,
    "avgRevenue": 607.18,
    "avgOrders": 0.62
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 85,
    "totalRevenue": 43383.87,
    "totalOrders": 45,
    "avgRevenue": 510.4,
    "avgOrders": 0.53
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 85,
    "totalRevenue": 50364.47,
    "totalOrders": 60,
    "avgRevenue": 592.52,
    "avgOrders": 0.71
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 85,
    "totalRevenue": 36480.03,
    "totalOrders": 48,
    "avgRevenue": 429.18,
    "avgOrders": 0.56
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 85,
    "totalRevenue": 47939.48,
    "totalOrders": 51,
    "avgRevenue": 563.99,
    "avgOrders": 0.6
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 85,
    "totalRevenue": 21626.16,
    "totalOrders": 27,
    "avgRevenue": 254.43,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 85,
    "totalRevenue": 11916.27,
    "totalOrders": 13,
    "avgRevenue": 140.19,
    "avgOrders": 0.15
  }
];
