// Auto-generated by scripts/updateData.js — last update: 2026-07-03
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = neděle … 6 = sobota
  hour:         number;  // 0–23
  dayCount:     number;  // počet dnů s daným dnem v týdnu v datasetu
  totalRevenue: number;  // celkové tržby bez DPH za (dow, hour)
  totalOrders:  number;  // celkový počet objednávek za (dow, hour)
  avgRevenue:   number;  // průměrné tržby bez DPH / den
  avgOrders:    number;  // průměrný počet objednávek / den
}

export const hourlyDataCZ: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 81,
    "totalRevenue": 12419.33,
    "totalOrders": 13,
    "avgRevenue": 153.33,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 81,
    "totalRevenue": 3425.89,
    "totalOrders": 4,
    "avgRevenue": 42.29,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 81,
    "totalRevenue": 1234.82,
    "totalOrders": 1,
    "avgRevenue": 15.24,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 81,
    "totalRevenue": 4636.61,
    "totalOrders": 4,
    "avgRevenue": 57.24,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 81,
    "totalRevenue": 8698.21,
    "totalOrders": 4,
    "avgRevenue": 107.39,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 81,
    "totalRevenue": 4084.79,
    "totalOrders": 6,
    "avgRevenue": 50.43,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 81,
    "totalRevenue": 9377.43,
    "totalOrders": 13,
    "avgRevenue": 115.77,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 81,
    "totalRevenue": 21455.3,
    "totalOrders": 25,
    "avgRevenue": 264.88,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 81,
    "totalRevenue": 35351.23,
    "totalOrders": 43,
    "avgRevenue": 436.43,
    "avgOrders": 0.53
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 81,
    "totalRevenue": 48418.98,
    "totalOrders": 55,
    "avgRevenue": 597.77,
    "avgOrders": 0.68
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 81,
    "totalRevenue": 45847.5,
    "totalOrders": 57,
    "avgRevenue": 566.02,
    "avgOrders": 0.7
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 81,
    "totalRevenue": 57065.9,
    "totalOrders": 63,
    "avgRevenue": 704.52,
    "avgOrders": 0.78
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 81,
    "totalRevenue": 43579.36,
    "totalOrders": 56,
    "avgRevenue": 538.02,
    "avgOrders": 0.69
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 81,
    "totalRevenue": 53809.84,
    "totalOrders": 65,
    "avgRevenue": 664.32,
    "avgOrders": 0.8
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 81,
    "totalRevenue": 55253.34,
    "totalOrders": 61,
    "avgRevenue": 682.14,
    "avgOrders": 0.75
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 81,
    "totalRevenue": 50030.52,
    "totalOrders": 55,
    "avgRevenue": 617.66,
    "avgOrders": 0.68
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 81,
    "totalRevenue": 60491.83,
    "totalOrders": 62,
    "avgRevenue": 746.81,
    "avgOrders": 0.77
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 81,
    "totalRevenue": 54153.27,
    "totalOrders": 62,
    "avgRevenue": 668.56,
    "avgOrders": 0.77
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 81,
    "totalRevenue": 60198.74,
    "totalOrders": 68,
    "avgRevenue": 743.19,
    "avgOrders": 0.84
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 81,
    "totalRevenue": 85318.28,
    "totalOrders": 98,
    "avgRevenue": 1053.31,
    "avgOrders": 1.21
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 81,
    "totalRevenue": 82168.37,
    "totalOrders": 90,
    "avgRevenue": 1014.42,
    "avgOrders": 1.11
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 81,
    "totalRevenue": 77849.48,
    "totalOrders": 85,
    "avgRevenue": 961.1,
    "avgOrders": 1.05
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 81,
    "totalRevenue": 50377.21,
    "totalOrders": 55,
    "avgRevenue": 621.94,
    "avgOrders": 0.68
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 81,
    "totalRevenue": 31252.55,
    "totalOrders": 36,
    "avgRevenue": 385.83,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 81,
    "totalRevenue": 13225.33,
    "totalOrders": 12,
    "avgRevenue": 163.28,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 81,
    "totalRevenue": 4261.59,
    "totalOrders": 3,
    "avgRevenue": 52.61,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 81,
    "totalRevenue": 1774.01,
    "totalOrders": 3,
    "avgRevenue": 21.9,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 81,
    "totalRevenue": 913.67,
    "totalOrders": 1,
    "avgRevenue": 11.28,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 81,
    "totalRevenue": 2884.83,
    "totalOrders": 4,
    "avgRevenue": 35.62,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 81,
    "totalRevenue": 7043.92,
    "totalOrders": 10,
    "avgRevenue": 86.96,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 81,
    "totalRevenue": 9614.55,
    "totalOrders": 13,
    "avgRevenue": 118.7,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 81,
    "totalRevenue": 31097.82,
    "totalOrders": 40,
    "avgRevenue": 383.92,
    "avgOrders": 0.49
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 81,
    "totalRevenue": 46841.36,
    "totalOrders": 53,
    "avgRevenue": 578.29,
    "avgOrders": 0.65
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 81,
    "totalRevenue": 76090.03,
    "totalOrders": 73,
    "avgRevenue": 939.38,
    "avgOrders": 0.9
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 81,
    "totalRevenue": 74971.19,
    "totalOrders": 86,
    "avgRevenue": 925.57,
    "avgOrders": 1.06
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 81,
    "totalRevenue": 75918.82,
    "totalOrders": 76,
    "avgRevenue": 937.27,
    "avgOrders": 0.94
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 81,
    "totalRevenue": 64168.62,
    "totalOrders": 71,
    "avgRevenue": 792.21,
    "avgOrders": 0.88
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 81,
    "totalRevenue": 53714.97,
    "totalOrders": 59,
    "avgRevenue": 663.15,
    "avgOrders": 0.73
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 81,
    "totalRevenue": 67493.17,
    "totalOrders": 71,
    "avgRevenue": 833.25,
    "avgOrders": 0.88
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 81,
    "totalRevenue": 54185.61,
    "totalOrders": 66,
    "avgRevenue": 668.96,
    "avgOrders": 0.81
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 81,
    "totalRevenue": 70568.44,
    "totalOrders": 78,
    "avgRevenue": 871.22,
    "avgOrders": 0.96
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 81,
    "totalRevenue": 57102.52,
    "totalOrders": 58,
    "avgRevenue": 704.97,
    "avgOrders": 0.72
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 81,
    "totalRevenue": 53361.21,
    "totalOrders": 62,
    "avgRevenue": 658.78,
    "avgOrders": 0.77
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 81,
    "totalRevenue": 60022.3,
    "totalOrders": 68,
    "avgRevenue": 741.02,
    "avgOrders": 0.84
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 81,
    "totalRevenue": 73921.56,
    "totalOrders": 86,
    "avgRevenue": 912.61,
    "avgOrders": 1.06
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 81,
    "totalRevenue": 101484.36,
    "totalOrders": 120,
    "avgRevenue": 1252.89,
    "avgOrders": 1.48
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 81,
    "totalRevenue": 58376.24,
    "totalOrders": 64,
    "avgRevenue": 720.69,
    "avgOrders": 0.79
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 81,
    "totalRevenue": 22595.96,
    "totalOrders": 28,
    "avgRevenue": 278.96,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 80,
    "totalRevenue": 6452.76,
    "totalOrders": 8,
    "avgRevenue": 80.66,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 80,
    "totalRevenue": 2570.73,
    "totalOrders": 4,
    "avgRevenue": 32.13,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 80,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 80,
    "totalRevenue": 4975.99,
    "totalOrders": 5,
    "avgRevenue": 62.2,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 80,
    "totalRevenue": 5529.44,
    "totalOrders": 6,
    "avgRevenue": 69.12,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 80,
    "totalRevenue": 8426.35,
    "totalOrders": 11,
    "avgRevenue": 105.33,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 80,
    "totalRevenue": 7917.68,
    "totalOrders": 10,
    "avgRevenue": 98.97,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 80,
    "totalRevenue": 41641.9,
    "totalOrders": 41,
    "avgRevenue": 520.52,
    "avgOrders": 0.51
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 80,
    "totalRevenue": 50553.32,
    "totalOrders": 60,
    "avgRevenue": 631.92,
    "avgOrders": 0.75
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 80,
    "totalRevenue": 58638.77,
    "totalOrders": 74,
    "avgRevenue": 732.98,
    "avgOrders": 0.93
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 80,
    "totalRevenue": 88662.61,
    "totalOrders": 91,
    "avgRevenue": 1108.28,
    "avgOrders": 1.14
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 80,
    "totalRevenue": 45586.04,
    "totalOrders": 57,
    "avgRevenue": 569.83,
    "avgOrders": 0.71
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 80,
    "totalRevenue": 59825.96,
    "totalOrders": 69,
    "avgRevenue": 747.82,
    "avgOrders": 0.86
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 80,
    "totalRevenue": 81108.26,
    "totalOrders": 68,
    "avgRevenue": 1013.85,
    "avgOrders": 0.85
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 80,
    "totalRevenue": 53684.28,
    "totalOrders": 66,
    "avgRevenue": 671.05,
    "avgOrders": 0.83
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 80,
    "totalRevenue": 39967.1,
    "totalOrders": 48,
    "avgRevenue": 499.59,
    "avgOrders": 0.6
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 80,
    "totalRevenue": 43488.79,
    "totalOrders": 52,
    "avgRevenue": 543.61,
    "avgOrders": 0.65
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 80,
    "totalRevenue": 52808.85,
    "totalOrders": 51,
    "avgRevenue": 660.11,
    "avgOrders": 0.64
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 80,
    "totalRevenue": 70546.82,
    "totalOrders": 78,
    "avgRevenue": 881.84,
    "avgOrders": 0.98
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 80,
    "totalRevenue": 48530.34,
    "totalOrders": 64,
    "avgRevenue": 606.63,
    "avgOrders": 0.8
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 80,
    "totalRevenue": 88358.81,
    "totalOrders": 102,
    "avgRevenue": 1104.49,
    "avgOrders": 1.27
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 80,
    "totalRevenue": 77118.38,
    "totalOrders": 91,
    "avgRevenue": 963.98,
    "avgOrders": 1.14
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 80,
    "totalRevenue": 47560.99,
    "totalOrders": 49,
    "avgRevenue": 594.51,
    "avgOrders": 0.61
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 80,
    "totalRevenue": 16476.03,
    "totalOrders": 18,
    "avgRevenue": 205.95,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 82,
    "totalRevenue": 9320.54,
    "totalOrders": 8,
    "avgRevenue": 113.67,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 82,
    "totalRevenue": 3778.75,
    "totalOrders": 5,
    "avgRevenue": 46.08,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 82,
    "totalRevenue": 3527.93,
    "totalOrders": 4,
    "avgRevenue": 43.02,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 82,
    "totalRevenue": 1140.08,
    "totalOrders": 3,
    "avgRevenue": 13.9,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 82,
    "totalRevenue": 1832.15,
    "totalOrders": 3,
    "avgRevenue": 22.34,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 82,
    "totalRevenue": 7750.51,
    "totalOrders": 11,
    "avgRevenue": 94.52,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 82,
    "totalRevenue": 15021.56,
    "totalOrders": 18,
    "avgRevenue": 183.19,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 82,
    "totalRevenue": 51424.16,
    "totalOrders": 37,
    "avgRevenue": 627.12,
    "avgOrders": 0.45
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 82,
    "totalRevenue": 61388.33,
    "totalOrders": 73,
    "avgRevenue": 748.64,
    "avgOrders": 0.89
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 82,
    "totalRevenue": 54982.07,
    "totalOrders": 63,
    "avgRevenue": 670.51,
    "avgOrders": 0.77
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 82,
    "totalRevenue": 69761.21,
    "totalOrders": 80,
    "avgRevenue": 850.75,
    "avgOrders": 0.98
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 82,
    "totalRevenue": 60422.78,
    "totalOrders": 67,
    "avgRevenue": 736.86,
    "avgOrders": 0.82
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 82,
    "totalRevenue": 70897.49,
    "totalOrders": 75,
    "avgRevenue": 864.6,
    "avgOrders": 0.91
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 82,
    "totalRevenue": 74296.97,
    "totalOrders": 85,
    "avgRevenue": 906.06,
    "avgOrders": 1.04
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 82,
    "totalRevenue": 66324.66,
    "totalOrders": 71,
    "avgRevenue": 808.84,
    "avgOrders": 0.87
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 82,
    "totalRevenue": 47418.78,
    "totalOrders": 49,
    "avgRevenue": 578.28,
    "avgOrders": 0.6
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 82,
    "totalRevenue": 37555.11,
    "totalOrders": 47,
    "avgRevenue": 457.99,
    "avgOrders": 0.57
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 82,
    "totalRevenue": 55797.4,
    "totalOrders": 66,
    "avgRevenue": 680.46,
    "avgOrders": 0.8
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 82,
    "totalRevenue": 51322.55,
    "totalOrders": 63,
    "avgRevenue": 625.88,
    "avgOrders": 0.77
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 82,
    "totalRevenue": 56247.31,
    "totalOrders": 68,
    "avgRevenue": 685.94,
    "avgOrders": 0.83
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 82,
    "totalRevenue": 82926.17,
    "totalOrders": 88,
    "avgRevenue": 1011.29,
    "avgOrders": 1.07
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 82,
    "totalRevenue": 70433.08,
    "totalOrders": 82,
    "avgRevenue": 858.94,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 82,
    "totalRevenue": 29813.46,
    "totalOrders": 39,
    "avgRevenue": 363.58,
    "avgOrders": 0.48
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 82,
    "totalRevenue": 27505.49,
    "totalOrders": 31,
    "avgRevenue": 335.43,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 83,
    "totalRevenue": 2901.21,
    "totalOrders": 6,
    "avgRevenue": 34.95,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 83,
    "totalRevenue": 4764.65,
    "totalOrders": 5,
    "avgRevenue": 57.41,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 83,
    "totalRevenue": 4511.6,
    "totalOrders": 6,
    "avgRevenue": 54.36,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 83,
    "totalRevenue": 1026.8,
    "totalOrders": 2,
    "avgRevenue": 12.37,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 83,
    "totalRevenue": 2505.64,
    "totalOrders": 3,
    "avgRevenue": 30.19,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 83,
    "totalRevenue": 15053.39,
    "totalOrders": 14,
    "avgRevenue": 181.37,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 83,
    "totalRevenue": 23749.06,
    "totalOrders": 21,
    "avgRevenue": 286.13,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 83,
    "totalRevenue": 27805.74,
    "totalOrders": 32,
    "avgRevenue": 335.01,
    "avgOrders": 0.39
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 83,
    "totalRevenue": 46647.64,
    "totalOrders": 48,
    "avgRevenue": 562.02,
    "avgOrders": 0.58
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 83,
    "totalRevenue": 73487.29,
    "totalOrders": 80,
    "avgRevenue": 885.39,
    "avgOrders": 0.96
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 83,
    "totalRevenue": 54130.21,
    "totalOrders": 57,
    "avgRevenue": 652.17,
    "avgOrders": 0.69
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 83,
    "totalRevenue": 61819.43,
    "totalOrders": 55,
    "avgRevenue": 744.81,
    "avgOrders": 0.66
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 83,
    "totalRevenue": 53099.05,
    "totalOrders": 61,
    "avgRevenue": 639.75,
    "avgOrders": 0.73
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 83,
    "totalRevenue": 65165.41,
    "totalOrders": 64,
    "avgRevenue": 785.13,
    "avgOrders": 0.77
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 83,
    "totalRevenue": 49343.08,
    "totalOrders": 55,
    "avgRevenue": 594.49,
    "avgOrders": 0.66
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 83,
    "totalRevenue": 36719.03,
    "totalOrders": 40,
    "avgRevenue": 442.4,
    "avgOrders": 0.48
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 83,
    "totalRevenue": 44384.94,
    "totalOrders": 49,
    "avgRevenue": 534.76,
    "avgOrders": 0.59
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 83,
    "totalRevenue": 47628.07,
    "totalOrders": 58,
    "avgRevenue": 573.83,
    "avgOrders": 0.7
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 83,
    "totalRevenue": 45823.96,
    "totalOrders": 58,
    "avgRevenue": 552.1,
    "avgOrders": 0.7
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 83,
    "totalRevenue": 41769.84,
    "totalOrders": 57,
    "avgRevenue": 503.25,
    "avgOrders": 0.69
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 83,
    "totalRevenue": 54847.11,
    "totalOrders": 61,
    "avgRevenue": 660.81,
    "avgOrders": 0.73
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 83,
    "totalRevenue": 55085.6,
    "totalOrders": 71,
    "avgRevenue": 663.68,
    "avgOrders": 0.86
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 83,
    "totalRevenue": 42119.33,
    "totalOrders": 45,
    "avgRevenue": 507.46,
    "avgOrders": 0.54
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 83,
    "totalRevenue": 29959.45,
    "totalOrders": 22,
    "avgRevenue": 360.96,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 81,
    "totalRevenue": 7683.09,
    "totalOrders": 10,
    "avgRevenue": 94.85,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 81,
    "totalRevenue": 4249.28,
    "totalOrders": 4,
    "avgRevenue": 52.46,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 81,
    "totalRevenue": 6035.88,
    "totalOrders": 6,
    "avgRevenue": 74.52,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 81,
    "totalRevenue": 8604.63,
    "totalOrders": 4,
    "avgRevenue": 106.23,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 81,
    "totalRevenue": 5558.3,
    "totalOrders": 6,
    "avgRevenue": 68.62,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 81,
    "totalRevenue": 4954.13,
    "totalOrders": 8,
    "avgRevenue": 61.16,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 81,
    "totalRevenue": 16547.51,
    "totalOrders": 23,
    "avgRevenue": 204.29,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 81,
    "totalRevenue": 36578.87,
    "totalOrders": 37,
    "avgRevenue": 451.59,
    "avgOrders": 0.46
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 81,
    "totalRevenue": 51070.32,
    "totalOrders": 66,
    "avgRevenue": 630.5,
    "avgOrders": 0.81
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 81,
    "totalRevenue": 39527.32,
    "totalOrders": 52,
    "avgRevenue": 487.99,
    "avgOrders": 0.64
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 81,
    "totalRevenue": 51179.33,
    "totalOrders": 58,
    "avgRevenue": 631.84,
    "avgOrders": 0.72
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 81,
    "totalRevenue": 51838.92,
    "totalOrders": 54,
    "avgRevenue": 639.99,
    "avgOrders": 0.67
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 81,
    "totalRevenue": 51092.91,
    "totalOrders": 57,
    "avgRevenue": 630.78,
    "avgOrders": 0.7
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 81,
    "totalRevenue": 54632.02,
    "totalOrders": 55,
    "avgRevenue": 674.47,
    "avgOrders": 0.68
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 81,
    "totalRevenue": 41708.98,
    "totalOrders": 51,
    "avgRevenue": 514.93,
    "avgOrders": 0.63
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 81,
    "totalRevenue": 46107.19,
    "totalOrders": 49,
    "avgRevenue": 569.22,
    "avgOrders": 0.6
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 81,
    "totalRevenue": 34111.8,
    "totalOrders": 45,
    "avgRevenue": 421.13,
    "avgOrders": 0.56
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 81,
    "totalRevenue": 32752.23,
    "totalOrders": 40,
    "avgRevenue": 404.35,
    "avgOrders": 0.49
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 81,
    "totalRevenue": 33233.33,
    "totalOrders": 37,
    "avgRevenue": 410.29,
    "avgOrders": 0.46
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 81,
    "totalRevenue": 52306.85,
    "totalOrders": 67,
    "avgRevenue": 645.76,
    "avgOrders": 0.83
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 81,
    "totalRevenue": 53277.41,
    "totalOrders": 64,
    "avgRevenue": 657.75,
    "avgOrders": 0.79
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 81,
    "totalRevenue": 57740.07,
    "totalOrders": 65,
    "avgRevenue": 712.84,
    "avgOrders": 0.8
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 81,
    "totalRevenue": 26177.73,
    "totalOrders": 35,
    "avgRevenue": 323.18,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 81,
    "totalRevenue": 21420.28,
    "totalOrders": 23,
    "avgRevenue": 264.45,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 81,
    "totalRevenue": 6269.5,
    "totalOrders": 7,
    "avgRevenue": 77.4,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 81,
    "totalRevenue": 3787.87,
    "totalOrders": 5,
    "avgRevenue": 46.76,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 81,
    "totalRevenue": 562.68,
    "totalOrders": 2,
    "avgRevenue": 6.95,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 81,
    "totalRevenue": 1875.89,
    "totalOrders": 3,
    "avgRevenue": 23.16,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 81,
    "totalRevenue": 1597.32,
    "totalOrders": 3,
    "avgRevenue": 19.72,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 81,
    "totalRevenue": 3865.56,
    "totalOrders": 4,
    "avgRevenue": 47.72,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 81,
    "totalRevenue": 16603.54,
    "totalOrders": 17,
    "avgRevenue": 204.98,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 81,
    "totalRevenue": 26551.88,
    "totalOrders": 35,
    "avgRevenue": 327.8,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 81,
    "totalRevenue": 34669.93,
    "totalOrders": 39,
    "avgRevenue": 428.02,
    "avgOrders": 0.48
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 81,
    "totalRevenue": 39993.22,
    "totalOrders": 50,
    "avgRevenue": 493.74,
    "avgOrders": 0.62
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 81,
    "totalRevenue": 57939.67,
    "totalOrders": 59,
    "avgRevenue": 715.3,
    "avgOrders": 0.73
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 81,
    "totalRevenue": 48984.36,
    "totalOrders": 50,
    "avgRevenue": 604.75,
    "avgOrders": 0.62
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 81,
    "totalRevenue": 40496.61,
    "totalOrders": 44,
    "avgRevenue": 499.96,
    "avgOrders": 0.54
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 81,
    "totalRevenue": 66564.55,
    "totalOrders": 71,
    "avgRevenue": 821.78,
    "avgOrders": 0.88
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 81,
    "totalRevenue": 39415.86,
    "totalOrders": 42,
    "avgRevenue": 486.62,
    "avgOrders": 0.52
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 81,
    "totalRevenue": 41075.4,
    "totalOrders": 48,
    "avgRevenue": 507.1,
    "avgOrders": 0.59
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 81,
    "totalRevenue": 39657.28,
    "totalOrders": 47,
    "avgRevenue": 489.6,
    "avgOrders": 0.58
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 81,
    "totalRevenue": 51610.59,
    "totalOrders": 53,
    "avgRevenue": 637.17,
    "avgOrders": 0.65
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 81,
    "totalRevenue": 42758.87,
    "totalOrders": 44,
    "avgRevenue": 527.89,
    "avgOrders": 0.54
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 81,
    "totalRevenue": 49225.19,
    "totalOrders": 58,
    "avgRevenue": 607.72,
    "avgOrders": 0.72
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 81,
    "totalRevenue": 36480.03,
    "totalOrders": 48,
    "avgRevenue": 450.37,
    "avgOrders": 0.59
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 81,
    "totalRevenue": 43995.72,
    "totalOrders": 48,
    "avgRevenue": 543.16,
    "avgOrders": 0.59
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 81,
    "totalRevenue": 20487.77,
    "totalOrders": 26,
    "avgRevenue": 252.94,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 81,
    "totalRevenue": 11916.27,
    "totalOrders": 13,
    "avgRevenue": 147.11,
    "avgOrders": 0.16
  }
];
