// Auto-generated by scripts/updateData.js — last update: 2026-09-15
// SK: hourly purchase behaviour (EUR), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = neděle … 6 = sobota
  hour:         number;  // 0–23
  dayCount:     number;  // počet dnů s daným dnem v týdnu v datasetu
  totalRevenue: number;  // celkové tržby bez DPH za (dow, hour)
  totalOrders:  number;  // celkový počet objednávek za (dow, hour)
  avgRevenue:   number;  // průměrné tržby bez DPH / den
  avgOrders:    number;  // průměrný počet objednávek / den
}

export const hourlyDataSK: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 29,
    "totalRevenue": 39.23,
    "totalOrders": 1,
    "avgRevenue": 1.35,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 29,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 29,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 29,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 29,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 29,
    "totalRevenue": 47.94,
    "totalOrders": 1,
    "avgRevenue": 1.65,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 29,
    "totalRevenue": 158.09,
    "totalOrders": 2,
    "avgRevenue": 5.45,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 29,
    "totalRevenue": 92.43,
    "totalOrders": 3,
    "avgRevenue": 3.19,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 29,
    "totalRevenue": 104.25,
    "totalOrders": 3,
    "avgRevenue": 3.59,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 29,
    "totalRevenue": 247.03,
    "totalOrders": 6,
    "avgRevenue": 8.52,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 29,
    "totalRevenue": 393.33,
    "totalOrders": 7,
    "avgRevenue": 13.56,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 29,
    "totalRevenue": 16.49,
    "totalOrders": 1,
    "avgRevenue": 0.57,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 29,
    "totalRevenue": 199.41,
    "totalOrders": 6,
    "avgRevenue": 6.88,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 29,
    "totalRevenue": 258.68,
    "totalOrders": 5,
    "avgRevenue": 8.92,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 29,
    "totalRevenue": 243.29,
    "totalOrders": 5,
    "avgRevenue": 8.39,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 29,
    "totalRevenue": 196.76,
    "totalOrders": 5,
    "avgRevenue": 6.78,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 29,
    "totalRevenue": 255.89,
    "totalOrders": 6,
    "avgRevenue": 8.82,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 29,
    "totalRevenue": 21.45,
    "totalOrders": 1,
    "avgRevenue": 0.74,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 29,
    "totalRevenue": 132.35,
    "totalOrders": 4,
    "avgRevenue": 4.56,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 29,
    "totalRevenue": 132.25,
    "totalOrders": 3,
    "avgRevenue": 4.56,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 29,
    "totalRevenue": 261.11,
    "totalOrders": 8,
    "avgRevenue": 9,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 29,
    "totalRevenue": 241.92,
    "totalOrders": 6,
    "avgRevenue": 8.34,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 29,
    "totalRevenue": 198.31,
    "totalOrders": 6,
    "avgRevenue": 6.84,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 29,
    "totalRevenue": 131.61,
    "totalOrders": 4,
    "avgRevenue": 4.54,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 31,
    "totalRevenue": 28.88,
    "totalOrders": 1,
    "avgRevenue": 0.93,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 31,
    "totalRevenue": 107.09,
    "totalOrders": 2,
    "avgRevenue": 3.45,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 31,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 31,
    "totalRevenue": 165.87,
    "totalOrders": 5,
    "avgRevenue": 5.35,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 31,
    "totalRevenue": 13.71,
    "totalOrders": 1,
    "avgRevenue": 0.44,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 31,
    "totalRevenue": 120.15,
    "totalOrders": 2,
    "avgRevenue": 3.88,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 31,
    "totalRevenue": 306.21,
    "totalOrders": 7,
    "avgRevenue": 9.88,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 31,
    "totalRevenue": 135.1,
    "totalOrders": 5,
    "avgRevenue": 4.36,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 31,
    "totalRevenue": 384.94,
    "totalOrders": 8,
    "avgRevenue": 12.42,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 31,
    "totalRevenue": 266,
    "totalOrders": 9,
    "avgRevenue": 8.58,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 31,
    "totalRevenue": 330.06,
    "totalOrders": 8,
    "avgRevenue": 10.65,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 31,
    "totalRevenue": 316.09,
    "totalOrders": 7,
    "avgRevenue": 10.2,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 31,
    "totalRevenue": 89.87,
    "totalOrders": 3,
    "avgRevenue": 2.9,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 31,
    "totalRevenue": 87.41,
    "totalOrders": 2,
    "avgRevenue": 2.82,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 31,
    "totalRevenue": 182.4,
    "totalOrders": 6,
    "avgRevenue": 5.88,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 31,
    "totalRevenue": 184.2,
    "totalOrders": 6,
    "avgRevenue": 5.94,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 31,
    "totalRevenue": 288.96,
    "totalOrders": 6,
    "avgRevenue": 9.32,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 31,
    "totalRevenue": 422.21,
    "totalOrders": 6,
    "avgRevenue": 13.62,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 31,
    "totalRevenue": 1.26,
    "totalOrders": 1,
    "avgRevenue": 0.04,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 29,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 29,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 29,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 29,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 29,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 29,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 29,
    "totalRevenue": 113.75,
    "totalOrders": 2,
    "avgRevenue": 3.92,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 29,
    "totalRevenue": 156.39,
    "totalOrders": 4,
    "avgRevenue": 5.39,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 29,
    "totalRevenue": 219.51,
    "totalOrders": 7,
    "avgRevenue": 7.57,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 29,
    "totalRevenue": 79.11,
    "totalOrders": 2,
    "avgRevenue": 2.73,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 29,
    "totalRevenue": 212.56,
    "totalOrders": 7,
    "avgRevenue": 7.33,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 29,
    "totalRevenue": 29.08,
    "totalOrders": 1,
    "avgRevenue": 1,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 29,
    "totalRevenue": 262.45,
    "totalOrders": 8,
    "avgRevenue": 9.05,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 29,
    "totalRevenue": 103.57,
    "totalOrders": 3,
    "avgRevenue": 3.57,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 29,
    "totalRevenue": 166.22,
    "totalOrders": 6,
    "avgRevenue": 5.73,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 29,
    "totalRevenue": 222.2,
    "totalOrders": 7,
    "avgRevenue": 7.66,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 29,
    "totalRevenue": 260,
    "totalOrders": 5,
    "avgRevenue": 8.97,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 29,
    "totalRevenue": 148.68,
    "totalOrders": 3,
    "avgRevenue": 5.13,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 29,
    "totalRevenue": 29.74,
    "totalOrders": 1,
    "avgRevenue": 1.03,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 29,
    "totalRevenue": 337.76,
    "totalOrders": 8,
    "avgRevenue": 11.65,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 29,
    "totalRevenue": 183.11,
    "totalOrders": 5,
    "avgRevenue": 6.31,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 29,
    "totalRevenue": 100.7,
    "totalOrders": 5,
    "avgRevenue": 3.47,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 29,
    "totalRevenue": 254.47,
    "totalOrders": 6,
    "avgRevenue": 8.77,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 29,
    "totalRevenue": 119.22,
    "totalOrders": 2,
    "avgRevenue": 4.11,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 27,
    "totalRevenue": 182.56,
    "totalOrders": 3,
    "avgRevenue": 6.76,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 27,
    "totalRevenue": 89.71,
    "totalOrders": 2,
    "avgRevenue": 3.32,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 27,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 27,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 27,
    "totalRevenue": 29.6,
    "totalOrders": 1,
    "avgRevenue": 1.1,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 27,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 27,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 27,
    "totalRevenue": 64.95,
    "totalOrders": 1,
    "avgRevenue": 2.41,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 27,
    "totalRevenue": 111.15,
    "totalOrders": 6,
    "avgRevenue": 4.12,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 27,
    "totalRevenue": 569.2,
    "totalOrders": 2,
    "avgRevenue": 21.08,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 27,
    "totalRevenue": 293.63,
    "totalOrders": 7,
    "avgRevenue": 10.88,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 27,
    "totalRevenue": 39.47,
    "totalOrders": 2,
    "avgRevenue": 1.46,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 27,
    "totalRevenue": 237.7,
    "totalOrders": 7,
    "avgRevenue": 8.8,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 27,
    "totalRevenue": 343.05,
    "totalOrders": 7,
    "avgRevenue": 12.71,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 27,
    "totalRevenue": 649.07,
    "totalOrders": 5,
    "avgRevenue": 24.04,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 27,
    "totalRevenue": 128.77,
    "totalOrders": 4,
    "avgRevenue": 4.77,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 27,
    "totalRevenue": 145.01,
    "totalOrders": 6,
    "avgRevenue": 5.37,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 27,
    "totalRevenue": 156.59,
    "totalOrders": 4,
    "avgRevenue": 5.8,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 27,
    "totalRevenue": 394,
    "totalOrders": 7,
    "avgRevenue": 14.59,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 27,
    "totalRevenue": 242.24,
    "totalOrders": 8,
    "avgRevenue": 8.97,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 27,
    "totalRevenue": 245.8,
    "totalOrders": 6,
    "avgRevenue": 9.1,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 27,
    "totalRevenue": 272.23,
    "totalOrders": 9,
    "avgRevenue": 10.08,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 27,
    "totalRevenue": 312.43,
    "totalOrders": 6,
    "avgRevenue": 11.57,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 27,
    "totalRevenue": 102.73,
    "totalOrders": 4,
    "avgRevenue": 3.8,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 25,
    "totalRevenue": 69.23,
    "totalOrders": 2,
    "avgRevenue": 2.77,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 25,
    "totalRevenue": 39.49,
    "totalOrders": 1,
    "avgRevenue": 1.58,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 25,
    "totalRevenue": 123.24,
    "totalOrders": 4,
    "avgRevenue": 4.93,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 25,
    "totalRevenue": 146.69,
    "totalOrders": 2,
    "avgRevenue": 5.87,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 25,
    "totalRevenue": 214.5,
    "totalOrders": 5,
    "avgRevenue": 8.58,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 25,
    "totalRevenue": 514.76,
    "totalOrders": 10,
    "avgRevenue": 20.59,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 25,
    "totalRevenue": 235.03,
    "totalOrders": 5,
    "avgRevenue": 9.4,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 25,
    "totalRevenue": 162.88,
    "totalOrders": 4,
    "avgRevenue": 6.52,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 25,
    "totalRevenue": 48.42,
    "totalOrders": 2,
    "avgRevenue": 1.94,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 25,
    "totalRevenue": 172.82,
    "totalOrders": 4,
    "avgRevenue": 6.91,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 25,
    "totalRevenue": 122.96,
    "totalOrders": 4,
    "avgRevenue": 4.92,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 25,
    "totalRevenue": 89.22,
    "totalOrders": 1,
    "avgRevenue": 3.57,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 25,
    "totalRevenue": 243.24,
    "totalOrders": 6,
    "avgRevenue": 9.73,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 25,
    "totalRevenue": 210.46,
    "totalOrders": 6,
    "avgRevenue": 8.42,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 25,
    "totalRevenue": 196.12,
    "totalOrders": 6,
    "avgRevenue": 7.84,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 25,
    "totalRevenue": 141.08,
    "totalOrders": 4,
    "avgRevenue": 5.64,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 25,
    "totalRevenue": 113.3,
    "totalOrders": 3,
    "avgRevenue": 4.53,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 25,
    "totalRevenue": 47.22,
    "totalOrders": 2,
    "avgRevenue": 1.89,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 30,
    "totalRevenue": 10.8,
    "totalOrders": 1,
    "avgRevenue": 0.36,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 30,
    "totalRevenue": 54.85,
    "totalOrders": 1,
    "avgRevenue": 1.83,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 30,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 30,
    "totalRevenue": 87.07,
    "totalOrders": 2,
    "avgRevenue": 2.9,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 30,
    "totalRevenue": 174.75,
    "totalOrders": 3,
    "avgRevenue": 5.83,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 30,
    "totalRevenue": 294.4,
    "totalOrders": 7,
    "avgRevenue": 9.81,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 30,
    "totalRevenue": 149.04,
    "totalOrders": 4,
    "avgRevenue": 4.97,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 30,
    "totalRevenue": 161.88,
    "totalOrders": 6,
    "avgRevenue": 5.4,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 30,
    "totalRevenue": 132.18,
    "totalOrders": 4,
    "avgRevenue": 4.41,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 30,
    "totalRevenue": 295.31,
    "totalOrders": 6,
    "avgRevenue": 9.84,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 30,
    "totalRevenue": 342.13,
    "totalOrders": 8,
    "avgRevenue": 11.4,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 30,
    "totalRevenue": 140.1,
    "totalOrders": 3,
    "avgRevenue": 4.67,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 30,
    "totalRevenue": 162.28,
    "totalOrders": 3,
    "avgRevenue": 5.41,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 30,
    "totalRevenue": 277.03,
    "totalOrders": 4,
    "avgRevenue": 9.23,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 30,
    "totalRevenue": 103.35,
    "totalOrders": 4,
    "avgRevenue": 3.45,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 30,
    "totalRevenue": 169.2,
    "totalOrders": 4,
    "avgRevenue": 5.64,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 30,
    "totalRevenue": 124.67,
    "totalOrders": 3,
    "avgRevenue": 4.16,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 30,
    "totalRevenue": 110.47,
    "totalOrders": 3,
    "avgRevenue": 3.68,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 30,
    "totalRevenue": 201.86,
    "totalOrders": 5,
    "avgRevenue": 6.73,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 30,
    "totalRevenue": 295.44,
    "totalOrders": 5,
    "avgRevenue": 9.85,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 30,
    "totalRevenue": 75.89,
    "totalOrders": 2,
    "avgRevenue": 2.53,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 28,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 28,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 28,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 28,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 28,
    "totalRevenue": 57.66,
    "totalOrders": 1,
    "avgRevenue": 2.06,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 28,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 28,
    "totalRevenue": 55.6,
    "totalOrders": 1,
    "avgRevenue": 1.99,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 28,
    "totalRevenue": 163.88,
    "totalOrders": 3,
    "avgRevenue": 5.85,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 28,
    "totalRevenue": 71.59,
    "totalOrders": 2,
    "avgRevenue": 2.56,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 28,
    "totalRevenue": 229.88,
    "totalOrders": 6,
    "avgRevenue": 8.21,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 28,
    "totalRevenue": 81.73,
    "totalOrders": 2,
    "avgRevenue": 2.92,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 28,
    "totalRevenue": 250.35,
    "totalOrders": 4,
    "avgRevenue": 8.94,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 28,
    "totalRevenue": 131.05,
    "totalOrders": 4,
    "avgRevenue": 4.68,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 28,
    "totalRevenue": 243.2,
    "totalOrders": 7,
    "avgRevenue": 8.69,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 28,
    "totalRevenue": 296.16,
    "totalOrders": 9,
    "avgRevenue": 10.58,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 28,
    "totalRevenue": 94.94,
    "totalOrders": 3,
    "avgRevenue": 3.39,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 28,
    "totalRevenue": 184.11,
    "totalOrders": 5,
    "avgRevenue": 6.58,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 28,
    "totalRevenue": 161.39,
    "totalOrders": 4,
    "avgRevenue": 5.76,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 28,
    "totalRevenue": 18.45,
    "totalOrders": 1,
    "avgRevenue": 0.66,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 28,
    "totalRevenue": 241.71,
    "totalOrders": 4,
    "avgRevenue": 8.63,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 28,
    "totalRevenue": 274.15,
    "totalOrders": 7,
    "avgRevenue": 9.79,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 28,
    "totalRevenue": 187.13,
    "totalOrders": 4,
    "avgRevenue": 6.68,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 28,
    "totalRevenue": 121.98,
    "totalOrders": 3,
    "avgRevenue": 4.36,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 28,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  }
];
