// Auto-generated by scripts/updateData.js — last update: 2026-08-13
// SK: hourly purchase behaviour (EUR), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = neděle … 6 = sobota
  hour:         number;  // 0–23
  dayCount:     number;  // počet dnů s daným dnem v týdnu v datasetu
  totalRevenue: number;  // celkové tržby bez DPH za (dow, hour)
  totalOrders:  number;  // celkový počet objednávek za (dow, hour)
  avgRevenue:   number;  // průměrné tržby bez DPH / den
  avgOrders:    number;  // průměrný počet objednávek / den
}

export const hourlyDataSK: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 24,
    "totalRevenue": 39.23,
    "totalOrders": 1,
    "avgRevenue": 1.63,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 24,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 24,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 24,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 24,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 24,
    "totalRevenue": 47.94,
    "totalOrders": 1,
    "avgRevenue": 2,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 24,
    "totalRevenue": 50.12,
    "totalOrders": 1,
    "avgRevenue": 2.09,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 24,
    "totalRevenue": 7.5,
    "totalOrders": 1,
    "avgRevenue": 0.31,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 24,
    "totalRevenue": 71.09,
    "totalOrders": 2,
    "avgRevenue": 2.96,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 24,
    "totalRevenue": 140.22,
    "totalOrders": 4,
    "avgRevenue": 5.84,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 24,
    "totalRevenue": 329.26,
    "totalOrders": 5,
    "avgRevenue": 13.72,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 24,
    "totalRevenue": 16.49,
    "totalOrders": 1,
    "avgRevenue": 0.69,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 24,
    "totalRevenue": 117.62,
    "totalOrders": 4,
    "avgRevenue": 4.9,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 24,
    "totalRevenue": 212.11,
    "totalOrders": 4,
    "avgRevenue": 8.84,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 24,
    "totalRevenue": 194.7,
    "totalOrders": 4,
    "avgRevenue": 8.11,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 24,
    "totalRevenue": 196.76,
    "totalOrders": 5,
    "avgRevenue": 8.2,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 24,
    "totalRevenue": 255.89,
    "totalOrders": 6,
    "avgRevenue": 10.66,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 24,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 24,
    "totalRevenue": 132.35,
    "totalOrders": 4,
    "avgRevenue": 5.51,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 24,
    "totalRevenue": 28.38,
    "totalOrders": 1,
    "avgRevenue": 1.18,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 24,
    "totalRevenue": 261.11,
    "totalOrders": 8,
    "avgRevenue": 10.88,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 24,
    "totalRevenue": 141,
    "totalOrders": 4,
    "avgRevenue": 5.88,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 24,
    "totalRevenue": 115.45,
    "totalOrders": 3,
    "avgRevenue": 4.81,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 24,
    "totalRevenue": 75.98,
    "totalOrders": 2,
    "avgRevenue": 3.17,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 26,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 26,
    "totalRevenue": 28.88,
    "totalOrders": 1,
    "avgRevenue": 1.11,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 26,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 26,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 26,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 26,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 26,
    "totalRevenue": 96.06,
    "totalOrders": 1,
    "avgRevenue": 3.69,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 26,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 26,
    "totalRevenue": 89.63,
    "totalOrders": 2,
    "avgRevenue": 3.45,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 26,
    "totalRevenue": 13.71,
    "totalOrders": 1,
    "avgRevenue": 0.53,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 26,
    "totalRevenue": 78.14,
    "totalOrders": 1,
    "avgRevenue": 3.01,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 26,
    "totalRevenue": 205.16,
    "totalOrders": 4,
    "avgRevenue": 7.89,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 26,
    "totalRevenue": 121.57,
    "totalOrders": 4,
    "avgRevenue": 4.68,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 26,
    "totalRevenue": 298.63,
    "totalOrders": 6,
    "avgRevenue": 11.49,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 26,
    "totalRevenue": 180.45,
    "totalOrders": 6,
    "avgRevenue": 6.94,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 26,
    "totalRevenue": 330.06,
    "totalOrders": 8,
    "avgRevenue": 12.69,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 26,
    "totalRevenue": 161.92,
    "totalOrders": 3,
    "avgRevenue": 6.23,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 26,
    "totalRevenue": 89.87,
    "totalOrders": 3,
    "avgRevenue": 3.46,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 26,
    "totalRevenue": 87.41,
    "totalOrders": 2,
    "avgRevenue": 3.36,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 26,
    "totalRevenue": 182.4,
    "totalOrders": 6,
    "avgRevenue": 7.02,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 26,
    "totalRevenue": 95.38,
    "totalOrders": 3,
    "avgRevenue": 3.67,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 26,
    "totalRevenue": 178.62,
    "totalOrders": 4,
    "avgRevenue": 6.87,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 26,
    "totalRevenue": 422.21,
    "totalOrders": 6,
    "avgRevenue": 16.24,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 26,
    "totalRevenue": 1.26,
    "totalOrders": 1,
    "avgRevenue": 0.05,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 25,
    "totalRevenue": 113.75,
    "totalOrders": 2,
    "avgRevenue": 4.55,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 25,
    "totalRevenue": 156.39,
    "totalOrders": 4,
    "avgRevenue": 6.26,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 25,
    "totalRevenue": 165.07,
    "totalOrders": 5,
    "avgRevenue": 6.6,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 25,
    "totalRevenue": 79.11,
    "totalOrders": 2,
    "avgRevenue": 3.16,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 25,
    "totalRevenue": 192.52,
    "totalOrders": 6,
    "avgRevenue": 7.7,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 25,
    "totalRevenue": 29.08,
    "totalOrders": 1,
    "avgRevenue": 1.16,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 25,
    "totalRevenue": 238.34,
    "totalOrders": 7,
    "avgRevenue": 9.53,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 25,
    "totalRevenue": 70.79,
    "totalOrders": 2,
    "avgRevenue": 2.83,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 25,
    "totalRevenue": 144.94,
    "totalOrders": 5,
    "avgRevenue": 5.8,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 25,
    "totalRevenue": 166.63,
    "totalOrders": 5,
    "avgRevenue": 6.67,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 25,
    "totalRevenue": 214.96,
    "totalOrders": 4,
    "avgRevenue": 8.6,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 25,
    "totalRevenue": 148.68,
    "totalOrders": 3,
    "avgRevenue": 5.95,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 25,
    "totalRevenue": 29.74,
    "totalOrders": 1,
    "avgRevenue": 1.19,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 25,
    "totalRevenue": 307.81,
    "totalOrders": 7,
    "avgRevenue": 12.31,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 25,
    "totalRevenue": 151.53,
    "totalOrders": 4,
    "avgRevenue": 6.06,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 25,
    "totalRevenue": 90.74,
    "totalOrders": 4,
    "avgRevenue": 3.63,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 25,
    "totalRevenue": 109.31,
    "totalOrders": 3,
    "avgRevenue": 4.37,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 25,
    "totalRevenue": 119.22,
    "totalOrders": 2,
    "avgRevenue": 4.77,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 23,
    "totalRevenue": 182.56,
    "totalOrders": 3,
    "avgRevenue": 7.94,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 23,
    "totalRevenue": 89.71,
    "totalOrders": 2,
    "avgRevenue": 3.9,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 23,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 23,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 23,
    "totalRevenue": 29.6,
    "totalOrders": 1,
    "avgRevenue": 1.29,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 23,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 23,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 23,
    "totalRevenue": 64.95,
    "totalOrders": 1,
    "avgRevenue": 2.82,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 23,
    "totalRevenue": 91.27,
    "totalOrders": 3,
    "avgRevenue": 3.97,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 23,
    "totalRevenue": 569.2,
    "totalOrders": 2,
    "avgRevenue": 24.75,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 23,
    "totalRevenue": 222.66,
    "totalOrders": 6,
    "avgRevenue": 9.68,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 23,
    "totalRevenue": 39.47,
    "totalOrders": 2,
    "avgRevenue": 1.72,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 23,
    "totalRevenue": 160.24,
    "totalOrders": 5,
    "avgRevenue": 6.97,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 23,
    "totalRevenue": 343.05,
    "totalOrders": 7,
    "avgRevenue": 14.92,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 23,
    "totalRevenue": 649.07,
    "totalOrders": 5,
    "avgRevenue": 28.22,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 23,
    "totalRevenue": 88.21,
    "totalOrders": 3,
    "avgRevenue": 3.84,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 23,
    "totalRevenue": 125.11,
    "totalOrders": 5,
    "avgRevenue": 5.44,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 23,
    "totalRevenue": 182.42,
    "totalOrders": 5,
    "avgRevenue": 7.93,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 23,
    "totalRevenue": 394,
    "totalOrders": 7,
    "avgRevenue": 17.13,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 23,
    "totalRevenue": 220.72,
    "totalOrders": 7,
    "avgRevenue": 9.6,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 23,
    "totalRevenue": 133.05,
    "totalOrders": 3,
    "avgRevenue": 5.78,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 23,
    "totalRevenue": 210.52,
    "totalOrders": 7,
    "avgRevenue": 9.15,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 23,
    "totalRevenue": 234.32,
    "totalOrders": 4,
    "avgRevenue": 10.19,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 23,
    "totalRevenue": 80.85,
    "totalOrders": 3,
    "avgRevenue": 3.52,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 20,
    "totalRevenue": 69.23,
    "totalOrders": 2,
    "avgRevenue": 3.46,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 20,
    "totalRevenue": 39.49,
    "totalOrders": 1,
    "avgRevenue": 1.97,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 20,
    "totalRevenue": 123.24,
    "totalOrders": 4,
    "avgRevenue": 6.16,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 20,
    "totalRevenue": 80.98,
    "totalOrders": 1,
    "avgRevenue": 4.05,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 20,
    "totalRevenue": 149.62,
    "totalOrders": 3,
    "avgRevenue": 7.48,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 20,
    "totalRevenue": 377.66,
    "totalOrders": 8,
    "avgRevenue": 18.88,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 20,
    "totalRevenue": 235.03,
    "totalOrders": 5,
    "avgRevenue": 11.75,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 20,
    "totalRevenue": 106.68,
    "totalOrders": 2,
    "avgRevenue": 5.33,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 20,
    "totalRevenue": 48.42,
    "totalOrders": 2,
    "avgRevenue": 2.42,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 20,
    "totalRevenue": 172.82,
    "totalOrders": 3,
    "avgRevenue": 8.64,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 20,
    "totalRevenue": 122.96,
    "totalOrders": 4,
    "avgRevenue": 6.15,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 20,
    "totalRevenue": 89.22,
    "totalOrders": 1,
    "avgRevenue": 4.46,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 20,
    "totalRevenue": 145.72,
    "totalOrders": 5,
    "avgRevenue": 7.29,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 20,
    "totalRevenue": 111.09,
    "totalOrders": 4,
    "avgRevenue": 5.55,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 20,
    "totalRevenue": 169.69,
    "totalOrders": 5,
    "avgRevenue": 8.48,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 20,
    "totalRevenue": 141.08,
    "totalOrders": 4,
    "avgRevenue": 7.05,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 20,
    "totalRevenue": 72.21,
    "totalOrders": 2,
    "avgRevenue": 3.61,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 20,
    "totalRevenue": 47.22,
    "totalOrders": 2,
    "avgRevenue": 2.36,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 25,
    "totalRevenue": 10.8,
    "totalOrders": 1,
    "avgRevenue": 0.43,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 25,
    "totalRevenue": 54.85,
    "totalOrders": 1,
    "avgRevenue": 2.19,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 25,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 25,
    "totalRevenue": 75.28,
    "totalOrders": 1,
    "avgRevenue": 3.01,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 25,
    "totalRevenue": 64.99,
    "totalOrders": 1,
    "avgRevenue": 2.6,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 25,
    "totalRevenue": 294.4,
    "totalOrders": 7,
    "avgRevenue": 11.78,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 25,
    "totalRevenue": 149.04,
    "totalOrders": 4,
    "avgRevenue": 5.96,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 25,
    "totalRevenue": 38.24,
    "totalOrders": 2,
    "avgRevenue": 1.53,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 25,
    "totalRevenue": 53.65,
    "totalOrders": 2,
    "avgRevenue": 2.15,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 25,
    "totalRevenue": 250.02,
    "totalOrders": 5,
    "avgRevenue": 10,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 25,
    "totalRevenue": 165.35,
    "totalOrders": 5,
    "avgRevenue": 6.61,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 25,
    "totalRevenue": 140.1,
    "totalOrders": 3,
    "avgRevenue": 5.6,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 25,
    "totalRevenue": 162.28,
    "totalOrders": 3,
    "avgRevenue": 6.49,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 25,
    "totalRevenue": 256.86,
    "totalOrders": 3,
    "avgRevenue": 10.27,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 25,
    "totalRevenue": 51.48,
    "totalOrders": 3,
    "avgRevenue": 2.06,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 25,
    "totalRevenue": 169.2,
    "totalOrders": 4,
    "avgRevenue": 6.77,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 25,
    "totalRevenue": 83.91,
    "totalOrders": 2,
    "avgRevenue": 3.36,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 25,
    "totalRevenue": 110.47,
    "totalOrders": 3,
    "avgRevenue": 4.42,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 25,
    "totalRevenue": 201.86,
    "totalOrders": 5,
    "avgRevenue": 8.07,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 25,
    "totalRevenue": 236.55,
    "totalOrders": 4,
    "avgRevenue": 9.46,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 25,
    "totalRevenue": 75.89,
    "totalOrders": 2,
    "avgRevenue": 3.04,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 23,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 23,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 23,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 23,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 23,
    "totalRevenue": 57.66,
    "totalOrders": 1,
    "avgRevenue": 2.51,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 23,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 23,
    "totalRevenue": 55.6,
    "totalOrders": 1,
    "avgRevenue": 2.42,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 23,
    "totalRevenue": 52.12,
    "totalOrders": 1,
    "avgRevenue": 2.27,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 23,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 23,
    "totalRevenue": 144.32,
    "totalOrders": 3,
    "avgRevenue": 6.27,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 23,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 23,
    "totalRevenue": 193.53,
    "totalOrders": 3,
    "avgRevenue": 8.41,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 23,
    "totalRevenue": 111.5,
    "totalOrders": 3,
    "avgRevenue": 4.85,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 23,
    "totalRevenue": 179.29,
    "totalOrders": 5,
    "avgRevenue": 7.8,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 23,
    "totalRevenue": 221.66,
    "totalOrders": 6,
    "avgRevenue": 9.64,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 23,
    "totalRevenue": 94.94,
    "totalOrders": 3,
    "avgRevenue": 4.13,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 23,
    "totalRevenue": 72.57,
    "totalOrders": 3,
    "avgRevenue": 3.16,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 23,
    "totalRevenue": 111.21,
    "totalOrders": 3,
    "avgRevenue": 4.84,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 23,
    "totalRevenue": 18.45,
    "totalOrders": 1,
    "avgRevenue": 0.8,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 23,
    "totalRevenue": 241.71,
    "totalOrders": 4,
    "avgRevenue": 10.51,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 23,
    "totalRevenue": 208.31,
    "totalOrders": 5,
    "avgRevenue": 9.06,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 23,
    "totalRevenue": 187.13,
    "totalOrders": 4,
    "avgRevenue": 8.14,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 23,
    "totalRevenue": 121.98,
    "totalOrders": 3,
    "avgRevenue": 5.3,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 23,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  }
];
