// Auto-generated by scripts/updateData.js — last update: 2026-08-09
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = neděle … 6 = sobota
  hour:         number;  // 0–23
  dayCount:     number;  // počet dnů s daným dnem v týdnu v datasetu
  totalRevenue: number;  // celkové tržby bez DPH za (dow, hour)
  totalOrders:  number;  // celkový počet objednávek za (dow, hour)
  avgRevenue:   number;  // průměrné tržby bez DPH / den
  avgOrders:    number;  // průměrný počet objednávek / den
}

export const hourlyDataCZ: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 86,
    "totalRevenue": 12969.33,
    "totalOrders": 15,
    "avgRevenue": 150.81,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 86,
    "totalRevenue": 3425.89,
    "totalOrders": 4,
    "avgRevenue": 39.84,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 86,
    "totalRevenue": 1234.82,
    "totalOrders": 1,
    "avgRevenue": 14.36,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 86,
    "totalRevenue": 4636.61,
    "totalOrders": 4,
    "avgRevenue": 53.91,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 86,
    "totalRevenue": 8698.21,
    "totalOrders": 4,
    "avgRevenue": 101.14,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 86,
    "totalRevenue": 4084.79,
    "totalOrders": 6,
    "avgRevenue": 47.5,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 86,
    "totalRevenue": 9377.43,
    "totalOrders": 13,
    "avgRevenue": 109.04,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 86,
    "totalRevenue": 21455.3,
    "totalOrders": 25,
    "avgRevenue": 249.48,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 86,
    "totalRevenue": 35351.23,
    "totalOrders": 43,
    "avgRevenue": 411.06,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 86,
    "totalRevenue": 51572.38,
    "totalOrders": 57,
    "avgRevenue": 599.68,
    "avgOrders": 0.66
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 86,
    "totalRevenue": 49336.79,
    "totalOrders": 60,
    "avgRevenue": 573.68,
    "avgOrders": 0.7
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 86,
    "totalRevenue": 57065.9,
    "totalOrders": 63,
    "avgRevenue": 663.56,
    "avgOrders": 0.73
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 86,
    "totalRevenue": 45716.24,
    "totalOrders": 57,
    "avgRevenue": 531.58,
    "avgOrders": 0.66
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 86,
    "totalRevenue": 53809.84,
    "totalOrders": 65,
    "avgRevenue": 625.7,
    "avgOrders": 0.76
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 86,
    "totalRevenue": 56240.84,
    "totalOrders": 62,
    "avgRevenue": 653.96,
    "avgOrders": 0.72
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 86,
    "totalRevenue": 51239.44,
    "totalOrders": 56,
    "avgRevenue": 595.81,
    "avgOrders": 0.65
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 86,
    "totalRevenue": 63682.35,
    "totalOrders": 65,
    "avgRevenue": 740.49,
    "avgOrders": 0.76
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 86,
    "totalRevenue": 57953.24,
    "totalOrders": 66,
    "avgRevenue": 673.87,
    "avgOrders": 0.77
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 86,
    "totalRevenue": 60875.52,
    "totalOrders": 69,
    "avgRevenue": 707.85,
    "avgOrders": 0.8
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 86,
    "totalRevenue": 86442.33,
    "totalOrders": 100,
    "avgRevenue": 1005.14,
    "avgOrders": 1.16
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 86,
    "totalRevenue": 86876.41,
    "totalOrders": 95,
    "avgRevenue": 1010.19,
    "avgOrders": 1.1
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 86,
    "totalRevenue": 77849.48,
    "totalOrders": 85,
    "avgRevenue": 905.23,
    "avgOrders": 0.99
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 86,
    "totalRevenue": 51738.46,
    "totalOrders": 56,
    "avgRevenue": 601.61,
    "avgOrders": 0.65
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 86,
    "totalRevenue": 32868.54,
    "totalOrders": 37,
    "avgRevenue": 382.19,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 86,
    "totalRevenue": 13492.29,
    "totalOrders": 13,
    "avgRevenue": 156.89,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 86,
    "totalRevenue": 4261.59,
    "totalOrders": 3,
    "avgRevenue": 49.55,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 86,
    "totalRevenue": 1774.01,
    "totalOrders": 3,
    "avgRevenue": 20.63,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 86,
    "totalRevenue": 913.67,
    "totalOrders": 1,
    "avgRevenue": 10.62,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 86,
    "totalRevenue": 2884.83,
    "totalOrders": 4,
    "avgRevenue": 33.54,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 86,
    "totalRevenue": 7043.92,
    "totalOrders": 10,
    "avgRevenue": 81.91,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 86,
    "totalRevenue": 9614.55,
    "totalOrders": 13,
    "avgRevenue": 111.8,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 86,
    "totalRevenue": 31097.82,
    "totalOrders": 40,
    "avgRevenue": 361.6,
    "avgOrders": 0.47
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 86,
    "totalRevenue": 49177.97,
    "totalOrders": 55,
    "avgRevenue": 571.84,
    "avgOrders": 0.64
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 86,
    "totalRevenue": 77273.96,
    "totalOrders": 75,
    "avgRevenue": 898.53,
    "avgOrders": 0.87
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 86,
    "totalRevenue": 76591.06,
    "totalOrders": 88,
    "avgRevenue": 890.59,
    "avgOrders": 1.02
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 86,
    "totalRevenue": 77003.64,
    "totalOrders": 77,
    "avgRevenue": 895.39,
    "avgOrders": 0.9
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 86,
    "totalRevenue": 64168.62,
    "totalOrders": 71,
    "avgRevenue": 746.15,
    "avgOrders": 0.83
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 86,
    "totalRevenue": 58059.64,
    "totalOrders": 63,
    "avgRevenue": 675.11,
    "avgOrders": 0.73
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 86,
    "totalRevenue": 69816.02,
    "totalOrders": 74,
    "avgRevenue": 811.81,
    "avgOrders": 0.86
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 86,
    "totalRevenue": 58890.92,
    "totalOrders": 67,
    "avgRevenue": 684.78,
    "avgOrders": 0.78
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 86,
    "totalRevenue": 73057.19,
    "totalOrders": 81,
    "avgRevenue": 849.5,
    "avgOrders": 0.94
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 86,
    "totalRevenue": 59875.65,
    "totalOrders": 59,
    "avgRevenue": 696.23,
    "avgOrders": 0.69
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 86,
    "totalRevenue": 53361.21,
    "totalOrders": 62,
    "avgRevenue": 620.48,
    "avgOrders": 0.72
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 86,
    "totalRevenue": 62249.09,
    "totalOrders": 69,
    "avgRevenue": 723.83,
    "avgOrders": 0.8
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 86,
    "totalRevenue": 83485.84,
    "totalOrders": 90,
    "avgRevenue": 970.77,
    "avgOrders": 1.05
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 86,
    "totalRevenue": 102885.43,
    "totalOrders": 123,
    "avgRevenue": 1196.34,
    "avgOrders": 1.43
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 86,
    "totalRevenue": 68683.62,
    "totalOrders": 67,
    "avgRevenue": 798.65,
    "avgOrders": 0.78
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 86,
    "totalRevenue": 24567.38,
    "totalOrders": 30,
    "avgRevenue": 285.67,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 85,
    "totalRevenue": 7865.26,
    "totalOrders": 9,
    "avgRevenue": 92.53,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 85,
    "totalRevenue": 3185.01,
    "totalOrders": 5,
    "avgRevenue": 37.47,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 85,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 85,
    "totalRevenue": 4975.99,
    "totalOrders": 5,
    "avgRevenue": 58.54,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 85,
    "totalRevenue": 5529.44,
    "totalOrders": 6,
    "avgRevenue": 65.05,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 85,
    "totalRevenue": 8426.35,
    "totalOrders": 11,
    "avgRevenue": 99.13,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 85,
    "totalRevenue": 8273.93,
    "totalOrders": 11,
    "avgRevenue": 97.34,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 85,
    "totalRevenue": 41641.9,
    "totalOrders": 41,
    "avgRevenue": 489.9,
    "avgOrders": 0.48
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 85,
    "totalRevenue": 51288.14,
    "totalOrders": 61,
    "avgRevenue": 603.39,
    "avgOrders": 0.72
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 85,
    "totalRevenue": 59301.26,
    "totalOrders": 75,
    "avgRevenue": 697.66,
    "avgOrders": 0.88
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 85,
    "totalRevenue": 94594.92,
    "totalOrders": 96,
    "avgRevenue": 1112.88,
    "avgOrders": 1.13
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 85,
    "totalRevenue": 49015.51,
    "totalOrders": 60,
    "avgRevenue": 576.65,
    "avgOrders": 0.71
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 85,
    "totalRevenue": 62668.81,
    "totalOrders": 73,
    "avgRevenue": 737.28,
    "avgOrders": 0.86
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 85,
    "totalRevenue": 81108.26,
    "totalOrders": 68,
    "avgRevenue": 954.21,
    "avgOrders": 0.8
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 85,
    "totalRevenue": 55388.57,
    "totalOrders": 68,
    "avgRevenue": 651.63,
    "avgOrders": 0.8
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 85,
    "totalRevenue": 41383.17,
    "totalOrders": 50,
    "avgRevenue": 486.86,
    "avgOrders": 0.59
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 85,
    "totalRevenue": 44654.86,
    "totalOrders": 53,
    "avgRevenue": 525.35,
    "avgOrders": 0.62
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 85,
    "totalRevenue": 53700.78,
    "totalOrders": 53,
    "avgRevenue": 631.77,
    "avgOrders": 0.62
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 85,
    "totalRevenue": 70546.82,
    "totalOrders": 78,
    "avgRevenue": 829.96,
    "avgOrders": 0.92
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 85,
    "totalRevenue": 48923.2,
    "totalOrders": 65,
    "avgRevenue": 575.57,
    "avgOrders": 0.76
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 85,
    "totalRevenue": 90246.31,
    "totalOrders": 103,
    "avgRevenue": 1061.72,
    "avgOrders": 1.21
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 85,
    "totalRevenue": 79693.73,
    "totalOrders": 95,
    "avgRevenue": 937.57,
    "avgOrders": 1.12
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 85,
    "totalRevenue": 48232.41,
    "totalOrders": 50,
    "avgRevenue": 567.44,
    "avgOrders": 0.59
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 85,
    "totalRevenue": 18139.43,
    "totalOrders": 20,
    "avgRevenue": 213.41,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 87,
    "totalRevenue": 9320.54,
    "totalOrders": 8,
    "avgRevenue": 107.13,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 87,
    "totalRevenue": 3778.75,
    "totalOrders": 5,
    "avgRevenue": 43.43,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 87,
    "totalRevenue": 3527.93,
    "totalOrders": 4,
    "avgRevenue": 40.55,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 87,
    "totalRevenue": 1140.08,
    "totalOrders": 3,
    "avgRevenue": 13.1,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 87,
    "totalRevenue": 1832.15,
    "totalOrders": 3,
    "avgRevenue": 21.06,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 87,
    "totalRevenue": 7750.51,
    "totalOrders": 11,
    "avgRevenue": 89.09,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 87,
    "totalRevenue": 15021.56,
    "totalOrders": 18,
    "avgRevenue": 172.66,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 87,
    "totalRevenue": 51424.16,
    "totalOrders": 37,
    "avgRevenue": 591.08,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 87,
    "totalRevenue": 62474.94,
    "totalOrders": 74,
    "avgRevenue": 718.1,
    "avgOrders": 0.85
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 87,
    "totalRevenue": 54982.07,
    "totalOrders": 63,
    "avgRevenue": 631.98,
    "avgOrders": 0.72
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 87,
    "totalRevenue": 72648.18,
    "totalOrders": 82,
    "avgRevenue": 835.04,
    "avgOrders": 0.94
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 87,
    "totalRevenue": 66007.61,
    "totalOrders": 69,
    "avgRevenue": 758.71,
    "avgOrders": 0.79
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 87,
    "totalRevenue": 74485.89,
    "totalOrders": 78,
    "avgRevenue": 856.16,
    "avgOrders": 0.9
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 87,
    "totalRevenue": 74296.97,
    "totalOrders": 85,
    "avgRevenue": 853.99,
    "avgOrders": 0.98
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 87,
    "totalRevenue": 67322.87,
    "totalOrders": 72,
    "avgRevenue": 773.83,
    "avgOrders": 0.83
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 87,
    "totalRevenue": 47418.78,
    "totalOrders": 49,
    "avgRevenue": 545.04,
    "avgOrders": 0.56
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 87,
    "totalRevenue": 39207.78,
    "totalOrders": 49,
    "avgRevenue": 450.66,
    "avgOrders": 0.56
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 87,
    "totalRevenue": 55797.4,
    "totalOrders": 66,
    "avgRevenue": 641.35,
    "avgOrders": 0.76
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 87,
    "totalRevenue": 52693.09,
    "totalOrders": 64,
    "avgRevenue": 605.67,
    "avgOrders": 0.74
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 87,
    "totalRevenue": 58587.5,
    "totalOrders": 70,
    "avgRevenue": 673.42,
    "avgOrders": 0.8
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 87,
    "totalRevenue": 82926.17,
    "totalOrders": 88,
    "avgRevenue": 953.17,
    "avgOrders": 1.01
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 87,
    "totalRevenue": 72832.18,
    "totalOrders": 85,
    "avgRevenue": 837.15,
    "avgOrders": 0.98
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 87,
    "totalRevenue": 29813.46,
    "totalOrders": 39,
    "avgRevenue": 342.68,
    "avgOrders": 0.45
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 87,
    "totalRevenue": 28128.7,
    "totalOrders": 32,
    "avgRevenue": 323.32,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 88,
    "totalRevenue": 3168.17,
    "totalOrders": 7,
    "avgRevenue": 36,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 88,
    "totalRevenue": 4764.65,
    "totalOrders": 5,
    "avgRevenue": 54.14,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 88,
    "totalRevenue": 4511.6,
    "totalOrders": 6,
    "avgRevenue": 51.27,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 88,
    "totalRevenue": 1026.8,
    "totalOrders": 2,
    "avgRevenue": 11.67,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 88,
    "totalRevenue": 2505.64,
    "totalOrders": 3,
    "avgRevenue": 28.47,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 88,
    "totalRevenue": 16148.94,
    "totalOrders": 15,
    "avgRevenue": 183.51,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 88,
    "totalRevenue": 23749.06,
    "totalOrders": 21,
    "avgRevenue": 269.88,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 88,
    "totalRevenue": 27805.74,
    "totalOrders": 32,
    "avgRevenue": 315.97,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 88,
    "totalRevenue": 47744.06,
    "totalOrders": 49,
    "avgRevenue": 542.55,
    "avgOrders": 0.56
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 88,
    "totalRevenue": 74060.51,
    "totalOrders": 81,
    "avgRevenue": 841.6,
    "avgOrders": 0.92
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 88,
    "totalRevenue": 55963.25,
    "totalOrders": 59,
    "avgRevenue": 635.95,
    "avgOrders": 0.67
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 88,
    "totalRevenue": 61819.43,
    "totalOrders": 55,
    "avgRevenue": 702.49,
    "avgOrders": 0.63
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 88,
    "totalRevenue": 55516,
    "totalOrders": 63,
    "avgRevenue": 630.86,
    "avgOrders": 0.72
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 88,
    "totalRevenue": 67446.65,
    "totalOrders": 66,
    "avgRevenue": 766.44,
    "avgOrders": 0.75
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 88,
    "totalRevenue": 50451.21,
    "totalOrders": 56,
    "avgRevenue": 573.31,
    "avgOrders": 0.64
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 88,
    "totalRevenue": 36719.03,
    "totalOrders": 40,
    "avgRevenue": 417.26,
    "avgOrders": 0.45
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 88,
    "totalRevenue": 45009.94,
    "totalOrders": 50,
    "avgRevenue": 511.48,
    "avgOrders": 0.57
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 88,
    "totalRevenue": 50571.82,
    "totalOrders": 60,
    "avgRevenue": 574.68,
    "avgOrders": 0.68
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 88,
    "totalRevenue": 46848.06,
    "totalOrders": 60,
    "avgRevenue": 532.36,
    "avgOrders": 0.68
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 88,
    "totalRevenue": 46656.46,
    "totalOrders": 60,
    "avgRevenue": 530.19,
    "avgOrders": 0.68
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 88,
    "totalRevenue": 55506.04,
    "totalOrders": 62,
    "avgRevenue": 630.75,
    "avgOrders": 0.7
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 88,
    "totalRevenue": 55085.6,
    "totalOrders": 71,
    "avgRevenue": 625.97,
    "avgOrders": 0.81
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 88,
    "totalRevenue": 43991.66,
    "totalOrders": 47,
    "avgRevenue": 499.91,
    "avgOrders": 0.53
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 88,
    "totalRevenue": 29959.45,
    "totalOrders": 22,
    "avgRevenue": 340.45,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 87,
    "totalRevenue": 7683.09,
    "totalOrders": 10,
    "avgRevenue": 88.31,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 87,
    "totalRevenue": 5692.14,
    "totalOrders": 5,
    "avgRevenue": 65.43,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 87,
    "totalRevenue": 6035.88,
    "totalOrders": 6,
    "avgRevenue": 69.38,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 87,
    "totalRevenue": 8604.63,
    "totalOrders": 4,
    "avgRevenue": 98.9,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 87,
    "totalRevenue": 5558.3,
    "totalOrders": 6,
    "avgRevenue": 63.89,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 87,
    "totalRevenue": 4954.13,
    "totalOrders": 8,
    "avgRevenue": 56.94,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 87,
    "totalRevenue": 16547.51,
    "totalOrders": 23,
    "avgRevenue": 190.2,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 87,
    "totalRevenue": 40327.98,
    "totalOrders": 38,
    "avgRevenue": 463.54,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 87,
    "totalRevenue": 51070.32,
    "totalOrders": 66,
    "avgRevenue": 587.02,
    "avgOrders": 0.76
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 87,
    "totalRevenue": 42234.47,
    "totalOrders": 54,
    "avgRevenue": 485.45,
    "avgOrders": 0.62
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 87,
    "totalRevenue": 52159.69,
    "totalOrders": 59,
    "avgRevenue": 599.54,
    "avgOrders": 0.68
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 87,
    "totalRevenue": 52081.8,
    "totalOrders": 55,
    "avgRevenue": 598.64,
    "avgOrders": 0.63
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 87,
    "totalRevenue": 52828.62,
    "totalOrders": 59,
    "avgRevenue": 607.23,
    "avgOrders": 0.68
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 87,
    "totalRevenue": 55317.73,
    "totalOrders": 56,
    "avgRevenue": 635.84,
    "avgOrders": 0.64
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 87,
    "totalRevenue": 44784,
    "totalOrders": 55,
    "avgRevenue": 514.76,
    "avgOrders": 0.63
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 87,
    "totalRevenue": 46258.98,
    "totalOrders": 50,
    "avgRevenue": 531.71,
    "avgOrders": 0.57
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 87,
    "totalRevenue": 34870.74,
    "totalOrders": 46,
    "avgRevenue": 400.81,
    "avgOrders": 0.53
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 87,
    "totalRevenue": 38652.23,
    "totalOrders": 43,
    "avgRevenue": 444.28,
    "avgOrders": 0.49
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 87,
    "totalRevenue": 33233.33,
    "totalOrders": 37,
    "avgRevenue": 381.99,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 87,
    "totalRevenue": 52992.56,
    "totalOrders": 68,
    "avgRevenue": 609.11,
    "avgOrders": 0.78
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 87,
    "totalRevenue": 53277.41,
    "totalOrders": 64,
    "avgRevenue": 612.38,
    "avgOrders": 0.74
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 87,
    "totalRevenue": 59853.46,
    "totalOrders": 67,
    "avgRevenue": 687.97,
    "avgOrders": 0.77
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 87,
    "totalRevenue": 27932.11,
    "totalOrders": 37,
    "avgRevenue": 321.06,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 87,
    "totalRevenue": 24039.87,
    "totalOrders": 26,
    "avgRevenue": 276.32,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 87,
    "totalRevenue": 6269.5,
    "totalOrders": 7,
    "avgRevenue": 72.06,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 87,
    "totalRevenue": 3787.87,
    "totalOrders": 5,
    "avgRevenue": 43.54,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 87,
    "totalRevenue": 562.68,
    "totalOrders": 2,
    "avgRevenue": 6.47,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 87,
    "totalRevenue": 1875.89,
    "totalOrders": 3,
    "avgRevenue": 21.56,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 87,
    "totalRevenue": 1597.32,
    "totalOrders": 3,
    "avgRevenue": 18.36,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 87,
    "totalRevenue": 4497.7,
    "totalOrders": 5,
    "avgRevenue": 51.7,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 87,
    "totalRevenue": 16603.54,
    "totalOrders": 17,
    "avgRevenue": 190.85,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 87,
    "totalRevenue": 27869.74,
    "totalOrders": 36,
    "avgRevenue": 320.34,
    "avgOrders": 0.41
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 87,
    "totalRevenue": 35177.07,
    "totalOrders": 40,
    "avgRevenue": 404.33,
    "avgOrders": 0.46
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 87,
    "totalRevenue": 42370.05,
    "totalOrders": 52,
    "avgRevenue": 487.01,
    "avgOrders": 0.6
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 87,
    "totalRevenue": 59658.78,
    "totalOrders": 61,
    "avgRevenue": 685.73,
    "avgOrders": 0.7
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 87,
    "totalRevenue": 52392.39,
    "totalOrders": 52,
    "avgRevenue": 602.21,
    "avgOrders": 0.6
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 87,
    "totalRevenue": 42872.5,
    "totalOrders": 45,
    "avgRevenue": 492.79,
    "avgOrders": 0.52
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 87,
    "totalRevenue": 66564.55,
    "totalOrders": 71,
    "avgRevenue": 765.11,
    "avgOrders": 0.82
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 87,
    "totalRevenue": 41508.71,
    "totalOrders": 44,
    "avgRevenue": 477.11,
    "avgOrders": 0.51
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 87,
    "totalRevenue": 42078.97,
    "totalOrders": 49,
    "avgRevenue": 483.67,
    "avgOrders": 0.56
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 87,
    "totalRevenue": 39657.28,
    "totalOrders": 47,
    "avgRevenue": 455.83,
    "avgOrders": 0.54
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 87,
    "totalRevenue": 52754.34,
    "totalOrders": 54,
    "avgRevenue": 606.37,
    "avgOrders": 0.62
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 87,
    "totalRevenue": 43383.87,
    "totalOrders": 45,
    "avgRevenue": 498.67,
    "avgOrders": 0.52
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 87,
    "totalRevenue": 50364.47,
    "totalOrders": 60,
    "avgRevenue": 578.9,
    "avgOrders": 0.69
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 87,
    "totalRevenue": 39596.12,
    "totalOrders": 50,
    "avgRevenue": 455.13,
    "avgOrders": 0.57
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 87,
    "totalRevenue": 47939.48,
    "totalOrders": 51,
    "avgRevenue": 551.03,
    "avgOrders": 0.59
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 87,
    "totalRevenue": 21626.16,
    "totalOrders": 27,
    "avgRevenue": 248.58,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 87,
    "totalRevenue": 11916.27,
    "totalOrders": 13,
    "avgRevenue": 136.97,
    "avgOrders": 0.15
  }
];
