// Auto-generated by scripts/updateData.js — last update: 2026-06-09
// SK: hourly purchase behaviour (EUR), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = neděle … 6 = sobota
  hour:         number;  // 0–23
  dayCount:     number;  // počet dnů s daným dnem v týdnu v datasetu
  totalRevenue: number;  // celkové tržby bez DPH za (dow, hour)
  totalOrders:  number;  // celkový počet objednávek za (dow, hour)
  avgRevenue:   number;  // průměrné tržby bez DPH / den
  avgOrders:    number;  // průměrný počet objednávek / den
}

export const hourlyDataSK: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 19,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 19,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 19,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 19,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 19,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 19,
    "totalRevenue": 47.94,
    "totalOrders": 1,
    "avgRevenue": 2.52,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 19,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 19,
    "totalRevenue": 7.5,
    "totalOrders": 1,
    "avgRevenue": 0.39,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 19,
    "totalRevenue": 71.09,
    "totalOrders": 2,
    "avgRevenue": 3.74,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 19,
    "totalRevenue": 140.22,
    "totalOrders": 4,
    "avgRevenue": 7.38,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 19,
    "totalRevenue": 210.19,
    "totalOrders": 3,
    "avgRevenue": 11.06,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 19,
    "totalRevenue": 16.49,
    "totalOrders": 1,
    "avgRevenue": 0.87,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 19,
    "totalRevenue": 117.62,
    "totalOrders": 4,
    "avgRevenue": 6.19,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 19,
    "totalRevenue": 212.11,
    "totalOrders": 4,
    "avgRevenue": 11.16,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 19,
    "totalRevenue": 140.19,
    "totalOrders": 3,
    "avgRevenue": 7.38,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 19,
    "totalRevenue": 196.76,
    "totalOrders": 5,
    "avgRevenue": 10.36,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 19,
    "totalRevenue": 214.5,
    "totalOrders": 5,
    "avgRevenue": 11.29,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 19,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 19,
    "totalRevenue": 132.35,
    "totalOrders": 4,
    "avgRevenue": 6.97,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 19,
    "totalRevenue": 28.38,
    "totalOrders": 1,
    "avgRevenue": 1.49,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 19,
    "totalRevenue": 230.48,
    "totalOrders": 7,
    "avgRevenue": 12.13,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 19,
    "totalRevenue": 141,
    "totalOrders": 4,
    "avgRevenue": 7.42,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 19,
    "totalRevenue": 94.77,
    "totalOrders": 2,
    "avgRevenue": 4.99,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 19,
    "totalRevenue": 75.98,
    "totalOrders": 2,
    "avgRevenue": 4,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 20,
    "totalRevenue": 28.88,
    "totalOrders": 1,
    "avgRevenue": 1.44,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 20,
    "totalRevenue": 44.8,
    "totalOrders": 1,
    "avgRevenue": 2.24,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 20,
    "totalRevenue": 13.71,
    "totalOrders": 1,
    "avgRevenue": 0.69,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 20,
    "totalRevenue": 78.14,
    "totalOrders": 1,
    "avgRevenue": 3.91,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 20,
    "totalRevenue": 135.07,
    "totalOrders": 3,
    "avgRevenue": 6.75,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 20,
    "totalRevenue": 121.57,
    "totalOrders": 4,
    "avgRevenue": 6.08,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 20,
    "totalRevenue": 226.79,
    "totalOrders": 5,
    "avgRevenue": 11.34,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 20,
    "totalRevenue": 130.98,
    "totalOrders": 5,
    "avgRevenue": 6.55,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 20,
    "totalRevenue": 312.62,
    "totalOrders": 7,
    "avgRevenue": 15.63,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 20,
    "totalRevenue": 116.44,
    "totalOrders": 2,
    "avgRevenue": 5.82,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 20,
    "totalRevenue": 89.87,
    "totalOrders": 3,
    "avgRevenue": 4.49,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 20,
    "totalRevenue": 87.41,
    "totalOrders": 2,
    "avgRevenue": 4.37,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 20,
    "totalRevenue": 153.6,
    "totalOrders": 5,
    "avgRevenue": 7.68,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 20,
    "totalRevenue": 26.81,
    "totalOrders": 1,
    "avgRevenue": 1.34,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 20,
    "totalRevenue": 222.84,
    "totalOrders": 5,
    "avgRevenue": 11.14,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 20,
    "totalRevenue": 389.17,
    "totalOrders": 5,
    "avgRevenue": 19.46,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 20,
    "totalRevenue": 113.75,
    "totalOrders": 2,
    "avgRevenue": 5.69,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 20,
    "totalRevenue": 156.39,
    "totalOrders": 4,
    "avgRevenue": 7.82,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 20,
    "totalRevenue": 135.48,
    "totalOrders": 4,
    "avgRevenue": 6.77,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 20,
    "totalRevenue": 79.11,
    "totalOrders": 2,
    "avgRevenue": 3.96,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 20,
    "totalRevenue": 166.64,
    "totalOrders": 5,
    "avgRevenue": 8.33,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 20,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 20,
    "totalRevenue": 211.17,
    "totalOrders": 6,
    "avgRevenue": 10.56,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 20,
    "totalRevenue": 70.79,
    "totalOrders": 2,
    "avgRevenue": 3.54,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 20,
    "totalRevenue": 85.08,
    "totalOrders": 3,
    "avgRevenue": 4.25,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 20,
    "totalRevenue": 93.33,
    "totalOrders": 4,
    "avgRevenue": 4.67,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 20,
    "totalRevenue": 169.9,
    "totalOrders": 3,
    "avgRevenue": 8.49,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 20,
    "totalRevenue": 148.68,
    "totalOrders": 3,
    "avgRevenue": 7.43,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 20,
    "totalRevenue": 31.17,
    "totalOrders": 1,
    "avgRevenue": 1.56,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 20,
    "totalRevenue": 254.21,
    "totalOrders": 6,
    "avgRevenue": 12.71,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 20,
    "totalRevenue": 151.53,
    "totalOrders": 4,
    "avgRevenue": 7.58,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 20,
    "totalRevenue": 73.18,
    "totalOrders": 3,
    "avgRevenue": 3.66,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 20,
    "totalRevenue": 109.31,
    "totalOrders": 3,
    "avgRevenue": 5.47,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 20,
    "totalRevenue": 119.22,
    "totalOrders": 2,
    "avgRevenue": 5.96,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 18,
    "totalRevenue": 182.56,
    "totalOrders": 3,
    "avgRevenue": 10.14,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 18,
    "totalRevenue": 89.71,
    "totalOrders": 2,
    "avgRevenue": 4.98,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 18,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 18,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 18,
    "totalRevenue": 29.6,
    "totalOrders": 1,
    "avgRevenue": 1.64,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 18,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 18,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 18,
    "totalRevenue": 64.95,
    "totalOrders": 1,
    "avgRevenue": 3.61,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 18,
    "totalRevenue": 26.39,
    "totalOrders": 1,
    "avgRevenue": 1.47,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 18,
    "totalRevenue": 569.2,
    "totalOrders": 2,
    "avgRevenue": 31.62,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 18,
    "totalRevenue": 195.56,
    "totalOrders": 5,
    "avgRevenue": 10.86,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 18,
    "totalRevenue": 39.47,
    "totalOrders": 2,
    "avgRevenue": 2.19,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 18,
    "totalRevenue": 104.15,
    "totalOrders": 4,
    "avgRevenue": 5.79,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 18,
    "totalRevenue": 288.97,
    "totalOrders": 5,
    "avgRevenue": 16.05,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 18,
    "totalRevenue": 649.07,
    "totalOrders": 5,
    "avgRevenue": 36.06,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 18,
    "totalRevenue": 88.21,
    "totalOrders": 3,
    "avgRevenue": 4.9,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 18,
    "totalRevenue": 125.11,
    "totalOrders": 5,
    "avgRevenue": 6.95,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 18,
    "totalRevenue": 129.94,
    "totalOrders": 3,
    "avgRevenue": 7.22,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 18,
    "totalRevenue": 394,
    "totalOrders": 7,
    "avgRevenue": 21.89,
    "avgOrders": 0.39
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 18,
    "totalRevenue": 149.45,
    "totalOrders": 5,
    "avgRevenue": 8.3,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 18,
    "totalRevenue": 133.05,
    "totalOrders": 3,
    "avgRevenue": 7.39,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 18,
    "totalRevenue": 125.88,
    "totalOrders": 5,
    "avgRevenue": 6.99,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 18,
    "totalRevenue": 234.32,
    "totalOrders": 4,
    "avgRevenue": 13.02,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 18,
    "totalRevenue": 80.85,
    "totalOrders": 3,
    "avgRevenue": 4.49,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 17,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 17,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 17,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 17,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 17,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 17,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 17,
    "totalRevenue": 69.23,
    "totalOrders": 2,
    "avgRevenue": 4.07,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 17,
    "totalRevenue": 39.49,
    "totalOrders": 1,
    "avgRevenue": 2.32,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 17,
    "totalRevenue": 123.24,
    "totalOrders": 4,
    "avgRevenue": 7.25,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 17,
    "totalRevenue": 80.98,
    "totalOrders": 1,
    "avgRevenue": 4.76,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 17,
    "totalRevenue": 149.62,
    "totalOrders": 3,
    "avgRevenue": 8.8,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 17,
    "totalRevenue": 265.8,
    "totalOrders": 6,
    "avgRevenue": 15.64,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 17,
    "totalRevenue": 185.27,
    "totalOrders": 4,
    "avgRevenue": 10.9,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 17,
    "totalRevenue": 106.68,
    "totalOrders": 2,
    "avgRevenue": 6.28,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 17,
    "totalRevenue": 48.42,
    "totalOrders": 2,
    "avgRevenue": 2.85,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 17,
    "totalRevenue": 172.82,
    "totalOrders": 3,
    "avgRevenue": 10.17,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 17,
    "totalRevenue": 122.96,
    "totalOrders": 4,
    "avgRevenue": 7.23,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 17,
    "totalRevenue": 89.22,
    "totalOrders": 1,
    "avgRevenue": 5.25,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 17,
    "totalRevenue": 145.72,
    "totalOrders": 5,
    "avgRevenue": 8.57,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 17,
    "totalRevenue": 111.09,
    "totalOrders": 4,
    "avgRevenue": 6.53,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 17,
    "totalRevenue": 140.57,
    "totalOrders": 4,
    "avgRevenue": 8.27,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 17,
    "totalRevenue": 141.08,
    "totalOrders": 4,
    "avgRevenue": 8.3,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 17,
    "totalRevenue": 72.21,
    "totalOrders": 2,
    "avgRevenue": 4.25,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 17,
    "totalRevenue": 47.22,
    "totalOrders": 2,
    "avgRevenue": 2.78,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 19,
    "totalRevenue": 10.8,
    "totalOrders": 1,
    "avgRevenue": 0.57,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 19,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 19,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 19,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 19,
    "totalRevenue": 54.85,
    "totalOrders": 1,
    "avgRevenue": 2.89,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 19,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 19,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 19,
    "totalRevenue": 64.99,
    "totalOrders": 1,
    "avgRevenue": 3.42,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 19,
    "totalRevenue": 159.36,
    "totalOrders": 4,
    "avgRevenue": 8.39,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 19,
    "totalRevenue": 149.04,
    "totalOrders": 4,
    "avgRevenue": 7.84,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 19,
    "totalRevenue": 38.24,
    "totalOrders": 2,
    "avgRevenue": 2.01,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 19,
    "totalRevenue": 53.65,
    "totalOrders": 2,
    "avgRevenue": 2.82,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 19,
    "totalRevenue": 194.76,
    "totalOrders": 4,
    "avgRevenue": 10.25,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 19,
    "totalRevenue": 138.56,
    "totalOrders": 4,
    "avgRevenue": 7.29,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 19,
    "totalRevenue": 74.76,
    "totalOrders": 2,
    "avgRevenue": 3.93,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 19,
    "totalRevenue": 99.17,
    "totalOrders": 2,
    "avgRevenue": 5.22,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 19,
    "totalRevenue": 256.86,
    "totalOrders": 3,
    "avgRevenue": 13.52,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 19,
    "totalRevenue": 51.48,
    "totalOrders": 3,
    "avgRevenue": 2.71,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 19,
    "totalRevenue": 169.2,
    "totalOrders": 4,
    "avgRevenue": 8.91,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 19,
    "totalRevenue": 83.91,
    "totalOrders": 2,
    "avgRevenue": 4.42,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 19,
    "totalRevenue": 110.47,
    "totalOrders": 3,
    "avgRevenue": 5.81,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 19,
    "totalRevenue": 201.86,
    "totalOrders": 5,
    "avgRevenue": 10.62,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 19,
    "totalRevenue": 236.55,
    "totalOrders": 4,
    "avgRevenue": 12.45,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 19,
    "totalRevenue": 75.89,
    "totalOrders": 2,
    "avgRevenue": 3.99,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 21,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 21,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 21,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 21,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 21,
    "totalRevenue": 57.66,
    "totalOrders": 1,
    "avgRevenue": 2.75,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 21,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 21,
    "totalRevenue": 55.6,
    "totalOrders": 1,
    "avgRevenue": 2.65,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 21,
    "totalRevenue": 52.12,
    "totalOrders": 1,
    "avgRevenue": 2.48,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 21,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 21,
    "totalRevenue": 144.32,
    "totalOrders": 3,
    "avgRevenue": 6.87,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 21,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 21,
    "totalRevenue": 193.53,
    "totalOrders": 3,
    "avgRevenue": 9.22,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 21,
    "totalRevenue": 111.5,
    "totalOrders": 3,
    "avgRevenue": 5.31,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 21,
    "totalRevenue": 133.91,
    "totalOrders": 4,
    "avgRevenue": 6.38,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 21,
    "totalRevenue": 173.3,
    "totalOrders": 5,
    "avgRevenue": 8.25,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 21,
    "totalRevenue": 94.94,
    "totalOrders": 3,
    "avgRevenue": 4.52,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 21,
    "totalRevenue": 72.57,
    "totalOrders": 3,
    "avgRevenue": 3.46,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 21,
    "totalRevenue": 111.21,
    "totalOrders": 3,
    "avgRevenue": 5.3,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 21,
    "totalRevenue": 18.45,
    "totalOrders": 1,
    "avgRevenue": 0.88,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 21,
    "totalRevenue": 241.71,
    "totalOrders": 4,
    "avgRevenue": 11.51,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 21,
    "totalRevenue": 208.31,
    "totalOrders": 5,
    "avgRevenue": 9.92,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 21,
    "totalRevenue": 187.13,
    "totalOrders": 4,
    "avgRevenue": 8.91,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 21,
    "totalRevenue": 121.98,
    "totalOrders": 3,
    "avgRevenue": 5.81,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 21,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  }
];
