// Auto-generated by scripts/updateData.js — last update: 2026-04-05
// SK: daily margin data (EUR). purchaseCost = nákupní cena, revenue = tržby bez DPH. Spojeno přes kód objednávky z orders exportu.

export interface MarginDailyRecord {
  date: string;        // ISO "2025-05-25"
  purchaseCost: number; // nákupní cena (součet za den)
  revenue: number;      // tržby bez DPH (součet za den)
}

export const marginDataSK: MarginDailyRecord[] = [
  {
    "date": "2025-12-09",
    "purchaseCost": 74.84,
    "revenue": 151.18
  },
  {
    "date": "2025-12-10",
    "purchaseCost": 204.58,
    "revenue": 219.88
  },
  {
    "date": "2025-12-11",
    "purchaseCost": 48.94,
    "revenue": 65.85
  },
  {
    "date": "2025-12-12",
    "purchaseCost": 16.1,
    "revenue": 27.58
  },
  {
    "date": "2025-12-13",
    "purchaseCost": 32.16,
    "revenue": 51.99
  },
  {
    "date": "2025-12-14",
    "purchaseCost": 35.21,
    "revenue": 50.51
  },
  {
    "date": "2025-12-15",
    "purchaseCost": 67.96,
    "revenue": 60.47
  },
  {
    "date": "2025-12-16",
    "purchaseCost": 17.36,
    "revenue": 32.45
  },
  {
    "date": "2025-12-17",
    "purchaseCost": 60.73,
    "revenue": 103.19
  },
  {
    "date": "2025-12-18",
    "purchaseCost": 116.07,
    "revenue": 150.79
  },
  {
    "date": "2026-01-04",
    "purchaseCost": 16.35,
    "revenue": 27.14
  },
  {
    "date": "2026-01-05",
    "purchaseCost": 120.8,
    "revenue": 181.1
  },
  {
    "date": "2026-01-06",
    "purchaseCost": 105.57,
    "revenue": 163.59
  },
  {
    "date": "2026-01-07",
    "purchaseCost": 238.06,
    "revenue": 345.03
  },
  {
    "date": "2026-01-08",
    "purchaseCost": 151.52,
    "revenue": 276.23
  },
  {
    "date": "2026-01-09",
    "purchaseCost": 62.51,
    "revenue": 93.73
  },
  {
    "date": "2026-01-10",
    "purchaseCost": 119.1,
    "revenue": 175.92
  },
  {
    "date": "2026-01-11",
    "purchaseCost": 114.22,
    "revenue": 189
  },
  {
    "date": "2026-01-12",
    "purchaseCost": 113.54,
    "revenue": 128.39
  },
  {
    "date": "2026-01-13",
    "purchaseCost": 140.32,
    "revenue": 238.04
  },
  {
    "date": "2026-01-14",
    "purchaseCost": 196.56,
    "revenue": 338.94
  },
  {
    "date": "2026-01-15",
    "purchaseCost": 39.82,
    "revenue": 64.34
  },
  {
    "date": "2026-01-16",
    "purchaseCost": 135.37,
    "revenue": 215.68
  },
  {
    "date": "2026-01-17",
    "purchaseCost": 64.68,
    "revenue": 101.43
  },
  {
    "date": "2026-01-18",
    "purchaseCost": 67.94,
    "revenue": 111.99
  },
  {
    "date": "2026-01-19",
    "purchaseCost": 54.85,
    "revenue": 95.5
  },
  {
    "date": "2026-01-20",
    "purchaseCost": 52.61,
    "revenue": 86.62
  },
  {
    "date": "2026-01-21",
    "purchaseCost": 50.32,
    "revenue": 82.06
  },
  {
    "date": "2026-01-23",
    "purchaseCost": 61.48,
    "revenue": 98.91
  },
  {
    "date": "2026-01-24",
    "purchaseCost": 22.63,
    "revenue": 34.96
  },
  {
    "date": "2026-01-25",
    "purchaseCost": 150.34,
    "revenue": 212.64
  },
  {
    "date": "2026-01-26",
    "purchaseCost": 36.54,
    "revenue": 75.87
  },
  {
    "date": "2026-01-30",
    "purchaseCost": 16.01,
    "revenue": 32
  },
  {
    "date": "2026-01-31",
    "purchaseCost": 17.06,
    "revenue": 33.1
  },
  {
    "date": "2026-02-02",
    "purchaseCost": 49.08,
    "revenue": 73.44
  },
  {
    "date": "2026-02-03",
    "purchaseCost": 34.25,
    "revenue": 61.5
  },
  {
    "date": "2026-02-04",
    "purchaseCost": 68.53,
    "revenue": 118.62
  },
  {
    "date": "2026-02-05",
    "purchaseCost": 124.53,
    "revenue": 207.2
  },
  {
    "date": "2026-02-06",
    "purchaseCost": 90.33,
    "revenue": 152.34
  },
  {
    "date": "2026-02-07",
    "purchaseCost": 72.07,
    "revenue": 123.6
  },
  {
    "date": "2026-02-08",
    "purchaseCost": 63.1,
    "revenue": 103.87
  },
  {
    "date": "2026-02-09",
    "purchaseCost": 56.43,
    "revenue": 93.07
  },
  {
    "date": "2026-02-10",
    "purchaseCost": 72.83,
    "revenue": 128.26
  },
  {
    "date": "2026-02-11",
    "purchaseCost": 183.24,
    "revenue": 289.76
  },
  {
    "date": "2026-02-12",
    "purchaseCost": 22.69,
    "revenue": 39.16
  },
  {
    "date": "2026-02-15",
    "purchaseCost": 24.99,
    "revenue": 42.76
  },
  {
    "date": "2026-02-16",
    "purchaseCost": 20.06,
    "revenue": 21.44
  },
  {
    "date": "2026-02-17",
    "purchaseCost": 32.49,
    "revenue": 56.8
  },
  {
    "date": "2026-02-18",
    "purchaseCost": 204.4,
    "revenue": 320.35
  },
  {
    "date": "2026-02-19",
    "purchaseCost": 39.18,
    "revenue": 68.3
  },
  {
    "date": "2026-02-20",
    "purchaseCost": 40.94,
    "revenue": 73.82
  },
  {
    "date": "2026-02-21",
    "purchaseCost": 4.8,
    "revenue": 15.85
  },
  {
    "date": "2026-02-24",
    "purchaseCost": 92.18,
    "revenue": 166.61
  },
  {
    "date": "2026-02-25",
    "purchaseCost": 82.26,
    "revenue": 152.95
  },
  {
    "date": "2026-02-26",
    "purchaseCost": 119.4,
    "revenue": 224.62
  },
  {
    "date": "2026-02-27",
    "purchaseCost": 188.12,
    "revenue": 306.26
  },
  {
    "date": "2026-02-28",
    "purchaseCost": 53.74,
    "revenue": 97.67
  },
  {
    "date": "2026-03-01",
    "purchaseCost": 35.45,
    "revenue": 55.2
  },
  {
    "date": "2026-03-02",
    "purchaseCost": 130.87,
    "revenue": 237.16
  },
  {
    "date": "2026-03-03",
    "purchaseCost": 118.55,
    "revenue": 155.08
  },
  {
    "date": "2026-03-04",
    "purchaseCost": 15.5,
    "revenue": 29.6
  },
  {
    "date": "2026-03-05",
    "purchaseCost": 95.33,
    "revenue": 163.27
  },
  {
    "date": "2026-03-06",
    "purchaseCost": 69.13,
    "revenue": 116.22
  },
  {
    "date": "2026-03-07",
    "purchaseCost": 23.76,
    "revenue": 43.8
  },
  {
    "date": "2026-03-08",
    "purchaseCost": 108.23,
    "revenue": 180.89
  },
  {
    "date": "2026-03-09",
    "purchaseCost": 69.64,
    "revenue": 133.15
  },
  {
    "date": "2026-03-12",
    "purchaseCost": 45.69,
    "revenue": 59.26
  },
  {
    "date": "2026-03-13",
    "purchaseCost": 180.17,
    "revenue": 304.06
  },
  {
    "date": "2026-03-14",
    "purchaseCost": 27.78,
    "revenue": 52.12
  },
  {
    "date": "2026-03-15",
    "purchaseCost": 102.62,
    "revenue": 182.45
  },
  {
    "date": "2026-03-16",
    "purchaseCost": 243.45,
    "revenue": 395.22
  },
  {
    "date": "2026-03-17",
    "purchaseCost": 67.7,
    "revenue": 83.06
  },
  {
    "date": "2026-03-18",
    "purchaseCost": 255.02,
    "revenue": 513.36
  },
  {
    "date": "2026-03-19",
    "purchaseCost": 91.56,
    "revenue": 135.04
  },
  {
    "date": "2026-03-20",
    "purchaseCost": 119.82,
    "revenue": 216.15
  },
  {
    "date": "2026-03-21",
    "purchaseCost": 131.77,
    "revenue": 197.63
  },
  {
    "date": "2026-03-22",
    "purchaseCost": 117.97,
    "revenue": 177.06
  },
  {
    "date": "2026-03-23",
    "purchaseCost": 47.32,
    "revenue": 82.26
  },
  {
    "date": "2026-03-24",
    "purchaseCost": 90.4,
    "revenue": 165.61
  },
  {
    "date": "2026-03-25",
    "purchaseCost": 213.01,
    "revenue": 355.29
  },
  {
    "date": "2026-03-26",
    "purchaseCost": 200.78,
    "revenue": 332.63
  },
  {
    "date": "2026-03-27",
    "purchaseCost": 39.36,
    "revenue": 83.11
  },
  {
    "date": "2026-03-28",
    "purchaseCost": 105.37,
    "revenue": 166.69
  },
  {
    "date": "2026-03-29",
    "purchaseCost": 46.43,
    "revenue": 79.07
  },
  {
    "date": "2026-03-31",
    "purchaseCost": 61.18,
    "revenue": 103.32
  },
  {
    "date": "2026-04-01",
    "purchaseCost": 31.37,
    "revenue": 52.33
  },
  {
    "date": "2026-04-03",
    "purchaseCost": 24.16,
    "revenue": 45.78
  },
  {
    "date": "2026-04-04",
    "purchaseCost": 24.18,
    "revenue": 52.28
  }
];
