// Auto-generated by scripts/updateData.js — last update: 2026-04-12
// SK: per-customer retention data (EUR)

export const retentionDataSK: { dates: string[]; revenues: number[]; revsVat: number[] }[] = [
  {
    "dates": [
      "2025-12-09"
    ],
    "revenues": [
      27.52
    ],
    "revsVat": [
      30.82
    ]
  },
  {
    "dates": [
      "2025-12-09",
      "2026-01-11"
    ],
    "revenues": [
      18.17,
      14.29
    ],
    "revsVat": [
      20.35,
      16.01
    ]
  },
  {
    "dates": [
      "2025-12-09"
    ],
    "revenues": [
      64.16
    ],
    "revsVat": [
      71.91
    ]
  },
  {
    "dates": [
      "2025-12-10"
    ],
    "revenues": [
      130.87
    ],
    "revsVat": [
      146.58
    ]
  },
  {
    "dates": [
      "2025-12-10"
    ],
    "revenues": [
      26.39
    ],
    "revsVat": [
      29.56
    ]
  },
  {
    "dates": [
      "2025-12-10"
    ],
    "revenues": [
      12.54
    ],
    "revsVat": [
      14.05
    ]
  },
  {
    "dates": [
      "2025-12-10"
    ],
    "revenues": [
      40.69
    ],
    "revsVat": [
      45.57
    ]
  },
  {
    "dates": [
      "2025-12-11"
    ],
    "revenues": [
      14.5
    ],
    "revsVat": [
      16.24
    ]
  },
  {
    "dates": [
      "2025-12-11"
    ],
    "revenues": [
      48.22
    ],
    "revsVat": [
      54.02
    ]
  },
  {
    "dates": [
      "2025-12-12"
    ],
    "revenues": [
      24.45
    ],
    "revsVat": [
      27.38
    ]
  },
  {
    "dates": [
      "2025-12-13"
    ],
    "revenues": [
      48.86
    ],
    "revsVat": [
      54.72
    ]
  },
  {
    "dates": [
      "2025-12-14"
    ],
    "revenues": [
      50.51
    ],
    "revsVat": [
      56.57
    ]
  },
  {
    "dates": [
      "2025-12-15"
    ],
    "revenues": [
      26.1
    ],
    "revsVat": [
      29.25
    ]
  },
  {
    "dates": [
      "2025-12-15"
    ],
    "revenues": [
      28.11
    ],
    "revsVat": [
      31.48
    ]
  },
  {
    "dates": [
      "2025-12-16",
      "2026-01-07"
    ],
    "revenues": [
      29.32,
      20.9
    ],
    "revsVat": [
      32.84,
      23.41
    ]
  },
  {
    "dates": [
      "2025-12-17"
    ],
    "revenues": [
      25.63
    ],
    "revsVat": [
      28.7
    ]
  },
  {
    "dates": [
      "2025-12-17"
    ],
    "revenues": [
      53.48
    ],
    "revsVat": [
      59.89
    ]
  },
  {
    "dates": [
      "2025-12-17",
      "2026-01-07"
    ],
    "revenues": [
      17.11,
      36.58
    ],
    "revsVat": [
      19.16,
      40.97
    ]
  },
  {
    "dates": [
      "2025-12-18"
    ],
    "revenues": [
      26.33
    ],
    "revsVat": [
      29.48
    ]
  },
  {
    "dates": [
      "2025-12-18",
      "2026-02-27",
      "2026-04-01"
    ],
    "revenues": [
      49.97,
      29.02,
      52.33
    ],
    "revsVat": [
      55.97,
      32.5,
      58.61
    ]
  },
  {
    "dates": [
      "2025-12-18"
    ],
    "revenues": [
      71.36
    ],
    "revsVat": [
      79.93
    ]
  },
  {
    "dates": [
      "2026-01-04",
      "2026-01-08"
    ],
    "revenues": [
      24.01,
      48.99
    ],
    "revsVat": [
      26.89,
      54.85
    ]
  },
  {
    "dates": [
      "2026-01-05"
    ],
    "revenues": [
      13.71
    ],
    "revsVat": [
      15.36
    ]
  },
  {
    "dates": [
      "2026-01-05",
      "2026-03-26"
    ],
    "revenues": [
      58.53,
      80.98
    ],
    "revsVat": [
      65.57,
      90.72
    ]
  },
  {
    "dates": [
      "2026-01-05"
    ],
    "revenues": [
      21.81
    ],
    "revsVat": [
      24.43
    ]
  },
  {
    "dates": [
      "2026-01-05"
    ],
    "revenues": [
      32.13
    ],
    "revsVat": [
      36
    ]
  },
  {
    "dates": [
      "2026-01-05"
    ],
    "revenues": [
      44.82
    ],
    "revsVat": [
      50.21
    ]
  },
  {
    "dates": [
      "2026-01-06"
    ],
    "revenues": [
      32.2
    ],
    "revsVat": [
      36.05
    ]
  },
  {
    "dates": [
      "2026-01-06",
      "2026-02-10"
    ],
    "revenues": [
      13.23,
      25.72
    ],
    "revsVat": [
      14.81,
      28.81
    ]
  },
  {
    "dates": [
      "2026-01-06"
    ],
    "revenues": [
      18.83
    ],
    "revsVat": [
      21.09
    ]
  },
  {
    "dates": [
      "2026-01-06"
    ],
    "revenues": [
      23.12
    ],
    "revsVat": [
      25.9
    ]
  },
  {
    "dates": [
      "2026-01-06"
    ],
    "revenues": [
      22.08
    ],
    "revsVat": [
      24.73
    ]
  },
  {
    "dates": [
      "2026-01-06"
    ],
    "revenues": [
      35.35
    ],
    "revsVat": [
      39.6
    ]
  },
  {
    "dates": [
      "2026-01-07",
      "2026-02-25"
    ],
    "revenues": [
      10.89,
      18.42
    ],
    "revsVat": [
      12.2,
      20.62
    ]
  },
  {
    "dates": [
      "2026-01-07",
      "2026-01-11"
    ],
    "revenues": [
      27.4,
      46.88
    ],
    "revsVat": [
      30.69,
      52.53
    ]
  },
  {
    "dates": [
      "2026-01-07",
      "2026-01-14",
      "2026-03-16"
    ],
    "revenues": [
      49.96,
      37.85,
      54.05
    ],
    "revsVat": [
      55.97,
      42.4,
      60.52
    ]
  },
  {
    "dates": [
      "2026-01-07"
    ],
    "revenues": [
      46.09
    ],
    "revsVat": [
      51.62
    ]
  },
  {
    "dates": [
      "2026-01-07"
    ],
    "revenues": [
      14.27
    ],
    "revsVat": [
      15.98
    ]
  },
  {
    "dates": [
      "2026-01-07"
    ],
    "revenues": [
      32.66
    ],
    "revsVat": [
      36.59
    ]
  },
  {
    "dates": [
      "2026-01-07"
    ],
    "revenues": [
      16.51
    ],
    "revsVat": [
      18.49
    ]
  },
  {
    "dates": [
      "2026-01-07"
    ],
    "revenues": [
      33.26
    ],
    "revsVat": [
      37.26
    ]
  },
  {
    "dates": [
      "2026-01-07"
    ],
    "revenues": [
      27.63
    ],
    "revsVat": [
      30.94
    ]
  },
  {
    "dates": [
      "2026-01-08"
    ],
    "revenues": [
      15.14
    ],
    "revsVat": [
      16.94
    ]
  },
  {
    "dates": [
      "2026-01-08"
    ],
    "revenues": [
      20.24
    ],
    "revsVat": [
      22.67
    ]
  },
  {
    "dates": [
      "2026-01-08",
      "2026-03-09"
    ],
    "revenues": [
      12.19,
      18.92
    ],
    "revsVat": [
      13.65,
      21.19
    ]
  },
  {
    "dates": [
      "2026-01-08"
    ],
    "revenues": [
      24.63
    ],
    "revsVat": [
      27.57
    ]
  },
  {
    "dates": [
      "2026-01-08"
    ],
    "revenues": [
      36.41
    ],
    "revsVat": [
      40.77
    ]
  },
  {
    "dates": [
      "2026-01-08"
    ],
    "revenues": [
      16.45
    ],
    "revsVat": [
      18.43
    ]
  },
  {
    "dates": [
      "2026-01-08"
    ],
    "revenues": [
      23.05
    ],
    "revsVat": [
      25.81
    ]
  },
  {
    "dates": [
      "2026-01-08"
    ],
    "revenues": [
      57.22
    ],
    "revsVat": [
      64.06
    ]
  },
  {
    "dates": [
      "2026-01-09"
    ],
    "revenues": [
      35.9
    ],
    "revsVat": [
      40.2
    ]
  },
  {
    "dates": [
      "2026-01-09"
    ],
    "revenues": [
      54.7
    ],
    "revsVat": [
      61.27
    ]
  },
  {
    "dates": [
      "2026-01-10"
    ],
    "revenues": [
      59.85
    ],
    "revsVat": [
      67.04
    ]
  },
  {
    "dates": [
      "2026-01-10"
    ],
    "revenues": [
      26.15
    ],
    "revsVat": [
      29.29
    ]
  },
  {
    "dates": [
      "2026-01-10"
    ],
    "revenues": [
      25.55
    ],
    "revsVat": [
      28.62
    ]
  },
  {
    "dates": [
      "2026-01-10"
    ],
    "revenues": [
      13.55
    ],
    "revsVat": [
      15.18
    ]
  },
  {
    "dates": [
      "2026-01-10"
    ],
    "revenues": [
      22.83
    ],
    "revsVat": [
      25.57
    ]
  },
  {
    "dates": [
      "2026-01-10"
    ],
    "revenues": [
      12.34
    ],
    "revsVat": [
      13.82
    ]
  },
  {
    "dates": [
      "2026-01-11"
    ],
    "revenues": [
      27.11
    ],
    "revsVat": [
      30.36
    ]
  },
  {
    "dates": [
      "2026-01-11"
    ],
    "revenues": [
      66.37
    ],
    "revsVat": [
      74.35
    ]
  },
  {
    "dates": [
      "2026-01-11"
    ],
    "revenues": [
      24.96
    ],
    "revsVat": [
      27.96
    ]
  },
  {
    "dates": [
      "2026-01-12"
    ],
    "revenues": [
      24.59
    ],
    "revsVat": [
      27.54
    ]
  },
  {
    "dates": [
      "2026-01-12"
    ],
    "revenues": [
      45.51
    ],
    "revsVat": [
      50.98
    ]
  },
  {
    "dates": [
      "2026-01-12"
    ],
    "revenues": [
      55.16
    ],
    "revsVat": [
      61.78
    ]
  },
  {
    "dates": [
      "2026-01-13"
    ],
    "revenues": [
      25.03
    ],
    "revsVat": [
      28.04
    ]
  },
  {
    "dates": [
      "2026-01-13"
    ],
    "revenues": [
      55.85
    ],
    "revsVat": [
      62.57
    ]
  },
  {
    "dates": [
      "2026-01-13"
    ],
    "revenues": [
      62.39
    ],
    "revsVat": [
      69.87
    ]
  },
  {
    "dates": [
      "2026-01-13"
    ],
    "revenues": [
      27.91
    ],
    "revsVat": [
      31.26
    ]
  },
  {
    "dates": [
      "2026-01-13"
    ],
    "revenues": [
      28.6
    ],
    "revsVat": [
      32.04
    ]
  },
  {
    "dates": [
      "2026-01-13"
    ],
    "revenues": [
      25.03
    ],
    "revsVat": [
      28.04
    ]
  },
  {
    "dates": [
      "2026-01-14"
    ],
    "revenues": [
      60.32
    ],
    "revsVat": [
      67.55
    ]
  },
  {
    "dates": [
      "2026-01-14"
    ],
    "revenues": [
      53.79
    ],
    "revsVat": [
      53.79
    ]
  },
  {
    "dates": [
      "2026-01-14",
      "2026-02-24"
    ],
    "revenues": [
      25.95,
      61.33
    ],
    "revsVat": [
      29.06,
      68.69
    ]
  },
  {
    "dates": [
      "2026-01-14"
    ],
    "revenues": [
      80.77
    ],
    "revsVat": [
      90.46
    ]
  },
  {
    "dates": [
      "2026-01-14"
    ],
    "revenues": [
      31.73
    ],
    "revsVat": [
      35.53
    ]
  },
  {
    "dates": [
      "2026-01-14"
    ],
    "revenues": [
      13.61
    ],
    "revsVat": [
      15.24
    ]
  },
  {
    "dates": [
      "2026-01-14"
    ],
    "revenues": [
      15.43
    ],
    "revsVat": [
      17.28
    ]
  },
  {
    "dates": [
      "2026-01-15"
    ],
    "revenues": [
      23.56
    ],
    "revsVat": [
      26.38
    ]
  },
  {
    "dates": [
      "2026-01-15",
      "2026-02-28"
    ],
    "revenues": [
      33.81,
      49.82
    ],
    "revsVat": [
      37.86,
      55.81
    ]
  },
  {
    "dates": [
      "2026-01-16"
    ],
    "revenues": [
      20.1
    ],
    "revsVat": [
      22.52
    ]
  },
  {
    "dates": [
      "2026-01-16"
    ],
    "revenues": [
      25.75
    ],
    "revsVat": [
      28.84
    ]
  },
  {
    "dates": [
      "2026-01-16"
    ],
    "revenues": [
      24.44
    ],
    "revsVat": [
      27.36
    ]
  },
  {
    "dates": [
      "2026-01-16"
    ],
    "revenues": [
      58.65
    ],
    "revsVat": [
      65.67
    ]
  },
  {
    "dates": [
      "2026-01-16"
    ],
    "revenues": [
      24.09
    ],
    "revsVat": [
      26.98
    ]
  },
  {
    "dates": [
      "2026-01-16",
      "2026-03-08"
    ],
    "revenues": [
      49.42,
      51.85
    ],
    "revsVat": [
      55.34,
      58.07
    ]
  },
  {
    "dates": [
      "2026-01-17"
    ],
    "revenues": [
      101.43
    ],
    "revsVat": [
      113.6
    ]
  },
  {
    "dates": [
      "2026-01-18"
    ],
    "revenues": [
      30.55
    ],
    "revsVat": [
      34.22
    ]
  },
  {
    "dates": [
      "2026-01-18"
    ],
    "revenues": [
      46.8
    ],
    "revsVat": [
      52.42
    ]
  },
  {
    "dates": [
      "2026-01-18"
    ],
    "revenues": [
      28.38
    ],
    "revsVat": [
      31.79
    ]
  },
  {
    "dates": [
      "2026-01-19"
    ],
    "revenues": [
      12.47
    ],
    "revsVat": [
      13.97
    ]
  },
  {
    "dates": [
      "2026-01-19"
    ],
    "revenues": [
      29.67
    ],
    "revsVat": [
      33.23
    ]
  },
  {
    "dates": [
      "2026-01-19"
    ],
    "revenues": [
      43.26
    ],
    "revsVat": [
      48.45
    ]
  },
  {
    "dates": [
      "2026-01-20"
    ],
    "revenues": [
      36.77
    ],
    "revsVat": [
      41.19
    ]
  },
  {
    "dates": [
      "2026-01-20",
      "2026-02-08",
      "2026-03-05"
    ],
    "revenues": [
      42.88,
      28.55,
      36.75
    ],
    "revsVat": [
      48.05,
      31.97,
      41.15
    ]
  },
  {
    "dates": [
      "2026-01-21",
      "2026-03-05"
    ],
    "revenues": [
      21.74,
      28.54
    ],
    "revsVat": [
      24.36,
      31.96
    ]
  },
  {
    "dates": [
      "2026-01-21"
    ],
    "revenues": [
      56.48
    ],
    "revsVat": [
      63.29
    ]
  },
  {
    "dates": [
      "2026-01-23"
    ],
    "revenues": [
      38.46
    ],
    "revsVat": [
      43.08
    ]
  },
  {
    "dates": [
      "2026-01-23"
    ],
    "revenues": [
      24.63
    ],
    "revsVat": [
      27.58
    ]
  },
  {
    "dates": [
      "2026-01-23"
    ],
    "revenues": [
      26.43
    ],
    "revsVat": [
      29.6
    ]
  },
  {
    "dates": [
      "2026-01-24"
    ],
    "revenues": [
      31.12
    ],
    "revsVat": [
      34.86
    ]
  },
  {
    "dates": [
      "2026-01-25"
    ],
    "revenues": [
      50.56
    ],
    "revsVat": [
      56.62
    ]
  },
  {
    "dates": [
      "2026-01-25"
    ],
    "revenues": [
      93.58
    ],
    "revsVat": [
      104.81
    ]
  },
  {
    "dates": [
      "2026-01-25"
    ],
    "revenues": [
      43.67
    ],
    "revsVat": [
      48.9
    ]
  },
  {
    "dates": [
      "2026-01-25"
    ],
    "revenues": [
      18.57
    ],
    "revsVat": [
      20.8
    ]
  },
  {
    "dates": [
      "2026-01-26"
    ],
    "revenues": [
      27.66
    ],
    "revsVat": [
      30.98
    ]
  },
  {
    "dates": [
      "2026-01-26"
    ],
    "revenues": [
      41.95
    ],
    "revsVat": [
      46.99
    ]
  },
  {
    "dates": [
      "2026-01-30"
    ],
    "revenues": [
      28.88
    ],
    "revsVat": [
      32.34
    ]
  },
  {
    "dates": [
      "2026-01-31"
    ],
    "revenues": [
      29.98
    ],
    "revsVat": [
      33.59
    ]
  },
  {
    "dates": [
      "2026-02-02"
    ],
    "revenues": [
      44.8
    ],
    "revsVat": [
      50.16
    ]
  },
  {
    "dates": [
      "2026-02-02",
      "2026-03-15"
    ],
    "revenues": [
      22.4,
      30.26
    ],
    "revsVat": [
      25.08,
      33.89
    ]
  },
  {
    "dates": [
      "2026-02-03"
    ],
    "revenues": [
      39.09
    ],
    "revsVat": [
      43.78
    ]
  },
  {
    "dates": [
      "2026-02-03",
      "2026-02-25"
    ],
    "revenues": [
      16.17,
      21.27
    ],
    "revsVat": [
      18.11,
      23.82
    ]
  },
  {
    "dates": [
      "2026-02-04"
    ],
    "revenues": [
      26.35
    ],
    "revsVat": [
      29.52
    ]
  },
  {
    "dates": [
      "2026-02-04",
      "2026-03-27"
    ],
    "revenues": [
      50.28,
      40.88
    ],
    "revsVat": [
      56.31,
      45.78
    ]
  },
  {
    "dates": [
      "2026-02-04",
      "2026-03-19"
    ],
    "revenues": [
      32.63,
      52.76
    ],
    "revsVat": [
      36.55,
      59.09
    ]
  },
  {
    "dates": [
      "2026-02-05"
    ],
    "revenues": [
      29.65
    ],
    "revsVat": [
      33.21
    ]
  },
  {
    "dates": [
      "2026-02-05"
    ],
    "revenues": [
      72.06
    ],
    "revsVat": [
      80.71
    ]
  },
  {
    "dates": [
      "2026-02-05"
    ],
    "revenues": [
      54.69
    ],
    "revsVat": [
      61.25
    ]
  },
  {
    "dates": [
      "2026-02-05",
      "2026-03-02"
    ],
    "revenues": [
      43.84,
      86.65
    ],
    "revsVat": [
      49.1,
      97.06
    ]
  },
  {
    "dates": [
      "2026-02-06"
    ],
    "revenues": [
      40.06
    ],
    "revsVat": [
      44.87
    ]
  },
  {
    "dates": [
      "2026-02-06"
    ],
    "revenues": [
      80.78
    ],
    "revsVat": [
      90.47
    ]
  },
  {
    "dates": [
      "2026-02-06"
    ],
    "revenues": [
      25.26
    ],
    "revsVat": [
      28.3
    ]
  },
  {
    "dates": [
      "2026-02-07"
    ],
    "revenues": [
      13.6
    ],
    "revsVat": [
      15.23
    ]
  },
  {
    "dates": [
      "2026-02-07"
    ],
    "revenues": [
      62.21
    ],
    "revsVat": [
      69.68
    ]
  },
  {
    "dates": [
      "2026-02-07",
      "2026-04-08"
    ],
    "revenues": [
      17.32,
      14.88
    ],
    "revsVat": [
      19.39,
      16.67
    ]
  },
  {
    "dates": [
      "2026-02-07"
    ],
    "revenues": [
      21.11
    ],
    "revsVat": [
      23.64
    ]
  },
  {
    "dates": [
      "2026-02-08"
    ],
    "revenues": [
      29.39
    ],
    "revsVat": [
      32.92
    ]
  },
  {
    "dates": [
      "2026-02-08"
    ],
    "revenues": [
      36.57
    ],
    "revsVat": [
      40.96
    ]
  },
  {
    "dates": [
      "2026-02-09"
    ],
    "revenues": [
      53.9
    ],
    "revsVat": [
      60.36
    ]
  },
  {
    "dates": [
      "2026-02-09"
    ],
    "revenues": [
      36.05
    ],
    "revsVat": [
      40.38
    ]
  },
  {
    "dates": [
      "2026-02-10"
    ],
    "revenues": [
      13.9
    ],
    "revsVat": [
      15.57
    ]
  },
  {
    "dates": [
      "2026-02-10"
    ],
    "revenues": [
      24.85
    ],
    "revsVat": [
      27.83
    ]
  },
  {
    "dates": [
      "2026-02-10"
    ],
    "revenues": [
      54.43
    ],
    "revsVat": [
      60.96
    ]
  },
  {
    "dates": [
      "2026-02-11"
    ],
    "revenues": [
      47.8
    ],
    "revsVat": [
      53.54
    ]
  },
  {
    "dates": [
      "2026-02-11"
    ],
    "revenues": [
      27.16
    ],
    "revsVat": [
      30.42
    ]
  },
  {
    "dates": [
      "2026-02-11"
    ],
    "revenues": [
      121.78
    ],
    "revsVat": [
      136.39
    ]
  },
  {
    "dates": [
      "2026-02-11"
    ],
    "revenues": [
      56.5
    ],
    "revsVat": [
      63.28
    ]
  },
  {
    "dates": [
      "2026-02-11"
    ],
    "revenues": [
      27.16
    ],
    "revsVat": [
      30.42
    ]
  },
  {
    "dates": [
      "2026-02-12"
    ],
    "revenues": [
      35.32
    ],
    "revsVat": [
      39.56
    ]
  },
  {
    "dates": [
      "2026-02-15"
    ],
    "revenues": [
      39.64
    ],
    "revsVat": [
      44.4
    ]
  },
  {
    "dates": [
      "2026-02-16"
    ],
    "revenues": [
      17.6
    ],
    "revsVat": [
      19.71
    ]
  },
  {
    "dates": [
      "2026-02-17"
    ],
    "revenues": [
      56.8
    ],
    "revsVat": [
      63.63
    ]
  },
  {
    "dates": [
      "2026-02-18"
    ],
    "revenues": [
      35.16
    ],
    "revsVat": [
      39.38
    ]
  },
  {
    "dates": [
      "2026-02-18"
    ],
    "revenues": [
      61.6
    ],
    "revsVat": [
      69
    ]
  },
  {
    "dates": [
      "2026-02-18"
    ],
    "revenues": [
      48.19
    ],
    "revsVat": [
      53.97
    ]
  },
  {
    "dates": [
      "2026-02-18",
      "2026-03-16"
    ],
    "revenues": [
      167.72,
      78.14
    ],
    "revsVat": [
      167.72,
      78.14
    ]
  },
  {
    "dates": [
      "2026-02-19"
    ],
    "revenues": [
      68.3
    ],
    "revsVat": [
      76.5
    ]
  },
  {
    "dates": [
      "2026-02-20"
    ],
    "revenues": [
      44.82
    ],
    "revsVat": [
      50.2
    ]
  },
  {
    "dates": [
      "2026-02-20"
    ],
    "revenues": [
      22.76
    ],
    "revsVat": [
      25.49
    ]
  },
  {
    "dates": [
      "2026-02-21"
    ],
    "revenues": [
      12.73
    ],
    "revsVat": [
      14.26
    ]
  },
  {
    "dates": [
      "2026-02-24"
    ],
    "revenues": [
      33.21
    ],
    "revsVat": [
      37.2
    ]
  },
  {
    "dates": [
      "2026-02-24"
    ],
    "revenues": [
      33.92
    ],
    "revsVat": [
      37.98
    ]
  },
  {
    "dates": [
      "2026-02-24"
    ],
    "revenues": [
      38.15
    ],
    "revsVat": [
      42.72
    ]
  },
  {
    "dates": [
      "2026-02-25",
      "2026-03-02",
      "2026-03-15",
      "2026-03-20"
    ],
    "revenues": [
      35.24,
      26.81,
      13.45,
      35.3
    ],
    "revsVat": [
      39.46,
      30.03,
      15.07,
      39.55
    ]
  },
  {
    "dates": [
      "2026-02-25"
    ],
    "revenues": [
      28.68
    ],
    "revsVat": [
      32.12
    ]
  },
  {
    "dates": [
      "2026-02-25"
    ],
    "revenues": [
      30.88
    ],
    "revsVat": [
      34.59
    ]
  },
  {
    "dates": [
      "2026-02-25"
    ],
    "revenues": [
      18.46
    ],
    "revsVat": [
      20.67
    ]
  },
  {
    "dates": [
      "2026-02-26"
    ],
    "revenues": [
      41.05
    ],
    "revsVat": [
      45.98
    ]
  },
  {
    "dates": [
      "2026-02-26"
    ],
    "revenues": [
      29.34
    ],
    "revsVat": [
      32.86
    ]
  },
  {
    "dates": [
      "2026-02-26",
      "2026-03-16",
      "2026-04-06"
    ],
    "revenues": [
      27.21,
      27.23,
      39.54
    ],
    "revsVat": [
      30.47,
      30.5,
      44.26
    ]
  },
  {
    "dates": [
      "2026-02-26"
    ],
    "revenues": [
      20.99
    ],
    "revsVat": [
      23.5
    ]
  },
  {
    "dates": [
      "2026-02-26"
    ],
    "revenues": [
      12.2
    ],
    "revsVat": [
      13.66
    ]
  },
  {
    "dates": [
      "2026-02-26"
    ],
    "revenues": [
      30.12
    ],
    "revsVat": [
      33.73
    ]
  },
  {
    "dates": [
      "2026-02-26",
      "2026-03-13"
    ],
    "revenues": [
      41.91,
      116.26
    ],
    "revsVat": [
      46.94,
      130.21
    ]
  },
  {
    "dates": [
      "2026-02-26",
      "2026-03-26"
    ],
    "revenues": [
      18.68,
      48.98
    ],
    "revsVat": [
      20.91,
      54.86
    ]
  },
  {
    "dates": [
      "2026-02-27"
    ],
    "revenues": [
      54.85
    ],
    "revsVat": [
      61.43
    ]
  },
  {
    "dates": [
      "2026-02-27"
    ],
    "revenues": [
      64.99
    ],
    "revsVat": [
      72.79
    ]
  },
  {
    "dates": [
      "2026-02-27"
    ],
    "revenues": [
      35.83
    ],
    "revsVat": [
      40.13
    ]
  },
  {
    "dates": [
      "2026-02-27"
    ],
    "revenues": [
      38.93
    ],
    "revsVat": [
      43.6
    ]
  },
  {
    "dates": [
      "2026-02-27"
    ],
    "revenues": [
      41.14
    ],
    "revsVat": [
      46.08
    ]
  },
  {
    "dates": [
      "2026-02-27"
    ],
    "revenues": [
      41.5
    ],
    "revsVat": [
      46.48
    ]
  },
  {
    "dates": [
      "2026-02-28"
    ],
    "revenues": [
      29.4
    ],
    "revsVat": [
      32.92
    ]
  },
  {
    "dates": [
      "2026-02-28"
    ],
    "revenues": [
      18.45
    ],
    "revsVat": [
      20.66
    ]
  },
  {
    "dates": [
      "2026-03-01"
    ],
    "revenues": [
      21.77
    ],
    "revsVat": [
      24.38
    ]
  },
  {
    "dates": [
      "2026-03-01"
    ],
    "revenues": [
      33.43
    ],
    "revsVat": [
      37.45
    ]
  },
  {
    "dates": [
      "2026-03-02"
    ],
    "revenues": [
      36.34
    ],
    "revsVat": [
      40.7
    ]
  },
  {
    "dates": [
      "2026-03-02",
      "2026-03-15"
    ],
    "revenues": [
      60.18,
      64.63
    ],
    "revsVat": [
      67.4,
      72.39
    ]
  },
  {
    "dates": [
      "2026-03-02"
    ],
    "revenues": [
      27.18
    ],
    "revsVat": [
      30.44
    ]
  },
  {
    "dates": [
      "2026-03-03"
    ],
    "revenues": [
      56.13
    ],
    "revsVat": [
      62.87
    ]
  },
  {
    "dates": [
      "2026-03-03"
    ],
    "revenues": [
      66.01
    ],
    "revsVat": [
      73.94
    ]
  },
  {
    "dates": [
      "2026-03-03"
    ],
    "revenues": [
      32.94
    ],
    "revsVat": [
      36.9
    ]
  },
  {
    "dates": [
      "2026-03-04"
    ],
    "revenues": [
      29.6
    ],
    "revsVat": [
      33.15
    ]
  },
  {
    "dates": [
      "2026-03-05"
    ],
    "revenues": [
      55.94
    ],
    "revsVat": [
      62.67
    ]
  },
  {
    "dates": [
      "2026-03-05"
    ],
    "revenues": [
      42.04
    ],
    "revsVat": [
      47.08
    ]
  },
  {
    "dates": [
      "2026-03-06"
    ],
    "revenues": [
      55.69
    ],
    "revsVat": [
      62.37
    ]
  },
  {
    "dates": [
      "2026-03-06",
      "2026-03-18"
    ],
    "revenues": [
      23.61,
      14.58
    ],
    "revsVat": [
      26.45,
      16.33
    ]
  },
  {
    "dates": [
      "2026-03-06"
    ],
    "revenues": [
      36.92
    ],
    "revsVat": [
      36.92
    ]
  },
  {
    "dates": [
      "2026-03-07"
    ],
    "revenues": [
      43.8
    ],
    "revsVat": [
      49.05
    ]
  },
  {
    "dates": [
      "2026-03-08"
    ],
    "revenues": [
      29.56
    ],
    "revsVat": [
      33.11
    ]
  },
  {
    "dates": [
      "2026-03-08"
    ],
    "revenues": [
      19.65
    ],
    "revsVat": [
      22.01
    ]
  },
  {
    "dates": [
      "2026-03-08",
      "2026-04-04"
    ],
    "revenues": [
      41.6,
      29.04
    ],
    "revsVat": [
      46.59,
      32.52
    ]
  },
  {
    "dates": [
      "2026-03-08"
    ],
    "revenues": [
      38.23
    ],
    "revsVat": [
      42.82
    ]
  },
  {
    "dates": [
      "2026-03-09"
    ],
    "revenues": [
      58.39
    ],
    "revsVat": [
      65.4
    ]
  },
  {
    "dates": [
      "2026-03-09"
    ],
    "revenues": [
      49.6
    ],
    "revsVat": [
      55.56
    ]
  },
  {
    "dates": [
      "2026-03-12",
      "2026-03-22"
    ],
    "revenues": [
      28.18,
      49.32
    ],
    "revsVat": [
      31.55,
      55.24
    ]
  },
  {
    "dates": [
      "2026-03-12"
    ],
    "revenues": [
      24.84
    ],
    "revsVat": [
      27.82
    ]
  },
  {
    "dates": [
      "2026-03-13"
    ],
    "revenues": [
      26.63
    ],
    "revsVat": [
      29.82
    ]
  },
  {
    "dates": [
      "2026-03-13"
    ],
    "revenues": [
      74.54
    ],
    "revsVat": [
      83.5
    ]
  },
  {
    "dates": [
      "2026-03-13"
    ],
    "revenues": [
      83.51
    ],
    "revsVat": [
      93.53
    ]
  },
  {
    "dates": [
      "2026-03-14"
    ],
    "revenues": [
      49
    ],
    "revsVat": [
      54.88
    ]
  },
  {
    "dates": [
      "2026-03-15"
    ],
    "revenues": [
      13.78
    ],
    "revsVat": [
      15.43
    ]
  },
  {
    "dates": [
      "2026-03-15"
    ],
    "revenues": [
      50.97
    ],
    "revsVat": [
      57.1
    ]
  },
  {
    "dates": [
      "2026-03-16",
      "2026-03-26"
    ],
    "revenues": [
      98.46,
      113.45
    ],
    "revsVat": [
      110.28,
      127.09
    ]
  },
  {
    "dates": [
      "2026-03-16"
    ],
    "revenues": [
      33.31
    ],
    "revsVat": [
      37.31
    ]
  },
  {
    "dates": [
      "2026-03-16"
    ],
    "revenues": [
      58.05
    ],
    "revsVat": [
      65
    ]
  },
  {
    "dates": [
      "2026-03-16"
    ],
    "revenues": [
      32.06
    ],
    "revsVat": [
      35.9
    ]
  },
  {
    "dates": [
      "2026-03-17"
    ],
    "revenues": [
      40.02
    ],
    "revsVat": [
      44.83
    ]
  },
  {
    "dates": [
      "2026-03-17"
    ],
    "revenues": [
      13.12
    ],
    "revsVat": [
      14.7
    ]
  },
  {
    "dates": [
      "2026-03-17"
    ],
    "revenues": [
      19.12
    ],
    "revsVat": [
      21.41
    ]
  },
  {
    "dates": [
      "2026-03-18"
    ],
    "revenues": [
      26.57
    ],
    "revsVat": [
      29.77
    ]
  },
  {
    "dates": [
      "2026-03-18"
    ],
    "revenues": [
      66.1
    ],
    "revsVat": [
      74.01
    ]
  },
  {
    "dates": [
      "2026-03-18"
    ],
    "revenues": [
      317.49
    ],
    "revsVat": [
      317.49
    ]
  },
  {
    "dates": [
      "2026-03-18"
    ],
    "revenues": [
      26.29
    ],
    "revsVat": [
      29.45
    ]
  },
  {
    "dates": [
      "2026-03-18"
    ],
    "revenues": [
      49.13
    ],
    "revsVat": [
      49.13
    ]
  },
  {
    "dates": [
      "2026-03-19"
    ],
    "revenues": [
      27.54
    ],
    "revsVat": [
      30.84
    ]
  },
  {
    "dates": [
      "2026-03-19"
    ],
    "revenues": [
      47.78
    ],
    "revsVat": [
      53.5
    ]
  },
  {
    "dates": [
      "2026-03-20"
    ],
    "revenues": [
      25.71
    ],
    "revsVat": [
      28.79
    ]
  },
  {
    "dates": [
      "2026-03-20"
    ],
    "revenues": [
      48.38
    ],
    "revsVat": [
      54.2
    ]
  },
  {
    "dates": [
      "2026-03-20"
    ],
    "revenues": [
      100.52
    ],
    "revsVat": [
      112.58
    ]
  },
  {
    "dates": [
      "2026-03-21"
    ],
    "revenues": [
      49.04
    ],
    "revsVat": [
      54.93
    ]
  },
  {
    "dates": [
      "2026-03-21"
    ],
    "revenues": [
      50.41
    ],
    "revsVat": [
      56.46
    ]
  },
  {
    "dates": [
      "2026-03-21"
    ],
    "revenues": [
      26.49
    ],
    "revsVat": [
      29.67
    ]
  },
  {
    "dates": [
      "2026-03-21"
    ],
    "revenues": [
      35.67
    ],
    "revsVat": [
      39.94
    ]
  },
  {
    "dates": [
      "2026-03-21"
    ],
    "revenues": [
      23.54
    ],
    "revsVat": [
      26.37
    ]
  },
  {
    "dates": [
      "2026-03-22"
    ],
    "revenues": [
      52.33
    ],
    "revsVat": [
      58.61
    ]
  },
  {
    "dates": [
      "2026-03-22"
    ],
    "revenues": [
      75.41
    ],
    "revsVat": [
      84.45
    ]
  },
  {
    "dates": [
      "2026-03-23"
    ],
    "revenues": [
      52.98
    ],
    "revsVat": [
      59.34
    ]
  },
  {
    "dates": [
      "2026-03-23"
    ],
    "revenues": [
      26.16
    ],
    "revsVat": [
      29.3
    ]
  },
  {
    "dates": [
      "2026-03-24"
    ],
    "revenues": [
      24.76
    ],
    "revsVat": [
      27.74
    ]
  },
  {
    "dates": [
      "2026-03-24"
    ],
    "revenues": [
      12.8
    ],
    "revsVat": [
      14.34
    ]
  },
  {
    "dates": [
      "2026-03-24"
    ],
    "revenues": [
      50.25
    ],
    "revsVat": [
      56.29
    ]
  },
  {
    "dates": [
      "2026-03-24"
    ],
    "revenues": [
      68.44
    ],
    "revsVat": [
      76.65
    ]
  },
  {
    "dates": [
      "2026-03-25"
    ],
    "revenues": [
      24.73
    ],
    "revsVat": [
      27.7
    ]
  },
  {
    "dates": [
      "2026-03-25"
    ],
    "revenues": [
      110.8
    ],
    "revsVat": [
      124.1
    ]
  },
  {
    "dates": [
      "2026-03-25"
    ],
    "revenues": [
      112.65
    ],
    "revsVat": [
      126.18
    ]
  },
  {
    "dates": [
      "2026-03-25"
    ],
    "revenues": [
      18.3
    ],
    "revsVat": [
      20.49
    ]
  },
  {
    "dates": [
      "2026-03-25"
    ],
    "revenues": [
      81.85
    ],
    "revsVat": [
      91.67
    ]
  },
  {
    "dates": [
      "2026-03-26"
    ],
    "revenues": [
      89.22
    ],
    "revsVat": [
      99.93
    ]
  },
  {
    "dates": [
      "2026-03-27"
    ],
    "revenues": [
      10.8
    ],
    "revsVat": [
      12.1
    ]
  },
  {
    "dates": [
      "2026-03-27"
    ],
    "revenues": [
      22.07
    ],
    "revsVat": [
      24.73
    ]
  },
  {
    "dates": [
      "2026-03-28"
    ],
    "revenues": [
      14.87
    ],
    "revsVat": [
      16.66
    ]
  },
  {
    "dates": [
      "2026-03-28"
    ],
    "revenues": [
      81.95
    ],
    "revsVat": [
      81.95
    ]
  },
  {
    "dates": [
      "2026-03-28"
    ],
    "revenues": [
      66.03
    ],
    "revsVat": [
      73.95
    ]
  },
  {
    "dates": [
      "2026-03-29"
    ],
    "revenues": [
      47.94
    ],
    "revsVat": [
      53.67
    ]
  },
  {
    "dates": [
      "2026-03-29"
    ],
    "revenues": [
      24.17
    ],
    "revsVat": [
      27.06
    ]
  },
  {
    "dates": [
      "2026-03-31"
    ],
    "revenues": [
      49.13
    ],
    "revsVat": [
      55.01
    ]
  },
  {
    "dates": [
      "2026-03-31"
    ],
    "revenues": [
      54.19
    ],
    "revsVat": [
      60.69
    ]
  },
  {
    "dates": [
      "2026-04-03"
    ],
    "revenues": [
      13.07
    ],
    "revsVat": [
      14.63
    ]
  },
  {
    "dates": [
      "2026-04-03"
    ],
    "revenues": [
      26.47
    ],
    "revsVat": [
      29.63
    ]
  },
  {
    "dates": [
      "2026-04-04"
    ],
    "revenues": [
      17
    ],
    "revsVat": [
      19.04
    ]
  },
  {
    "dates": [
      "2026-04-11"
    ],
    "revenues": [
      26.32
    ],
    "revsVat": [
      29.47
    ]
  }
];
