// Auto-generated by scripts/updateData.js — last update: 2026-07-11
// SK: per-customer retention data (EUR)

export const retentionDataSK: { dates: string[]; revenues: number[]; revsVat: number[] }[] = [];
