// Auto-generated by scripts/updateData.js — last update: 2026-04-19
// SK: what customers paid for shipping & payment (EUR, cancelled excluded)

export interface ShippingPaymentRecord {
  date: string;         // ISO "2025-05-25"
  type: 'shipping' | 'payment';
  name: string;         // normalized method name e.g. "Zásilkovna", "Online platba kartou"
  count: number;        // number of orders using this method on this day
  revenue_vat: number;  // total paid by customers incl. VAT
}

export const shippingPaymentDataSK: ShippingPaymentRecord[] = [
  {
    "date": "2025-12-09",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-09",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-09",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 3,
    "revenue_vat": 7
  },
  {
    "date": "2025-12-10",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 4,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-10",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 4,
    "revenue_vat": 10.5
  },
  {
    "date": "2025-12-11",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-11",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-11",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-11",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2025-12-12",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-12",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2025-12-13",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-13",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2025-12-14",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-14",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-15",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-15",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-15",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 7
  },
  {
    "date": "2025-12-16",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-16",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2025-12-17",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-17",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 4.3
  },
  {
    "date": "2025-12-17",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 3.5
  },
  {
    "date": "2025-12-18",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-18",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-18",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2025-12-18",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 3,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-01-04",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-04",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-01-05",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-05",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-05",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 2,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-01-05",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 3,
    "revenue_vat": 7
  },
  {
    "date": "2026-01-06",
    "type": "payment",
    "name": "Apple Pay",
    "count": 4,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-06",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-06",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-06",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 6,
    "revenue_vat": 21
  },
  {
    "date": "2026-01-07",
    "type": "payment",
    "name": "Apple Pay",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-07",
    "type": "payment",
    "name": "Google Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-07",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 6,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-07",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-01-07",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 10,
    "revenue_vat": 28
  },
  {
    "date": "2026-01-08",
    "type": "payment",
    "name": "Apple Pay",
    "count": 5,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-08",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-08",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-08",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-08",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 8,
    "revenue_vat": 24.5
  },
  {
    "date": "2026-01-09",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-09",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-09",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-01-10",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-10",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-10",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-10",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 6,
    "revenue_vat": 17.5
  },
  {
    "date": "2026-01-11",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-11",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-11",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-11",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-11",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 4,
    "revenue_vat": 10.5
  },
  {
    "date": "2026-01-12",
    "type": "payment",
    "name": "Apple Pay",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-12",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-12",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-01-13",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-13",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 4,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-13",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-01-13",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 5,
    "revenue_vat": 10.5
  },
  {
    "date": "2026-01-14",
    "type": "payment",
    "name": "Apple Pay",
    "count": 4,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-14",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 4,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-14",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 3,
    "revenue_vat": 3.84
  },
  {
    "date": "2026-01-14",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 5,
    "revenue_vat": 17.5
  },
  {
    "date": "2026-01-15",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-15",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-15",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-01-15",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-01-16",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-16",
    "type": "payment",
    "name": "Google Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-16",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-16",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-01-16",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 5,
    "revenue_vat": 10.5
  },
  {
    "date": "2026-01-17",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-17",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-18",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-18",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-18",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 3,
    "revenue_vat": 7
  },
  {
    "date": "2026-01-19",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-19",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-19",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-01-19",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 7
  },
  {
    "date": "2026-01-20",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-20",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-01-20",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-01-21",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-21",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-21",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 2,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-01-23",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-23",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-23",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 3,
    "revenue_vat": 10.5
  },
  {
    "date": "2026-01-24",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-24",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-01-25",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-25",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-25",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-25",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 4,
    "revenue_vat": 7
  },
  {
    "date": "2026-01-26",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-26",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-26",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 7
  },
  {
    "date": "2026-01-30",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-30",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-01-31",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-01-31",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-02-02",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-02",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-02",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 7
  },
  {
    "date": "2026-02-03",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-03",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-03",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 7
  },
  {
    "date": "2026-02-04",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-04",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-04",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 3,
    "revenue_vat": 10.5
  },
  {
    "date": "2026-02-05",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-05",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-05",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 3,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-02-05",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-02-06",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-06",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-06",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-06",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 7
  },
  {
    "date": "2026-02-07",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 4,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-07",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-07",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 3,
    "revenue_vat": 10.5
  },
  {
    "date": "2026-02-08",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-08",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-08",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 3,
    "revenue_vat": 10.5
  },
  {
    "date": "2026-02-09",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-09",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-02-10",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-10",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-10",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-10",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 3,
    "revenue_vat": 10.5
  },
  {
    "date": "2026-02-11",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 5,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-11",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 5,
    "revenue_vat": 10.5
  },
  {
    "date": "2026-02-12",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-12",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-02-15",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-15",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-02-16",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-16",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-02-17",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-17",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-18",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-18",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-18",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 4,
    "revenue_vat": 8.6
  },
  {
    "date": "2026-02-19",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-19",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-20",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-20",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 7
  },
  {
    "date": "2026-02-21",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-21",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-02-24",
    "type": "payment",
    "name": "Apple Pay",
    "count": 4,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-24",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-24",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-25",
    "type": "payment",
    "name": "Apple Pay",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-25",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-25",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-25",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-25",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 4,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-26",
    "type": "payment",
    "name": "Google Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-26",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 6,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-26",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-26",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 5,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-02-27",
    "type": "payment",
    "name": "Apple Pay",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-27",
    "type": "payment",
    "name": "Google Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-27",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-27",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 5,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-27",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-28",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-28",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-28",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-02-28",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-01",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-01",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-01",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-02",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-02",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 4,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-02",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-02",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-03",
    "type": "payment",
    "name": "Apple Pay",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-03",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-03",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-04",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-04",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-05",
    "type": "payment",
    "name": "Google Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-05",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-05",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-05",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-06",
    "type": "payment",
    "name": "Apple Pay",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-06",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-06",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-07",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-07",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-08",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-08",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 4,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-08",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-08",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-09",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-09",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-09",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-09",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 7
  },
  {
    "date": "2026-03-12",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-12",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-12",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 7
  },
  {
    "date": "2026-03-13",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-13",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-13",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-13",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-13",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-03-14",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-14",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-03-15",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-15",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-15",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 5,
    "revenue_vat": 10.5
  },
  {
    "date": "2026-03-16",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-16",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-16",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 5,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-16",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 3,
    "revenue_vat": 8.14
  },
  {
    "date": "2026-03-16",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 4,
    "revenue_vat": 7
  },
  {
    "date": "2026-03-17",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-17",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 2,
    "revenue_vat": 8.6
  },
  {
    "date": "2026-03-17",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-03-18",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-18",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-18",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-18",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 3,
    "revenue_vat": 3.84
  },
  {
    "date": "2026-03-18",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 3,
    "revenue_vat": 10.5
  },
  {
    "date": "2026-03-19",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-19",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-19",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 2,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-03-19",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-03-20",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-20",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-20",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-20",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-20",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 3,
    "revenue_vat": 7
  },
  {
    "date": "2026-03-21",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-21",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 4,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-21",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 5,
    "revenue_vat": 14
  },
  {
    "date": "2026-03-22",
    "type": "payment",
    "name": "Google Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-22",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-22",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-22",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-23",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-23",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-23",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-23",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-03-24",
    "type": "payment",
    "name": "Google Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-24",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-24",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-24",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 3,
    "revenue_vat": 10.5
  },
  {
    "date": "2026-03-25",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 5,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-25",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 4,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-03-25",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-03-26",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-26",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 3,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-26",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-26",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-27",
    "type": "payment",
    "name": "Google Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-27",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-27",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 3,
    "revenue_vat": 10.5
  },
  {
    "date": "2026-03-28",
    "type": "payment",
    "name": "Apple Pay",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-28",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-28",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 2,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-03-28",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-29",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-29",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-29",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-03-29",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-03-31",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-31",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-03-31",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-01",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-01",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-03",
    "type": "payment",
    "name": "Google Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-03",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-03",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 7
  },
  {
    "date": "2026-04-04",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-04",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-04-06",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-06",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-04-11",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-11",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 1,
    "revenue_vat": 4.3
  },
  {
    "date": "2026-04-12",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-12",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-14",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-14",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-14",
    "type": "shipping",
    "name": "Zásilkovna na adresu SK",
    "count": 2,
    "revenue_vat": 3.84
  },
  {
    "date": "2026-04-14",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-16",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-16",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 2,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-16",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 3,
    "revenue_vat": 7
  },
  {
    "date": "2026-04-17",
    "type": "payment",
    "name": "Apple Pay",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-17",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-17",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 2,
    "revenue_vat": 3.5
  },
  {
    "date": "2026-04-18",
    "type": "payment",
    "name": "Online platba kartou",
    "count": 1,
    "revenue_vat": 0
  },
  {
    "date": "2026-04-18",
    "type": "shipping",
    "name": "Zásilkovna na výdejní místo SK",
    "count": 1,
    "revenue_vat": 3.5
  }
];
