// Auto-generated by scripts/updateData.js — last update: 2026-06-19
// CZ: stock levels per product (live from Google Sheets)

export interface StockRecord {
  code: string;
  name: string;
  stock: number;
}

export const stockDataCZ: StockRecord[] = [
  {
    "code": "384",
    "name": "Dárkový box Ovocná kolekce DELUXE",
    "stock": 0
  },
  {
    "code": "383",
    "name": "Dárkový box Ovocná radost",
    "stock": 0
  },
  {
    "code": "422",
    "name": "Datle Medjool Premium 100g",
    "stock": 3
  },
  {
    "code": "423",
    "name": "Datle Medjool Premium 500g",
    "stock": 8
  },
  {
    "code": "411",
    "name": "Elektronický dárkový poukaz 1000Kč",
    "stock": 9
  },
  {
    "code": "410",
    "name": "Elektronický dárkový poukaz 500Kč",
    "stock": 9
  },
  {
    "code": "288",
    "name": "Jablečné křížaly 100g - česká jablka",
    "stock": 0
  },
  {
    "code": "34",
    "name": "Jablečné křížaly 25g - česká jablka",
    "stock": 45
  },
  {
    "code": "415",
    "name": "Jablečné křížaly 500g - česká jablka",
    "stock": 10
  },
  {
    "code": "126",
    "name": "Jablečné kuličky natural RAW (32g)",
    "stock": 71
  },
  {
    "code": "127",
    "name": "Jablečné kuličky natural RAW 10 + 1 ZDARMA",
    "stock": 8
  },
  {
    "code": "413",
    "name": "Jablečné kuličky natural RAW GASTRO 850g",
    "stock": 6
  },
  {
    "code": "124",
    "name": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU (100g)",
    "stock": 20
  },
  {
    "code": "125",
    "name": "Jablečné kuličky s čokoládovou polevou BEZ PALMOVÉHO TUKU 10 + 1 ZDARMA",
    "stock": 1
  },
  {
    "code": "118",
    "name": "Jablečné kuličky s jahodovou polevou a kokosem (32g)",
    "stock": 37
  },
  {
    "code": "432",
    "name": "Jablečné kuličky s jahodovou polevou a kokosem (32g) 30x32g",
    "stock": 2
  },
  {
    "code": "119",
    "name": "Jablečné kuličky s jahodovou polevou a kokosem 10 + 1 ZDARMA",
    "stock": 6
  },
  {
    "code": "412",
    "name": "Jablečné kuličky s jahodovou polevou a kokosem GASTRO 850g",
    "stock": 4
  },
  {
    "code": "120",
    "name": "Jablečné kuličky s jogurtovou polevou a kokosem (32g)",
    "stock": 38
  },
  {
    "code": "121",
    "name": "Jablečné kuličky s jogurtovou polevou a kokosem (32g) 10 + 1 ZDARMA",
    "stock": 7
  },
  {
    "code": "431",
    "name": "Jablečné kuličky s jogurtovou polevou a kokosem (32g) 30x32g",
    "stock": 2
  },
  {
    "code": "414",
    "name": "Jablečné kuličky s jogurtovou polevou a kokosem GASTRO 850g",
    "stock": 2
  },
  {
    "code": "99",
    "name": "Jablečné trubičky 2ks - MIX",
    "stock": 24
  },
  {
    "code": "87",
    "name": "Jablečné trubičky s čokoládovou polevou 2ks (24g)",
    "stock": 21
  },
  {
    "code": "429",
    "name": "Jablečné trubičky s čokoládovou polevou 2ks (24g) 30x24g",
    "stock": 3
  },
  {
    "code": "85",
    "name": "Jablečné trubičky s čokoládovou polevou 43ks (540g)",
    "stock": 22
  },
  {
    "code": "90",
    "name": "Jablečné trubičky s čokoládovou polevou 500ks GASTRO",
    "stock": 3
  },
  {
    "code": "91",
    "name": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g)",
    "stock": 18
  },
  {
    "code": "430",
    "name": "Jablečné trubičky s čokoládovou polevou a černým rybízem 2ks (24g) 30x24g",
    "stock": 2
  },
  {
    "code": "86",
    "name": "Jablečné trubičky s čokoládovou polevou a černým rybízem 43ks (540g)",
    "stock": 11
  },
  {
    "code": "104",
    "name": "Jablečné trubičky s čokoládovou polevou a višní 43ks (540g)",
    "stock": 16
  },
  {
    "code": "96",
    "name": "Jablečné trubičky s čokoládovou polevou bez palmového tuku 43ks (540g)",
    "stock": 9
  },
  {
    "code": "98",
    "name": "Jablečné trubičky s čokoládovou polevou bez přidaného cukru 43ks (540g)",
    "stock": 21
  },
  {
    "code": "433",
    "name": "Jablečné trubičky s hořkou čokoládou 70% 18ks (220g)",
    "stock": 11
  },
  {
    "code": "94",
    "name": "Jablečné trubičky s jahodovou polevou 2ks (24g)",
    "stock": 27
  },
  {
    "code": "427",
    "name": "Jablečné trubičky s jahodovou polevou 2ks (24g) 30x24g",
    "stock": 2
  },
  {
    "code": "93",
    "name": "Jablečné trubičky s jahodovou polevou 43ks (540g)",
    "stock": 26
  },
  {
    "code": "89",
    "name": "Jablečné trubičky s jogurtovou polevou 2ks (24g)",
    "stock": 24
  },
  {
    "code": "428",
    "name": "Jablečné trubičky s jogurtovou polevou 2ks (24g) 30x24g",
    "stock": 2
  },
  {
    "code": "84",
    "name": "Jablečné trubičky s jogurtovou polevou 43ks (540g)",
    "stock": 57
  },
  {
    "code": "88",
    "name": "Jablečné trubičky s jogurtovou polevou 500ks GASTRO",
    "stock": 2
  },
  {
    "code": "106",
    "name": "Jablečné trubičky s jogurtovou polevou a višní 43ks (540g)",
    "stock": 23
  },
  {
    "code": "100",
    "name": "Jablečné trubičky s karamelovou polevou 43ks (540g)",
    "stock": 14
  },
  {
    "code": "130",
    "name": "Jablečné trubičky s karobovou polevou 2ks (24g)",
    "stock": 7
  },
  {
    "code": "426",
    "name": "Jablečné trubičky s karobovou polevou 2ks (24g) 30x24g",
    "stock": 2
  },
  {
    "code": "102",
    "name": "Jablečné trubičky s karobovou polevou 43ks (540g)",
    "stock": 9
  },
  {
    "code": "434",
    "name": "Jablečné trubičky s mléčnou čokoládou 18ks (220g)",
    "stock": 35
  },
  {
    "code": "117",
    "name": "Jahodové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
    "stock": 8
  },
  {
    "code": "192",
    "name": "Lyofilizované jahody 100g",
    "stock": 0
  },
  {
    "code": "191",
    "name": "Lyofilizované jahody 15g",
    "stock": 0
  },
  {
    "code": "190",
    "name": "Lyofilizované maliny 100g",
    "stock": 10
  },
  {
    "code": "189",
    "name": "Lyofilizované maliny 15g",
    "stock": 0
  },
  {
    "code": "188",
    "name": "Lyofilizované mango 100g",
    "stock": 13
  },
  {
    "code": "187",
    "name": "Lyofilizované mango 15g",
    "stock": 57
  },
  {
    "code": "388",
    "name": "Lyofilizovaný ananas 100g",
    "stock": 86
  },
  {
    "code": "389",
    "name": "Lyofilizovaný ananas 15g",
    "stock": 59
  },
  {
    "code": "116",
    "name": "Malinové trubičky polomáčené s čokoládovou polevou bez palmového tuku 18ks (220g)",
    "stock": 0
  },
  {
    "code": "114",
    "name": "Mangové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
    "stock": 0
  },
  {
    "code": "115",
    "name": "Meruňkové trubičky polomáčené s jogurtovou polevou 18ks (220g)",
    "stock": 3
  },
  {
    "code": "142",
    "name": "MIX křížaly x hrušky 100g - české ovoce",
    "stock": 11
  },
  {
    "code": "143",
    "name": "MIX křížaly x hrušky 25g - české ovoce",
    "stock": 52
  },
  {
    "code": "148",
    "name": "Ovocné mlsání - černý rybíz (100g)",
    "stock": 30
  },
  {
    "code": "144",
    "name": "Ovocné mlsání - jahoda (100g)",
    "stock": 10
  },
  {
    "code": "146",
    "name": "Ovocné mlsání - malina (100g)",
    "stock": 37
  },
  {
    "code": "147",
    "name": "Ovocné mlsání - mango (100g)",
    "stock": 12
  },
  {
    "code": "145",
    "name": "Ovocné mlsání - meruňka (100g)",
    "stock": 10
  },
  {
    "code": "416",
    "name": "Ovocné mlsání - višeň (100g)",
    "stock": 0
  },
  {
    "code": "132",
    "name": "Ovocné trubičky - černý rybíz 10 + 1 ZDARMA",
    "stock": 8
  },
  {
    "code": "112",
    "name": "Ovocné trubičky - černý rybíz 2ks (25g)",
    "stock": 79
  },
  {
    "code": "193",
    "name": "Ovocné trubičky - černý rybíz 33ks (380g)",
    "stock": 7
  },
  {
    "code": "424",
    "name": "Ovocné trubičky - hruška 33ks (380g)",
    "stock": 23
  },
  {
    "code": "133",
    "name": "Ovocné trubičky - jablko 10 + 1 ZDARMA",
    "stock": 9
  },
  {
    "code": "113",
    "name": "Ovocné trubičky - jablko 2ks (25g)",
    "stock": 49
  },
  {
    "code": "194",
    "name": "Ovocné trubičky - jablko 33ks (380g)",
    "stock": 12
  },
  {
    "code": "134",
    "name": "Ovocné trubičky - jahoda 10 + 1 ZDARMA",
    "stock": 0
  },
  {
    "code": "109",
    "name": "Ovocné trubičky - jahoda 2ks (25g)",
    "stock": 67
  },
  {
    "code": "195",
    "name": "Ovocné trubičky - jahoda 33ks (380g)",
    "stock": 24
  },
  {
    "code": "131",
    "name": "Ovocné trubičky - malina 10 + 1 ZDARMA",
    "stock": 9
  },
  {
    "code": "108",
    "name": "Ovocné trubičky - malina 2ks (25g)",
    "stock": 67
  },
  {
    "code": "196",
    "name": "Ovocné trubičky - malina 33ks (380g)",
    "stock": 37
  },
  {
    "code": "135",
    "name": "Ovocné trubičky - mango 10 + 1 ZDARMA",
    "stock": 9
  },
  {
    "code": "110",
    "name": "Ovocné trubičky - mango 2ks (25g)",
    "stock": 100
  },
  {
    "code": "198",
    "name": "Ovocné trubičky - mango 33ks (380g)",
    "stock": 23
  },
  {
    "code": "136",
    "name": "Ovocné trubičky - meruňka 10 + 1 ZDARMA",
    "stock": 9
  },
  {
    "code": "111",
    "name": "Ovocné trubičky - meruňka 2ks (25g)",
    "stock": 61
  },
  {
    "code": "197",
    "name": "Ovocné trubičky - meruňka 33ks (380g)",
    "stock": 11
  },
  {
    "code": "137",
    "name": "Ovocné trubičky - MIX",
    "stock": 8
  },
  {
    "code": "425",
    "name": "Ovocné trubičky - švestka 33ks (380g)",
    "stock": 34
  },
  {
    "code": "417",
    "name": "Ovocné trubičky - višeň 33ks (380g)",
    "stock": 27
  },
  {
    "code": "141",
    "name": "Sušené hrušky 100g - české ovoce",
    "stock": 12
  },
  {
    "code": "140",
    "name": "Sušené hrušky 25g - české ovoce",
    "stock": 24
  },
  {
    "code": "154",
    "name": "Sušené mango Premium 100g",
    "stock": 0
  },
  {
    "code": "153",
    "name": "Sušené mango Premium 25g",
    "stock": 0
  },
  {
    "code": "385",
    "name": "Sušené mango Premium 500g",
    "stock": 0
  },
  {
    "code": "418",
    "name": "Sušené meruňky Premium 100g",
    "stock": 10
  },
  {
    "code": "419",
    "name": "Sušené meruňky Premium 500g",
    "stock": 1
  },
  {
    "code": "420",
    "name": "Sušené švestky Premium 100g",
    "stock": 29
  },
  {
    "code": "421",
    "name": "Sušené švestky Premium 500g",
    "stock": 4
  },
  {
    "code": "386",
    "name": "Sušený ananas Premium 100g",
    "stock": 7
  },
  {
    "code": "387",
    "name": "Sušený ananas Premium 500g",
    "stock": 12
  }
];
